BIBSYSDEV/NVA-Frontend

src/components/login/Login.tsx
src/styles/App.scss
src/styles/variables.scss

de-quoting

---

package.json
template.yml

Cloudformation template for creating S3 bucket 

---

src/api/mock-interceptor.ts
src/api/resource.ts
src/pages/resource/DescriptionPanel.tsx
src/pages/resource/LinkPublicationPanel.tsx
src/pages/resource/LinkPublicationPanelForm.tsx
src/translations/en/translations.json
src/translations/nb/translations.json
src/utils/constants.ts
src/utils/testfiles/doi_lookup_response.json

(bør ikke merges inn før sarahs oppdartering)

Np 199 add form controll to doi

---

src/pages/resource/DescriptionPanel.tsx
src/pages/resource/ReferencesPanel.tsx
src/pages/resource/ResourceForm.tsx
src/redux/actions/formsDataActions.ts
src/redux/reducers/formsDataReducer.ts
src/types/form.types.ts
src/utils/hooks/useFormPersistor.ts
src/utils/hooks/useLocalStorage.ts

Har ikke tatt med data fra contributors i denne PRen siden contributors må uansett refaktoreres

Np 244  persist form data to localstorage

---

src/pages/publication/ReferencesPanel.tsx
src/pages/publication/references_tab/BookReferenceForm.tsx
src/pages/publication/references_tab/ChapterReferenceForm.tsx
src/pages/publication/references_tab/DegreeReferenceForm.tsx
src/pages/publication/references_tab/JournalPublicationReferenceForm.tsx
src/pages/publication/references_tab/ReportReferenceForm.tsx
src/redux/actions/formsDataActions.ts
src/redux/reducers/formsDataReducer.ts
src/themes/mainTheme.ts
src/translations/en/publication.json
src/translations/nb/publication.json
src/types/form.types.ts
src/types/references.types.ts
src/utils/hooks/useFormPersistor.ts

Kan egentlig se bort fra redux-ting, siden det forsvinner i neste refaktorering uansett

Np 126 reference form

---

src/api/publicationChannelApi.ts
src/pages/publication/files_and_license_tab/PublicationChannelInfoCard.tsx
src/types/references.types.ts

Bruk open access info fra backend

Np 422 kanalreg license

---

package-lock.json
package.json

https://stackoverflow.com/a/24596500

Remove obsolete package

---

buildspec.yml
templates/sar_application_template.yml

Added missing buildspec-file file and orcid properties

pr-np-561-fix

---

templates/pipeline_publish_sar_template.yml
templates/pipeline_template.yml

Invalidating cloudfront distribution

---

src/pages/publication/ContributorsPanel.tsx
src/pages/publication/PublicationPage.tsx
src/pages/publication/PublishedPublicationList.tsx
src/pages/publication/contributors_tab/components/SortableTable.tsx
src/pages/publication/publication_page/PublicationPageAuthors.tsx
src/pages/publication/submission_tab/submission_contributors.tsx
src/types/contributor.types.ts
src/types/publication.types.ts
src/utils/testfiles/my_publications.json
src/utils/testfiles/publication_generated.json

Venter avklaringer på hvordan strukturen skal være for affiliations, så ingen endringer der enda

Np 590 contributors tab

---

src/pages/publication/contributors_tab/components/SortableTable.tsx
src/utils/helpers.ts

We need to fix this again once all contributors are assigned an id in the future

populate contributors in contributors tab

---

src/pages/publication/FilesAndLicensePanel.tsx
src/pages/publication/PublishedPublicationList.tsx
src/pages/publication/publication_page/PublicationPageJournal.tsx
src/pages/publication/publication_page/PublicationPageSeries.tsx
src/pages/publication/references_tab/BookReferenceForm.tsx
src/pages/publication/references_tab/ChapterReferenceForm.tsx
src/pages/publication/references_tab/DegreeReferenceForm.tsx
src/pages/publication/references_tab/JournalArticleReferenceForm.tsx
src/pages/publication/references_tab/ReportReferenceForm.tsx
src/pages/publication/submission_tab/submission_book.tsx
src/pages/publication/submission_tab/submission_chapter.tsx
src/pages/publication/submission_tab/submission_degree.tsx
src/pages/publication/submission_tab/submission_journal.tsx
src/pages/publication/submission_tab/submission_report.tsx
src/translations/en/referenceTypes.json
src/translations/nb/referenceTypes.json
src/types/publication.types.ts
src/types/references.types.ts
src/utils/testfiles/my_publications.json

ble litt stor denne... :/
blir fort noen små endringer i etterkant også, hvis backend bruker andre navn enn oss på noen properties, men vi er hvertfall på samme struktur nå

Np 589 prefill references

---

package-lock.json
package.json
src/api/publicationApi.ts
src/pages/publication/ContributorsPanel.tsx
src/pages/publication/DescriptionPanel.tsx
src/pages/publication/FilesAndLicensePanel.tsx
src/pages/publication/PublicationForm.tsx
src/pages/publication/PublicationFormTabs.tsx
src/pages/publication/ReferencesPanel.tsx
src/pages/publication/SubmissionPanel.tsx
src/pages/publication/contributors_tab/components/SortableTable.tsx
src/pages/publication/description_tab/DatePickerField.tsx
src/pages/publication/description_tab/ProjectSearch.tsx
src/pages/publication/references_tab/BookReferenceForm.tsx
src/pages/publication/references_tab/DegreeReferenceForm.tsx
src/pages/publication/references_tab/JournalArticleReferenceForm.tsx
src/pages/publication/references_tab/ReportReferenceForm.tsx
src/pages/publication/references_tab/components/DoiField.tsx
src/pages/publication/references_tab/components/PeerReview.tsx
src/pages/publication/submission_tab/submission_book.tsx
src/pages/publication/submission_tab/submission_chapter.tsx
src/pages/publication/submission_tab/submission_contributors.tsx
src/pages/publication/submission_tab/submission_degree.tsx
src/pages/publication/submission_tab/submission_description.tsx
src/pages/publication/submission_tab/submission_files_licenses.tsx
src/pages/publication/submission_tab/submission_journal.tsx
src/pages/publication/submission_tab/submission_report.tsx
src/pages/worklist/WorkListTable.tsx
src/types/publication.types.ts

ingen ny funksjonalitet, så vi kan vente med å merge til etter demo

Np 643 merge publication types

---

package-lock.json
package.json
src/api/userApi.ts

Kilde på discontinuation:
https://github.com/amazon-archives/amazon-cognito-identity-js#amazon-cognito-identity-sdk-for-javascript

NP-648 Remove dependency to discontinued repository

---

package-lock.json
package.json

Reverts BIBSYSDEV/NVA-Frontend#377

Revert "Bump react-dom from 16.13.0 to 16.13.1"

---

package-lock.json
package.json

Reverts BIBSYSDEV/NVA-Frontend#378

Revert "Bump react-scripts from 3.4.0 to 3.4.1"

---

src/components/AutoSearch.tsx
src/pages/publication/FilesAndLicensePanel.tsx
src/pages/publication/PublicationForm.tsx
src/pages/publication/PublicationFormValidationSchema.ts
src/pages/publication/PublishedPublicationList.tsx
src/pages/publication/ReferencesPanel.tsx
src/pages/publication/references_tab/BookReferenceForm.tsx
src/pages/publication/references_tab/DegreeReferenceForm.tsx
src/pages/publication/references_tab/JournalArticleReferenceForm.tsx
src/pages/publication/references_tab/ReportReferenceForm.tsx
src/pages/publication/references_tab/components/PublicationChannelSearch.tsx
src/pages/publication/references_tab/components/PublisherField.tsx
src/pages/publication/references_tab/components/SelectTypeField.tsx
src/pages/publication/submission_tab/submission_book.tsx
src/pages/publication/submission_tab/submission_degree.tsx
src/pages/publication/submission_tab/submission_journal.tsx
src/pages/publication/submission_tab/submission_report.tsx
src/translations/en/referenceTypes.json
src/translations/nb/referenceTypes.json
src/types/publication.types.ts

må sikkert endre noen ting her også når v0.4 av datamodell kommer, men det får bli en egen sak

Np 655 validate references

---

cypress/integration/edit_publication.spec.js
package-lock.json
src/App.tsx
src/api/authorityApi.ts
src/api/mock-interceptor.ts
src/pages/user/User.tsx
src/pages/user/authority/ConnectAuthority.tsx
src/pages/user/authority/NewAuthorityCard.tsx
src/translations/en/profile.json
src/translations/nb/profile.json

noe rart som skjer med BARE/ARP nå, så avventer å merke denne som ferdig PR til de feilene er fikset, og jeg får testet at ting fungerer som det skal. Mangler også å skrive tester, men er avhengig av at BARE/ARP fungerer først.

Np 647  create own authority

---

src/components/SearchBar.tsx
src/pages/publication/ContributorsPanel.tsx
src/pages/publication/DescriptionPanel.tsx
src/pages/publication/FilesAndLicensePanel.tsx
src/pages/publication/PublicationFormTabs.tsx
src/pages/publication/PublicationFormValidationSchema.ts
src/pages/publication/PublishedPublicationList.tsx
src/pages/publication/ReferencesPanel.tsx
src/pages/publication/SubmissionPanel.tsx
src/pages/publication/contributors_tab/components/SortableTable.tsx
src/pages/publication/submission_tab/ErrorSummary.tsx
src/pages/publication/submission_tab/submission_contributors.tsx
src/translations/en/publication.json
src/translations/nb/publication.json
src/types/contributor.types.ts
src/types/publicationFieldNames.ts
src/utils/formik-helpers.ts

Np 656 validate contributors

---

src/App.tsx
src/pages/publication/contributors_tab/components/AddContributorModalContent.tsx
src/pages/user/OrcidModalContent.tsx
src/pages/user/User.tsx
src/pages/user/UserInstitution.tsx
src/pages/user/UserOrcid.tsx
src/pages/user/authority/AuthorityOrcidModal.tsx
src/pages/user/institution/InstitutionCard.tsx
src/pages/user/institution/InstitutionCardList.tsx
src/types/authority.types.ts
src/types/user.types.ts

Første steg med litt renaming og nullable authority

Np 687  dont open modal if author connected

---

src/App.tsx
src/pages/user/authority/AuthorityOrcidModal.tsx
src/utils/constants.ts

This reverts commit e4600e59df6f5d20bb6ac2e573aadf8eb32b9941.
pop up får tester til å feile

Revert "Np 687 avoid opening modal everytime (#435)"

---

package-lock.json
package.json
src/App.tsx
src/pages/publication/contributors_tab/components/AddContributorModalContent.tsx
src/pages/user/OrcidModalContent.tsx
src/pages/user/User.tsx
src/pages/user/UserInstitution.tsx
src/pages/user/UserOrcid.tsx
src/pages/user/authority/AuthorityOrcidModal.tsx
src/pages/user/institution/InstitutionCard.tsx
src/pages/user/institution/InstitutionCardList.tsx
src/translations/en/profile.json
src/translations/nb/profile.json
src/types/authority.types.ts
src/types/user.types.ts
src/utils/constants.ts

var litt tidlig ute med å merge forrige PR, som førte til at tester feilet.
reverta den merge commiten, og git-helvete brøt løs.......
Committen "NP-687 Fix tests" er egentlig det eneste som er nytt fra forrige PR

Np 687 authority modal

---

src/pages/publication/contributors_tab/components/SortableTable.tsx
src/pages/user/authority/AuthorityCard.tsx
src/themes/mainTheme.ts
src/translations/en/publication.json
src/translations/nb/publication.json
src/types/contributor.types.ts

NP-699 Show warning if selected contributor's authority is unauthorized (lacking feide id)

---

src/pages/publication/PublicationFormValidationSchema.ts

førte til krasj hvis man navigerte til references med touched error

Handle error leading to page crash

---

package-lock.json
package.json

Reverts BIBSYSDEV/NVA-Frontend#531

Revert "Bump @uppy/react from 1.6.2 to 1.6.3"

---

src/pages/publication/PublicationForm.tsx
src/pages/publication/PublicationFormValidationSchema.ts
src/pages/publication/submission_tab/submission_description.tsx
src/translations/en/formikValues.json
src/translations/nb/formikValues.json

Subsmission tab sier at publicationSubtype mangler selv om den er valgt

Np 818 validation

---

src/components/Modal.tsx
src/pages/publication/PublicationForm.tsx
src/pages/publication/contributors_tab/AddContributorModal.tsx
src/pages/publication/contributors_tab/components/AddContributorModalContent.tsx
src/pages/user/authority/AuthorityCard.tsx
src/pages/user/authority/AuthorityList.tsx
src/pages/user/authority/AuthorityOrcidModal.tsx
src/pages/user/authority/ConnectAuthority.tsx

Tar en liten runde med styling i neste sak (NP-904)

Np 450 show affiliations in author list

---

src/pages/publication/description_tab/ProjectRow.tsx
src/pages/publication/references_tab/BookForm.tsx
src/pages/publication/references_tab/JournalArticleForm.tsx
src/pages/publication/references_tab/components/NviValidation.tsx
src/pages/publication/references_tab/components/PublisherRow.tsx

Ganske lei alle firkanta hvite bokser, så la inn litt mer bruk av Card som får ting til å se litt bedre ut

Use Card component

---

src/api/publicationApi.ts
src/pages/publication/PublicationForm.tsx
src/pages/publication/new_publication/LoadPublication.tsx
src/types/file.types.ts
src/types/publication.types.ts

lager egen sak for uppy-cleanup

Np 875 start with file

---

src/pages/publication/PublicationForm.tsx
src/types/publication.types.ts
src/utils/hooks/useFetchPublication.ts

hva synes du om dette, @elkebab ?

pull out closeForm prop from useFetchPublicationHook

---

src/pages/publication/SubmissionPanel.tsx
src/pages/publication/public_publication/PublicPublication.tsx
src/pages/publication/references_tab/components/DoiField.tsx
src/utils/constants.ts

...since we get the full address from backend now

remove doi prefix

---

package-lock.json
package.json
src/pages/publication/FilesAndLicensePanel.tsx
src/pages/publication/PublicationFormTabs.tsx

Ser ut som downgraden gjorde mer skade enn nytte, ref krasj på submission tab om man fjerner alle filer :/

NP-1058 Upgrade formik

---

cypress/integration/logout.spec.js
src/App.tsx
src/api/userApi.ts
src/layout/header/Login.tsx
src/redux/actions/authActions.ts
src/redux/actions/userActions.ts
src/redux/reducers/userReducer.ts
src/types/user.types.ts
src/utils/hooks/useFetchAuthorities.ts
src/utils/hub-listener.ts
src/utils/routes/Routes.tsx

Det skjer en del ting her som gjør denne ganske innviklet :/
Ser ingen vei utenom det heller, men user er i hvert fall null i redux nå, og antall api-kall er minmert så mye jeg fikk til
TODO (lager egne saker for disse):
- unngå at login-knapp rendres med "Login" før man får brukernavn etter å ha logget inn
- Disable "Koble til forfatteridentitet" etter trykk

Np 1065 nullable user in redux

---

src/pages/publication/public_publication/PublicPublicationContent.tsx
src/pages/publication/public_publication/PublicPublicationFile.tsx

>The browser tracks whether the current dispatch of the browser's event thread was initiated by a direct user action -- such as entering a command at the console, or clicking on a link. Only when a direction action has been taken can a window or tab be opened.
https://stackoverflow.com/questions/49503119/why-does-chrome-allow-window-open-to-work-when-executed-in-the-console-but-not

Np 1115  unblock file download

---

src/pages/admin/AdminCustomerInstitutionPage.tsx
src/pages/admin/CustomerInstitutionAdminsForm.tsx
src/utils/hooks/useFetchUsersForInstitution.ts

enig i at dette er en bedre løsning?
her henter vi alle brukere på nytt når vi lagrer, heller enn å bare legge til objektet vi jobber med i egen state

NP-1287 Allow refetching institution users

---

src/App.tsx
src/api/apiRequest.ts
src/api/customerInstitutionsApi.ts
src/api/institutionApi.ts
src/utils/axios-config.ts
src/utils/hooks/useFetchCustomerInstitution.ts
src/utils/hooks/useFetchInstitutions.ts

1. utgave av `apiRequest`, med eksempel på bruk både med og uten påkrevd autentisering.
Flytta feilmeldinger fra api-filene til komponentene også.
Gir det mening?

Np 1303 apirequest

---

src/App.tsx
src/layout/header/Login.tsx
src/pages/user/authority/AuthorityModal.tsx
src/pages/user/authority/AuthorityOrcidModal.tsx
src/translations/en/profile.json
src/translations/nb/profile.json
src/utils/hooks/useAuthentication.ts

Gir brukeren lov til å avbryte "koble til forfatteridentitet", og bli logget ut igjen istedet

Np 1292 cancel login

---

src/components/Card.tsx
src/components/Modal.tsx
src/pages/publication/FilesAndLicensePanel.tsx
src/pages/publication/contributors_tab/AddContributorModal.tsx
src/pages/publication/contributors_tab/components/AffiliationsCell.tsx
src/pages/publication/public_publication/PublicPublicationStatusBar.tsx
src/pages/user/UserOrcid.tsx
src/pages/user/authority/AuthorityModal.tsx
src/pages/user/authority/OrcidModal.tsx
src/translations/en/common.json
src/translations/en/publication.json
src/translations/nb/common.json
src/translations/nb/publication.json

Åpner bare modalen. Videre funksjonalitet ligger i andre stories

Np 1347 request doi

---

package-lock.json
package.json

Need to downgrade because of this breaking change: https://github.com/axios/axios/issues/3220

downgrade axios because they removed body from delete request

---

src/pages/publication/FilesAndLicensePanel.tsx

uppy.RemoveFile fungerte ikke pga annen id, så det var lettere å løse det sånn her

remove file from uppy state when removing file

---

src/App.tsx
src/api/userApi.ts
src/layout/header/Login.tsx
src/utils/constants.ts

nå skal man få cristinId og customerId ved første gangs innlogging (fordi vi refresher session i frontend om det mangler)

Np 1578 failed login

---

src/components/RouteLeavingGuard.tsx

ikke kutt search params fra URL i RouteLeavingGuard

NP-1613 Keep search params through route guard

---

src/pages/publication/SubmissionPanel.tsx

Krasjer om man nå åpner en allerede publisert publikasjon, og trykker "Publiser"

NP-1630 Hide publish button for published publications

---

src/translations/en/publicationTypes.json
src/translations/nb/publicationTypes.json
src/types/publicationFieldNames.ts

Det er feil rekkefølge på noen av typene. Tok også en liten sync med typenavn i backend (`ReportOther` -> `ReportBasic`, og `JournalBookReview` -> `JournalReview`)
NB: backend gir bare 400 om vi prøver å lagre "Annen rapport" (ReportBasic) atm

NP-1540 Update order of elements

---

src/pages/publication/PublicationForm.tsx
src/pages/publication/PublicationFormContent.tsx
src/pages/publication/SubmissionPanel.tsx

- Viser alle feilmeldinger når man lagrer
- Håndterer evt feil ved lagring når man skal publisere

Np 1701 validate on save

---

cypress/integration/publication_references_book.spec.js
cypress/integration/publication_references_report.spec.js
cypress/integration/publication_validation.spec.js
src/components/styled/Wrappers.tsx
src/pages/publication/ReferencesPanel.tsx
src/pages/publication/references_tab/BookTypeForm.tsx
src/pages/publication/references_tab/DegreeTypeForm.tsx
src/pages/publication/references_tab/JournalTypeForm.tsx
src/pages/publication/references_tab/ReportTypeForm.tsx
src/pages/publication/references_tab/sub_type_forms/BookForm.tsx
src/pages/publication/references_tab/sub_type_forms/ChapterForm.tsx
src/pages/publication/references_tab/sub_type_forms/DegreeForm.tsx
src/pages/publication/references_tab/sub_type_forms/JournalArticleForm.tsx
src/pages/publication/references_tab/sub_type_forms/JournalForm.tsx
src/pages/publication/references_tab/sub_type_forms/ReportForm.tsx

Forberedt muligheten til å vise forskjellige skjema basert på subtyper istedenfor hovedtyper. Det kommer mange flere hoved- og subtyper etterhvert

Np 1702  show reference form based on subtypes

---

src/pages/registration/RegistrationForm.tsx
src/pages/registration/SubmissionPanel.tsx

Skal ikke være noen "Lagre"-knapp på submission, men "Publiser" og "Lagre og presenter". dette gjelder både Creator og Curator. la inn right-align i samme slengen

Np 1788 save buttons

---

src/App.tsx
src/components/SearchBar.tsx
src/pages/dashboard/Dashboard.tsx
src/pages/dashboard/RegistrationListItem.tsx
src/translations/en/common.json
src/translations/nb/common.json

Avhenger av https://github.com/BIBSYSDEV/NVA-Frontend/pull/1196

Np 1821 truncate info

---

src/components/LabelContentRow.tsx
src/pages/public_registration/PublicRegistrationContent.tsx

Unngå feil for offentlig visning av registrering med både sammendrag og beskrivelse

Avoid missing newline

---

src/pages/registration/ReferencesPanel.tsx
src/types/publication_types/journalRegistration.types.ts
src/utils/testfiles/mockRegistration.ts
src/utils/validation/registration/referenceValidation.ts

Unngå tidligere bug hvor det ikke var mulig å lagre med sidetall, pga feil `type` i modellen mot backend

Np 1959 page type

---

cypress/integration/admin_institution.spec.js
cypress/integration/registration_references_report.spec.js
cypress/integration/registration_validation.spec.js
cypress/integration/snackbar.spec.js
src/layout/Notifier.tsx

datatest-id vil nå bli "snackbar-success", "snackbar-error", etc

Add status to snackbar testid

---

package-lock.json
src/api/doiRequestApi.ts
src/pages/public_registration/PublicRegistrationContent.tsx
src/pages/public_registration/PublicRegistrationStatusBar.tsx
src/pages/registration/RegistrationFormActions.tsx
src/pages/registration/SubmissionPanel.tsx
src/pages/registration/references_tab/components/DoiField.tsx
src/translations/en/feedback.json
src/translations/nb/feedback.json
src/types/registration.types.ts

Approve eller Reject DoiRequest.
Støtter også (opp til) 2 DOIer i datamodell. en utstedt av NVA, og en annen (registrert med allerede eksisterende DOI)

Np 514 doi response

---

src/pages/public_registration/PublicRegistrationContent.tsx
src/pages/registration/DescriptionPanel.tsx
src/pages/registration/description_tab/projects_field/ProjectsField.tsx
src/pages/registration/submission_tab/submission_description.tsx
src/types/publicationFieldNames.ts
src/types/registration.types.ts
src/utils/testfiles/mockRegistration.ts

Fremtidig fiks:
- Bli kvitt uncontrolled -> uncontrolled warning

Np 1737 multiple projects

---

src/layout/header/Menu.tsx

endelig kan man åpne menu items i dropdown i ny fane med å trykke på musehjulet <3

Use link in menu

---

src/api/registrationApi.ts
src/pages/registration/EditRegistration.tsx
src/pages/registration/RegistrationForm.tsx
src/pages/registration/new_registration/LinkRegistration.tsx
src/pages/registration/new_registration/UploadRegistration.tsx
src/utils/hooks/useFetchRegistration.ts

Hvis man var i Wizard skjedde det ingenting om man trykket på "Ny registrering"

Np 2026 start new registration from wizard

---

src/pages/public_profile/PublicProfile.tsx
src/pages/public_registration/PublicPublicationInstance.tsx
src/pages/registration/references_tab/components/SearchContainerField.tsx
src/pages/search/RegistrationSearch.tsx
src/types/publicationFieldNames.ts
src/utils/hooks/useSearchRegistrations.ts
src/utils/searchHelpers.ts

Fullfør https://github.com/BIBSYSDEV/NVA-Frontend/pull/1359 før denne evt tas inn
`useSearchRegistrations` tar inn et søkeobjekt i stedet for en enkel søkestreng

Np 2020 move search query

---

src/components/ConfirmDialog.tsx
src/components/MessageForm.tsx
src/components/institution/EditInstitution.tsx
src/layout/header/Header.tsx
src/layout/header/Menu.tsx
src/pages/admin/CustomerInstitutionAdminsForm.tsx
src/pages/admin/CustomerInstitutionMetadataForm.tsx
src/pages/admin/InstitutionList.tsx
src/pages/admin/MyInstitutionPage.tsx
src/pages/admin/MyInstitutionUsersPage.tsx
src/pages/admin/UserList.tsx
src/pages/public_registration/PublicRegistrationStatusBar.tsx
src/pages/registration/RegistrationFormActions.tsx
src/pages/registration/contributors_tab/Authors.tsx
src/pages/registration/contributors_tab/components/AffiliationsCell.tsx
src/pages/registration/contributors_tab/components/AuthorCard.tsx
src/pages/user/UserInstitution.tsx
src/pages/worklist/DoiRequestAccordion.tsx
src/themes/mainTheme.ts
src/translations/en/workLists.json
src/translations/nb/workLists.json

Fjerner feilaktig endring av knappefont i theme og legger tid knappeikoner rundt omkring
Skjønner ikke helt hvordan `font-weight` virker/skal virke. Den er definert til `500` for knapper i theme (som er riktig), men i praksis endres bare utseende når weight passerer `600`, og støtter tilsynelatende bare bold (>=600) og ikke bold (<600) 😕 
EDIT: mistenker at fontene vi har importert ikke er helt fullstendige, i så fall dekkes det i egen task for fonter

Np 2062 button font

---

src/translations/en/registration.json
src/translations/nb/registration.json

NP-2070 Update description for starting with file

---

public/index.html
src/themes/mainTheme.ts

NP-2075 Use Crimson font instead of Merriweather

---

cypress/integration/registration_validation.spec.js
src/pages/registration/contributors_tab/AddContributorModal.tsx
src/pages/registration/contributors_tab/components/AddContributorModalContent.tsx
src/pages/registration/contributors_tab/components/CreateContributorModalContent.tsx
src/pages/user/authority/AuthorityList.tsx
src/translations/en/common.json
src/translations/nb/common.json

Np 2037 author modal search

---

src/pages/registration/contributors_tab/AddContributorModal.tsx
src/pages/registration/contributors_tab/components/AddContributorModalContent.tsx
src/translations/en/registration.json
src/translations/nb/registration.json

Endre tekst i lagre-knapp og header

NP-2078 Update texts

---

src/layout/Footer.tsx
src/pages/infopages/PrivacyPolicy.tsx
src/translations/en/infopages.json
src/translations/en/privacy.json
src/translations/i18n.ts
src/translations/nb/common.json
src/translations/nb/infopages.json
src/translations/nb/privacy.json

Norsk versjon er ferdig. Tror vi godt kan nøye oss med det foreløpig, så får POs sjekke at norsk versjon er slik den skal være før vi oversetter til engelsk

NP-2076 Add privacy statement

---

src/components/PageHeader.tsx

Unngå at siden utvider seg ut av skjermen for lang PageHeader på små skjermer

NP-2086 Handle wide page header

---

src/pages/infopages/About.tsx
src/translations/en/about.json
src/translations/nb/about.json
src/utils/constants.ts

Hege skal snakke med Kine om hvordan tekstene skal være på skisser for ny startside

Update about NVA

---

src/pages/infopages/About.tsx
src/translations/en/about.json
src/translations/nb/about.json

PO syns det var litt overkill med en ekstra heading

Remove Description heading

---

src/api/registrationApi.ts
src/utils/hooks/useFetchMyRegistrations.ts

Oppdaget evig lasting i prod (hver jeg ikke har noen registreringer)

NP-2105 Handle empty my registrations

---

src/api/institutionApi.ts
src/pages/public_registration/PublicRegistrationAuthors.tsx
src/pages/registration/contributors_tab/components/AffiliationsCell.tsx
src/types/contributor.types.ts
src/utils/institutions-helpers.ts

Vis "forslag" for affiliation fra DOI (skal ikke vises på Landing Page)
"Verifiser tilknytning" kommer i neste sak

Np 2094 doi affiliation

---

src/pages/public_registration/PublicRegistrationContent.tsx
src/pages/public_registration/PublicSummaryContent.tsx
src/themes/darkTheme.ts

Styling av boks for Sammendrag og Nøkkelord.
Selve summary box skal være responsiv, men det går i ball siden de andre boksene ikke er det enda.

Np 2031 summary box

---

src/pages/public_registration/PublicProjectsContent.tsx
src/pages/public_registration/PublicRegistrationContent.tsx
src/translations/en/registration.json
src/translations/nb/registration.json

Prosjekter virker egentlig ikke i dag. Vi mister mye data når vi lagrer, og ting henger generelt ikke helt sammen. 
Har tatt det opp med Rurik og Terje, så tror vi kan se på dette som en placeholder enn så lenge.

Np 2031 projects box

---

src/pages/dashboard/RegistrationListItem.tsx
src/pages/registration/references_tab/components/SearchContainerField.tsx
src/utils/date-helpers.ts

Abstract vises ikke for søketreff atm

New truncate package must have text via prop, not children

---

src/pages/registration/ContributorsPanel.tsx
src/pages/registration/FilesAndLicensePanel.tsx
src/pages/registration/contributors_tab/Authors.tsx

Sjekk at FieldArray er touched før feilmelding vises

Np 2088 file error message

---

src/pages/dashboard/RegistrationListItem.tsx
src/pages/registration/references_tab/components/SearchContainerField.tsx

Avoid <div> inside <p>

---

src/pages/public_registration/PublicRegistrationAuthors.tsx
src/pages/registration/contributors_tab/components/AffiliationsCell.tsx
src/types/contributor.types.ts
src/utils/formik-helpers.ts
src/utils/institutions-helpers.ts

Nå krasjer det om man prøver å legge til affiliation for en contributor som ikke har undefined affiliations (kan skje fra DOI-oppslag)

NP-2163 Allow undefined affiliations

---

package-lock.json
src/pages/public_registration/PublicFilesContent.tsx

Vis filer i egen div i stedet for å rote mer med Table.
Utkommentert kode ble brukt for å fikse layout for både mobil og desktop nå, og vil brukes i neste PR

Np 2164 refactor file list

---

src/pages/public_registration/PublicFilesContent.tsx

Last ned filer mindre enn 10MB uten at bruker må gjøre noe

Np 2165 auto download small files

---

src/pages/public_registration/preview_file/PreviewFile.tsx
src/pages/public_registration/preview_file/PreviewOfficeFile.tsx

Forhåndsvis MS Office-filer
Eks: http://localhost:3000/registration/c6ca8973-d90e-47b1-95ee-5b2bb4094ab5/public

Np 2166 office file preview

---

src/themes/lightTheme.ts

NP-2226 Add more space to autocomplete chips

---

cypress/integration/user.spec.js
src/pages/user/MyProfilePage.tsx
src/translations/en/profile.json
src/translations/nb/profile.json

Skal ikke vises på min profil. hvis man ikke har forfatteridentitet blir man jo logget ut, så det gir ikke mening å vise det slik det er nå

Np 2232 remove autor identity box

---

src/pages/registration/description_tab/projects_field/helpers.ts
src/types/project.types.ts

Håndterer at `fundings` kan være undefined. kan diskutere om den burde trengs, men skader ikke å ta den inn heller
(burde i så fall bli med på utrulling som kommer nå)
https://unit-norge.slack.com/archives/CN005AQCE/p1614607885011400

Handle undefined fundings for projects

---

src/pages/public_registration/PublicRegistrationStatusBar.tsx

Unngå sånn:
Eks: https://frontend.dev.nva.aws.unit.no/registration/7d14209c-5259-46c0-94e0-d54bcf48caaa/public

Np 2283 landing page validation

---

src/components/PageHeader.tsx
src/pages/dashboard/RegistrationListItem.tsx
src/pages/registration/resource_type_tab/components/SearchContainerField.tsx

Np 2379 truncated text

---

src/pages/registration/resource_type_tab/components/DoiField.tsx
src/pages/registration/resource_type_tab/sub_type_forms/BookForm.tsx
src/pages/registration/resource_type_tab/sub_type_forms/ChapterForm.tsx
src/pages/registration/resource_type_tab/sub_type_forms/DegreeForm.tsx
src/pages/registration/resource_type_tab/sub_type_forms/JournalForm.tsx
src/pages/registration/resource_type_tab/sub_type_forms/ReportForm.tsx
src/translations/en/registration.json
src/translations/nb/registration.json

Flytt fjerning av DOI til egen knapp utenfor (disabled) TextField

Np 2395 remove doi

---

src/pages/registration/resource_type_tab/components/SelectTypeField.tsx
src/themes/darkTheme.ts

Np 2395 field focus

---

src/pages/registration/files_and_license_tab/FileCard.tsx
src/translations/en/common.json
src/translations/en/registration.json
src/translations/nb/common.json
src/translations/nb/registration.json

La til ConfirmDialog ved fjerning av fil i samme slengen

Np 2395 files labels

---

src/utils/formik-helpers.ts
src/utils/validation/registration/referenceValidation.ts

Fiks opp i feilmeldinger som ble vist når de ikke var relevant, og motsatt

Np 2460 validate corrigendum

---

src/App.tsx

Forrige løsning førte til evig loading om brukeren ikke var logget inn 🙃

Update loading state

---

src/pages/registration/contributors_tab/AddContributorModal.tsx
src/pages/registration/contributors_tab/components/AddContributorModalContent.tsx
src/pages/user/authority/AuthorityList.tsx

EDIT: Siste versjon:
https://user-images.githubusercontent.com/6595982/115547521-a2879f00-a2a6-11eb-8b41-36b747ea3a26.mov

add fixed height for add contributor modal

---

src/pages/registration/contributors_tab/components/ContributorList.tsx

Note to self: det er viktig at `key` er unik. denne bøggen var pga 2 ikke-verifiserte forfattere med samme navn

NP-2551 Fix contributor paging bug

---

src/pages/public_registration/PublicRegistrationStatusBar.tsx

NP-2603 Don't escape date

---

src/components/IconLabelTextLine.tsx
src/pages/user/UserRoles.tsx

Caused by: https://github.com/BIBSYSDEV/NVA-Frontend/pull/1729#discussion_r625175077
Før:
Etter:

Np 2601 role icons

---

src/components/RouteLeavingGuard.tsx
src/pages/registration/RegistrationForm.tsx

fjern `window.onbeforeunload = () => true;` når man går fra Wizard til Landing Page

Np 2592 landing page warning

---

src/api/projectApi.ts

Update project search query

---

src/components/institution/AffiliationHierarchy.tsx
src/pages/user/institution/InstitutionCard.tsx

Unngå duplicated key hvis to underenheter har samme navn

Affiliation fixes

---

src/resources/vocabularies/hrcsActivities.ts
src/resources/vocabularies/hrcsCategories.ts

Update hrcs data

---

src/pages/registration/description_tab/projects_field/ProjectsField.tsx
src/pages/registration/resource_type_tab/components/PublicationChannelSearch.tsx
src/pages/registration/resource_type_tab/components/SearchContainerField.tsx

Unngå at Autocomplete filtrerer bort elementer som returneres fra søk hvis bruker søker på en id el.l.

NP-2709 Don't filter options when showing search results

---

src/types/publication_types/bookRegistration.types.ts
src/types/publication_types/chapterRegistration.types.ts
src/types/publication_types/degreeRegistration.types.ts
src/types/publication_types/journalRegistration.types.ts
src/types/publication_types/reportRegistration.types.ts
src/types/registration.types.ts
src/utils/testfiles/mockRegistration.ts

Legg til `controlledKeywords`, samt unngå en del kodeduplisering

Np 2717 refactor types

---

src/pages/registration/resource_type_tab/components/TotalPagesField.tsx
src/pages/registration/resource_type_tab/sub_type_forms/BookForm.tsx
src/pages/registration/resource_type_tab/sub_type_forms/DegreeForm.tsx
src/pages/registration/resource_type_tab/sub_type_forms/ReportForm.tsx
src/utils/dataTestIds.ts

Legg til input for antall sider for Degree.

Np 2779 pages for degree

---

src/components/AutocompleteTextField.tsx
src/components/ButtonWithProgress.tsx
src/components/Card.tsx
src/components/DelayedFallback.tsx
src/components/EmphasizeSubstring.tsx
src/components/Heading.tsx
src/components/LabelTextLine.tsx
src/components/ListSkeleton.tsx
src/components/NormalText.tsx
src/components/SearchBar.tsx
src/components/TabButton.tsx
src/components/institution/AffiliationSkeleton.tsx
src/components/institution/EditInstitution.tsx
src/layout/Logout.tsx
src/layout/Notifier.tsx
src/pages/dashboard/RegistrationListItem.tsx
src/pages/errorpages/Forbidden.tsx
src/pages/errorpages/NotFound.tsx
src/pages/errorpages/NotPublished.tsx
src/pages/registration/files_and_license_tab/FileUploader.tsx
src/pages/registration/new_registration/EditRegistration.tsx
src/pages/registration/resource_type_tab/components/JournalField.tsx
src/pages/registration/resource_type_tab/components/PublicationChannelSearch.tsx
src/pages/registration/resource_type_tab/components/PublisherField.tsx
src/pages/user/institution/InstitutionSelector.tsx
src/utils/routes/PrivateRoute.tsx
src/utils/routes/Routes.tsx

NP-2876 Remove React.FC

---

cypress/integration/registration.spec.js
src/AppRoutes.tsx

Vis NotFound også om man er logget inn

Np 2876 not found bug

---

src/App.tsx
src/api/roleApi.ts
src/pages/admin/UserList.tsx
src/types/user.types.ts
src/utils/testfiles/mock_feide_user.ts

Oppdater fetching av roller. kan forenkles ytterligere ved å sette roller fra innlogging også

Np 2876 refactor role api

---

cypress/integration/registration_validation.spec.js
package-lock.json
src/pages/public_registration/PublicGeneralContent.tsx
src/pages/public_registration/PublicPublicationInstance.tsx
src/pages/registration/resource_type_tab/components/ContentTypeField.tsx
src/pages/registration/resource_type_tab/sub_type_forms/JournalForm.tsx
src/themes/darkTheme.ts
src/translations/en/registration.json
src/translations/nb/registration.json
src/types/publicationFieldNames.ts
src/types/publication_types/journalRegistration.types.ts
src/utils/dataTestIds.ts
src/utils/formik-helpers.ts
src/utils/testfiles/mockRegistration.ts
src/utils/validation/registration/referenceValidation.ts

Legg til dropdown for Innholdstype for JournalArticle

Np 2689 journal article content type

---

src/pages/registration/RegistrationForm.tsx
src/pages/registration/ResourceTypePanel.tsx
src/pages/registration/description_tab/DatePickerField.tsx
src/pages/registration/resource_type_tab/components/nvi_fields/ContentTypeField.tsx

Fjern noen tilfeller hvor feilmelding ble hengende igjen selv om man hadde satt en verdi.

Np 2961 Fix (some) validation bugs

---

cypress/integration/registration.spec.js
cypress/integration/registration_files.spec.js
cypress/integration/registration_validation.spec.js
cypress/support/commands.js
package-lock.json
src/api/mock-interceptor.ts

Erstatt deprecated `cy.route()` med `cy.intercept()`

Cypress intercept

---

src/pages/registration/files_and_license_tab/FileCard.tsx

Fikk warning når man satte versjon for nylig opplastet fil

Uncontrolled input warning

---

src/pages/registration/resource_type_tab/components/SeriesFields.tsx
src/types/publication_types/bookRegistration.types.ts
src/types/publication_types/chapterRegistration.types.ts
src/types/publication_types/journalRegistration.types.ts
src/types/publication_types/reportRegistration.types.ts

Lagring virker ikke med tom streng som level

Use null instead of empty string

---

package-lock.json
package.json
src/pages/public_registration/PublicRegistrationContent.tsx
src/pages/public_registration/ShareOptions.tsx

Vis dele-knapper for brukere som har aktivert beta-flagg

NP-2980 Add share buttons to landing page

---

src/components/RegistrationList.tsx
src/pages/my_registrations/MyRegistrationList.tsx
src/pages/my_registrations/MyRegistrations.tsx
src/pages/my_registrations/MyRegistrationsList.tsx
src/pages/public_registration/PublicRegistrationContent.tsx
src/pages/search/SearchResults.tsx
src/translations/en/registration.json
src/translations/nb/registration.json
src/types/language.types.ts
src/utils/dataTestIds.ts

Link til andre relaterte registreringer

Np 2991 link to chapter

---

src/layout/Logout.tsx
src/pages/dashboard/Dashboard.tsx
src/translations/en/authorization.json
src/translations/nb/authorization.json
src/utils/constants.ts
src/utils/hooks/useAuthentication.ts

Åpne forrige side etter innlogging.
Forbli på public pages, evt gå til forsiden ved utlogging.

Np 3011 authentication paths

---

src/pages/dashboard/Dashboard.tsx
src/translations/en/common.json
src/translations/nb/common.json

Np 3010 dashboard banner

---

src/pages/registration/resource_type_tab/components/nvi_fields/ContentTypeField.tsx
src/pages/registration/resource_type_tab/components/nvi_fields/NviFields.tsx
src/pages/registration/resource_type_tab/sub_type_forms/BookForm.tsx
src/pages/registration/resource_type_tab/sub_type_forms/ChapterForm.tsx
src/pages/registration/resource_type_tab/sub_type_forms/JournalForm.tsx
src/translations/nb/registration.json
src/types/publication_types/content.types.ts

Sikrer at innholdstyper alltid blir oversatt

Np 3026 content translation

---

src/components/SearchBar.tsx

Legg til knapp for å nulltille søk

Np 3027 reset search

---

cypress/integration/registration_resource_book.spec.js
cypress/integration/registration_resource_report.spec.js
src/pages/public_registration/PublicGeneralContent.tsx
src/pages/public_registration/PublicPublicationContext.tsx
src/pages/registration/resource_type_tab/components/SeriesFields.tsx
src/pages/registration/resource_type_tab/components/SeriesSearch.tsx
src/translations/en/common.json
src/translations/en/feedback.json
src/translations/en/registration.json
src/translations/nb/common.json
src/translations/nb/feedback.json
src/translations/nb/registration.json
src/types/publication_types/degreeRegistration.types.ts
src/types/publication_types/reportRegistration.types.ts

Oppdater visning av serie for både wizard og landing page

Np 3028 series on landing page

---

cypress/integration/registration_resource_chapter.spec.js
cypress/integration/search.spec.js
src/components/SearchBar.tsx
src/pages/registration/resource_type_tab/sub_type_forms/ChapterForm.tsx
src/pages/search/RegistrationSearch.tsx
src/themes/lightTheme.ts
src/types/publicationFieldNames.ts
src/utils/dataTestIds.ts
src/utils/npiDisciplines.ts
src/utils/validation/registration/registrationValidation.ts

Diverse opprydding av gamle saker

Add skipped tests and remove some old TODOs

---

src/pages/public_registration/PublicRegistrationContent.tsx
src/pages/public_registration/PublicSummaryContent.tsx
src/pages/registration/description_tab/vocabularies/HrcsActivityInput.tsx
src/pages/registration/description_tab/vocabularies/VocabularyFields.tsx
src/utils/constants.ts

Avhenger av https://github.com/BIBSYSDEV/NVA-Frontend/pull/2044

Np 2724 show vocabularies on landing page

---

src/api/mock-interceptor.ts
src/pages/public_registration/PublicPublicationContext.tsx
src/pages/registration/resource_type_tab/components/SeriesField.tsx
src/types/publicationFieldNames.ts
src/types/publication_types/bookRegistration.types.ts
src/types/publication_types/chapterRegistration.types.ts
src/types/publication_types/degreeRegistration.types.ts
src/types/publication_types/reportRegistration.types.ts

Np 3101 series model

---

cypress/integration/registration_resource_book.spec.js
cypress/integration/registration_resource_report.spec.js
src/pages/registration/resource_type_tab/components/SeriesField.tsx
src/translations/en/registration.json
src/translations/nb/registration.json
src/utils/dataTestIds.ts
src/utils/registration-helpers.ts

Np 3125 series chip

---

cypress/integration/registration_resource_book.spec.js
cypress/integration/registration_resource_report.spec.js
src/pages/registration/resource_type_tab/components/JournalField.tsx
src/pages/registration/resource_type_tab/components/PublisherField.tsx
src/translations/en/feedback.json
src/translations/nb/feedback.json
src/utils/dataTestIds.ts

Np 3125 publisher chip

---

src/pages/registration/resource_type_tab/components/SearchContainerField.tsx
src/types/search.types.ts
src/utils/validation/registration/referenceValidation.ts

Chip for conteinar input (corrigendum og chapter)

Np 3125 container chip

---

src/pages/public_registration/PublicRegistrationStatusBar.tsx

Unngå at hele appen må lastes på nytt igjen

NP-3173 Use link instead of href

---

src/components/LabelTextLine.tsx
src/pages/public_profile/PublicProfile.tsx
src/pages/public_registration/PublicProjectsContent.tsx
src/pages/public_registration/PublicRegistrationContributors.tsx
src/pages/public_registration/RegistrationSummary.tsx
src/pages/registration/SupportModalContent.tsx

Unngå at hel siden lastes på nytt flere plasser

Np 3173 link instead of anchor

---

src/pages/registration/ResourceTypePanel.tsx
src/translations/en/registration.json
src/translations/nb/registration.json

Type -> Form
(Siden dette feltet ikke representeres i datamodell vil det fortsatt stå Type ifbm validering)

Np 3199 rename type field

---

src/pages/registration/resource_type_tab/components/JournalField.tsx
src/pages/registration/resource_type_tab/components/PublisherField.tsx

Velg tidsskrift om det finnes en med riktig issn (fra DOI)
Velg utgiver om det finnes en med identisk navn

Np 3127 select journal

---

src/pages/public_registration/PublicPublicationContext.tsx

Vis level for publisher på landing page

Np 3209 publisher level landing page

---

src/components/RegistrationList.tsx
src/pages/public_registration/PublicDoi.tsx
src/pages/public_registration/PublicGeneralContent.tsx
src/pages/public_registration/PublicRegistrationContent.tsx
src/pages/public_registration/PublicRegistrationStatusBar.tsx
src/pages/registration/ContributorsPanel.tsx
src/pages/registration/RegistrationForm.tsx
src/pages/registration/ResourceTypePanel.tsx
src/pages/registration/resource_type_tab/BookTypeForm.tsx
src/pages/registration/resource_type_tab/ChapterTypeForm.tsx
src/pages/registration/resource_type_tab/DegreeTypeForm.tsx
src/pages/registration/resource_type_tab/JournalTypeForm.tsx
src/pages/registration/resource_type_tab/ReportTypeForm.tsx
src/pages/registration/resource_type_tab/components/DoiField.tsx
src/pages/registration/resource_type_tab/components/JournalField.tsx
src/pages/registration/resource_type_tab/components/NviValidation.tsx
src/pages/registration/resource_type_tab/components/PublisherField.tsx
src/pages/registration/resource_type_tab/components/SeriesField.tsx
src/pages/registration/resource_type_tab/components/nvi_fields/NviFields.tsx
src/pages/registration/resource_type_tab/sub_type_forms/BookForm.tsx
src/pages/registration/resource_type_tab/sub_type_forms/ChapterForm.tsx
src/pages/registration/resource_type_tab/sub_type_forms/JournalForm.tsx
src/types/publicationFieldNames.ts
src/types/publication_types/bookRegistration.types.ts
src/types/publication_types/chapterRegistration.types.ts
src/types/publication_types/degreeRegistration.types.ts
src/types/publication_types/journalRegistration.types.ts
src/types/publication_types/reportRegistration.types.ts
src/utils/formik-helpers.ts
src/utils/validation/registration/referenceValidation.ts

Legg til at reference kan være null

NP-3294 Nullable reference

---

src/types/publicationFieldNames.ts

Oppdater søket for å finne registreringer som skal vises på brukerens offentlige profil

Show registrations on user's public profile

---

src/pages/public_registration/PublicGeneralContent.tsx
src/pages/public_registration/PublicPublicationContext.tsx
src/pages/public_registration/PublicPublicationInstance.tsx

Vis bare tidsskrift, utgiver, og serie i høyre bolk. Resten i venstre.

Np 3310 restructure landing page

---

src/pages/registration/contributors_tab/components/ContributorCard.tsx
src/pages/registration/resource_type_tab/sub_type_forms/artistic_types/design/ArtisticDesignForm.tsx
src/pages/registration/resource_type_tab/sub_type_forms/artistic_types/design/VenueModal.tsx
src/pages/registration/resource_type_tab/sub_type_forms/artistic_types/design/VenueRow.tsx
src/translations/en/common.json
src/translations/en/registration.json
src/translations/nb/common.json
src/translations/nb/registration.json

Np 3385 change order of exhibition place

---

src/pages/projects/ProjectGeneralInfo.tsx
src/pages/public_registration/PublicProjectsContent.tsx
src/pages/registration/description_tab/projects_field/ProjectChip.tsx
src/pages/registration/description_tab/projects_field/ProjectsField.tsx
src/pages/registration/description_tab/projects_field/projectHelpers.ts
src/redux/actions/resourcesActions.ts
src/types/publication_types/presentationRegistration.types.ts
src/utils/hooks/useFetchResource.ts

Unngå å endre prosjekttype frem og tilbake (`CristinProject` <-> `ResearchProject`)

Np 3386 simplify project mapping

---

src/pages/public_registration/PublicRegistrationContent.tsx
src/pages/registration/RegistrationForm.tsx
src/utils/formik-helpers.ts
src/utils/registration-helpers.ts

Pass på at `type` settes riktig før man sender data til backend

Np 3403 save empty registration

---

src/pages/public_registration/PublicRegistrationContributors.tsx
src/utils/registration-helpers.ts

Vis alle contributors med "main" roles (roller som er obligatorisk) for hver type. 
Vis navn på rolle der det kan være flere

Np 3409 public contributors

---

src/pages/search/filters/RegistrationTypeFilter.tsx

Ikke overskriv første filter hver gang man velger ny type. Prøv først å oppdater tilsvarende, og legg til nytt hvis det ikke finnes enda

Np 3411 avoid filter overwrite

---

cypress/integration/search.spec.js
src/pages/search/RegistrationSearch.tsx
src/pages/search/SearchPage.tsx
src/pages/search/SortSelector.tsx
src/utils/searchHelpers.ts

Gå rett til side 1 når man har oppdatert/endret søket

Np 3421 reset search paging

---

src/pages/public_registration/PublicSummaryContent.tsx
src/pages/registration/description_tab/projects_field/ProjectChip.tsx
src/pages/registration/resource_type_tab/components/JournalField.tsx
src/pages/registration/resource_type_tab/components/PublisherField.tsx
src/pages/registration/resource_type_tab/components/SearchContainerField.tsx
src/pages/registration/resource_type_tab/components/SeriesField.tsx
src/themes/lightTheme.ts
src/types/publicationFieldNames.ts

Tillat å fjerne foreslåtte treff når issn/navn bare gir ett treff.
Tillat å fjerne foreslåtte navn også.

Np 3422 remove default journal/publisher/series

---

src/pages/search/SearchBar.tsx
src/pages/search/SearchPage.tsx
src/pages/search/filters/AdvancedSearchRow.tsx

Vis avansert søk også uten beta=true
Oppdater visning for mobil

Np 3435 advanced search for all users

---

src/utils/validation/registration/referenceValidation.ts

Unngå krasj for serie-validering om serie er null

NP-3464 Fix series validation

---

src/pages/public_registration/PublicPublicationInstance.tsx

NP-3464 Avoid undefined type work on landing page

---

src/components/institution/InstitutionAutocomplete.tsx

Unngå dette:
(Permanent backend-fiks i NP-3465)

Np 3464 unique institutions

---

src/pages/registration/RegistrationForm.tsx
src/pages/registration/RegistrationFormStepper.tsx
src/pages/registration/RegistrationFormTabs.tsx
src/themes/mainTheme.ts
src/utils/validation/customerInstitutionValidation.ts

Fjern kraftig bakgrunn for feilmeldinger

Np 3440 remove error message backgrounds

---

src/api/fileApi.ts
src/pages/public_registration/PublicFilesContent.tsx

Bruk `id` i stedet for `presignedDownloadUrl`

Update download file response

---

cypress/integration/search.spec.js
src/themes/mainTheme.ts
src/translations/en/common.json
src/translations/nb/common.json

Siste versjon av MUI fikk støtte for norsk bokmål

Set locale in MUI theme

---

src/translations/en/about.json
src/translations/en/privacy.json
src/translations/en/profile.json
src/translations/nb/about.json
src/translations/nb/privacy.json
src/translations/nb/profile.json

Rename to Sikt

---

src/App.tsx
src/components/institution/SelectInstitutionForm.tsx
src/pages/admin/customerInstitutionFields/SelectInstitutionField.tsx

~Vent på denne: https://github.com/BIBSYSDEV/nva-cristin-service/pull/115~

NP-3495 Remove frontend filter for finding only top level institutions

---

src/App.tsx
src/api/userApi.ts
src/translations/en/authorization.json
src/translations/nb/authorization.json
src/utils/constants.ts

Send til `/` og vis infoboks om utløpt sesjon

NP-3529 Handle expired token

---

src/App.tsx
src/api/userApi.ts
src/components/BetaFunctionality.tsx
src/components/ErrorBoundary.tsx
src/layout/Logout.tsx
src/layout/header/Login.tsx
src/pages/dashboard/Dashboard.tsx
src/utils/constants.ts
src/utils/hooks/useAuthentication.ts

Samler alle localStarage keys i en enum

Move localstorage keys to enum

---

src/App.tsx
src/layout/Notifier.tsx
src/pages/admin/CustomerInstitutionMetadataForm.tsx
src/pages/admin/MyInstitutionPage.tsx
src/pages/admin/UserList.tsx
src/pages/admin/ViewingScopeCell.tsx
src/pages/editor/VocabularySettings.tsx
src/pages/my_registrations/MyRegistrationsList.tsx
src/pages/public_registration/PublicFilesContent.tsx
src/pages/public_registration/PublicRegistrationStatusBar.tsx
src/pages/registration/FilesAndLicensePanel.tsx
src/pages/registration/RegistrationFormActions.tsx
src/pages/registration/contributors_tab/Contributors.tsx
src/pages/registration/contributors_tab/components/AffiliationsCell.tsx
src/pages/registration/contributors_tab/components/CreateContributorModalContent.tsx
src/pages/registration/new_registration/LinkRegistration.tsx
src/pages/registration/new_registration/StartEmptyRegistration.tsx
src/pages/registration/new_registration/UploadRegistration.tsx
src/pages/user/UserAffiliations.tsx
src/pages/user/UserOrcid.tsx
src/pages/user/authority/ConnectAuthority.tsx
src/pages/user/authority/NewAuthorityCard.tsx
src/pages/user/institution/InstitutionCard.tsx
src/pages/worklist/SupportRequestAccordion.tsx
src/redux/actions/notificationActions.ts
src/types/notification.types.ts
src/utils/constants.ts
src/utils/hooks/useFetch.ts

Oppgi string  i stedet for egen enum-verdi

Refactor snackbar types

---

src/api/fileApi.ts
src/pages/public_registration/PublicFilesContent.tsx

Ikke krev token for å laste ned filer på Landing Page. Filer under embargo skal aldri vises her uanZ

Np 3561 landing page without auth

---

package-lock.json
package.json
src/components/RouteLeavingGuard.tsx

Fjern utdaterte @types/history

Np 3561 Refactor route leave guard

---

src/api/fileApi.ts
src/pages/public_registration/PublicFilesContent.tsx

La Creator/Curator som ser landing page for ikke-publisert Registrering se filer

Np 3615 file download bug

---

src/pages/registration/resource_type_tab/components/isbn_and_pages/IsbnField.tsx

Formatet vil variere litt basert på hva slags ISBN det er:  https://www.nb.no/standardnummerering/isbn/
Legger ikke inn ekstra logikk for å håndtere dette nå, men bruker bare 000-00-000-0000-0

NP-3601 Update isbn format

---

src/App.tsx
src/pages/admin/ViewingScopeCell.tsx
src/pages/worklist/WorklistPage.tsx
src/redux/actions/userActions.ts
src/redux/reducers/userReducer.ts
src/translations/en/workLists.json
src/translations/nb/workLists.json
src/types/user.types.ts

Np 4224 show user scope

---

src/pages/my_registrations/MyRegistrationsList.tsx

Oppdater formatering når bruker bytter side eller endrer antall treff på siden

Run mathjax when changing page

---

cypress/integration/registration_validation.spec.js
src/pages/registration/resource_type_tab/components/NviValidation.tsx
src/translations/en/registration.json
src/translations/nb/registration.json
src/types/publication_types/content.types.ts
src/utils/testfiles/mockRegistration.ts

Research article -> Academic article

NP-4701 Rename content type academic article

---

src/components/EmphasizeSubstring.tsx
src/pages/registration/resource_type_tab/components/SearchContainerField.tsx

Typeset MathJax for container search

---

src/components/AutocompleteTextField.tsx
src/pages/admin/customerInstitutionFields/OrganizationSearchField.tsx
src/pages/registration/description_tab/projects_field/ProjectContributorRow.tsx
src/utils/institutions-helpers.ts

Vis valgte brukers affiliations som forslag by default

NP-3585 Prefill institution options

---

src/pages/public_registration/PublicPublicationContext.tsx
src/pages/registration/resource_type_tab/sub_type_forms/artistic_types/OutputRow.tsx
src/pages/registration/resource_type_tab/sub_type_forms/artistic_types/architecture/ArtisticArchitectureForm.tsx
src/pages/registration/resource_type_tab/sub_type_forms/artistic_types/architecture/CompetitionModal.tsx
src/pages/registration/resource_type_tab/sub_type_forms/artistic_types/architecture/PublicationMentionModal.tsx
src/pages/registration/resource_type_tab/sub_type_forms/artistic_types/design/ArtisticDesignForm.tsx
src/pages/registration/resource_type_tab/sub_type_forms/artistic_types/design/VenueModal.tsx
src/translations/en/registration.json
src/translations/nb/registration.json
src/types/publication_types/artisticRegistration.types.ts
src/utils/dataTestIds.ts
src/utils/validation/registration/referenceValidation.ts

Np 3432 add publication mention

---

src/pages/registration/resource_type_tab/sub_type_forms/artistic_types/OutputRow.tsx
src/pages/registration/resource_type_tab/sub_type_forms/artistic_types/architecture/ArtisticArchitectureForm.tsx
src/pages/registration/resource_type_tab/sub_type_forms/artistic_types/architecture/AwardModal.tsx
src/translations/en/registration.json
src/translations/nb/registration.json
src/types/publication_types/artisticRegistration.types.ts
src/utils/dataTestIds.ts

Np 3431 architecture prize

---

src/pages/public_registration/PublicGeneralContent.tsx
src/pages/public_registration/PublicPublicationContext.tsx
src/pages/registration/resource_type_tab/sub_type_forms/artistic_types/OutputRow.tsx
src/translations/en/common.json
src/translations/nb/common.json
src/utils/registration-helpers.ts

Np 3438 artistic architecture landing page

---

src/pages/basic_data/BasicDataPage.tsx

NP-8443 Visualize selected menu item

---

cypress/integration/edit_registration.spec.js
src/translations/en/publicationTypes.json
src/translations/nb/publicationTypes.json
src/types/publicationFieldNames.ts

Oppdater navn på journalpubliksjon, og fjern kronikk som undertype.

Np 9096 minor journal updates

---

src/pages/basic_data/institution_admin/AddEmployeePage.tsx
src/pages/basic_data/institution_admin/AddRolePanel.tsx

Oppretting av NVA-bruker feiler noen ganger av ukjent årsak. Mistenker at det kan være fordi kallet blir for tett inntil oppretting av Cristin person, og at man derfor ikke får noen treff på fødselsnummer i Cristin når man oppretter NVA bruker

NP-7222 Add roles when creating new employees

---

cypress/integration/registration_description.spec.js
src/api/mock-interceptor.ts
src/pages/basic_data/fields/PositionField.tsx
src/redux/reducers/rootReducer.ts
src/redux/resourcesSlice.ts
src/utils/hooks/useFetchResource.ts

Tillat å lagre alle responser i redux, selv de som ikke har noen egen id. Bruk selve URI som nøkkel uansett

Allow any uri as key for useFetchResource

---

src/pages/basic_data/institution_admin/AddAffiliationPanel.tsx
src/pages/basic_data/institution_admin/AddEmployeePage.tsx
src/pages/basic_data/institution_admin/AddRolePanel.tsx
src/pages/basic_data/institution_admin/FindPersonPanel.tsx

Se todo for å løse denne hacken her: https://unit.atlassian.net/browse/NP-9121

Np 7222 wait before creating user

---

src/translations/en/registration.json
src/translations/nb/registration.json
src/types/publication_types/content.types.ts

Legg til `Introduction` og `ExhibitionCatalogChapter`

Np 3457 add anthology chapter content types

---

src/layout/header/Header.tsx

Avoid wrapping of basic data menu item

---

src/pages/basic_data/BasicDataPage.tsx
src/pages/basic_data/institution_admin/PersonRegisterPage.tsx
src/translations/en/basicData.json
src/translations/nb/basicData.json
src/utils/dataTestIds.ts
src/utils/urlPaths.ts

NP-9148 Add an empty page for Person Register

---

src/pages/basic_data/institution_admin/PersonRegisterPage.tsx
src/pages/public_registration/PublicRegistrationContributors.tsx
src/pages/registration/contributors_tab/components/ContributorRow.tsx
src/translations/en/basicData.json
src/translations/en/common.json
src/translations/en/registration.json
src/translations/nb/basicData.json
src/translations/nb/common.json
src/translations/nb/registration.json
src/types/user.types.ts
src/utils/user-helpers.ts

Np 9148 person register page

---

src/layout/header/Header.tsx
src/layout/header/Menu.tsx
src/types/user.types.ts

Flytt menyvalg for editor og gi denne samme navn som kortversjon av Customer

Np 9155 editor page

---

src/pages/basic_data/BasicDataPage.tsx
src/pages/basic_data/institution_admin/AddEmployeePage.tsx
src/pages/basic_data/institution_admin/person_register/PersonRegisterPage.tsx
src/pages/editor/EditorPage.tsx
src/pages/editor/VocabularyRow.tsx

Fortsatt langt fra kjempebra, men det er i det minste en bedring...

Np 9177 mobile pages for Basic Data and Editor

---

src/components/PageWithSideMenu.tsx
src/pages/basic_data/BasicDataPage.tsx
src/pages/editor/EditorPage.tsx
src/pages/my_page/MyPagePage.tsx

Bruk samme header komponent hver gang i stedet for å kopiere for hver fil

Np 9253 general header component

---

src/pages/public_registration/PublicGeneralContent.tsx
src/pages/public_registration/PublicPublicationContext.tsx
src/pages/public_registration/PublicPublicationInstance.tsx
src/pages/registration/resource_type_tab/ArtisticTypeForm.tsx
src/pages/registration/resource_type_tab/sub_type_forms/artistic_types/OutputRow.tsx
src/pages/registration/resource_type_tab/sub_type_forms/artistic_types/architecture/ArtisticArchitectureForm.tsx
src/pages/registration/resource_type_tab/sub_type_forms/artistic_types/moving_picture/ArtisticMovingPictureForm.tsx
src/pages/registration/resource_type_tab/sub_type_forms/artistic_types/moving_picture/BroadcastModal.tsx
src/translations/en/feedback.json
src/translations/en/publicationTypes.json
src/translations/en/registration.json
src/translations/nb/feedback.json
src/translations/nb/publicationTypes.json
src/translations/nb/registration.json
src/types/publicationFieldNames.ts
src/types/publication_types/artisticRegistration.types.ts
src/types/publication_types/bookRegistration.types.ts
src/utils/registration-helpers.ts
src/utils/validation/registration/referenceValidation.ts

Np 9305 artistic film

---

src/pages/public_registration/PublicGeneralContent.tsx
src/pages/public_registration/PublicPublicationContext.tsx
src/pages/registration/resource_type_tab/ArtisticTypeForm.tsx
src/pages/registration/resource_type_tab/components/isbn_and_pages/IsbnField.tsx
src/pages/registration/resource_type_tab/sub_type_forms/artistic_types/OutputRow.tsx
src/pages/registration/resource_type_tab/sub_type_forms/artistic_types/music_performance/ArtisticMusicPerformanceForm.tsx
src/pages/registration/resource_type_tab/sub_type_forms/artistic_types/music_performance/MusicScoreModal.tsx
src/translations/en/registration.json
src/translations/nb/registration.json
src/types/publication_types/artisticRegistration.types.ts
src/utils/registration-helpers.ts

Np 9306 add score to music

---

package-lock.json
package.json
src/pages/registration/FilesAndLicensePanel.tsx
src/pages/registration/resource_type_tab/sub_type_forms/ChapterForm.tsx
src/translations/engTranslations.json
src/translations/nobTranslations.json
src/types/file.types.ts

Np 9282 translation ordering

---

src/pages/dashboard/Dashboard.tsx

Set fixed width of dashboard banner

---

src/pages/search/SearchPage.tsx
src/pages/search/filters/BaseFilterItem.tsx
src/pages/search/filters/RegistrationTypeFilter.tsx
src/translations/enTranslations.json
src/translations/nbTranslations.json

Unngå ugyldige children for `ul` i filter-liste

Np 9376 a11y filter list

---

cypress/e2e/registration_resource_book.spec.ts
cypress/e2e/registration_resource_chapter.spec.ts
cypress/e2e/registration_resource_report.spec.ts
cypress/e2e/registration_validation.spec.ts
src/components/ConfirmDialog.tsx
src/components/RouteLeavingGuard.tsx
src/pages/basic_data/app_admin/UserList.tsx
src/pages/my_page/user_profile/UserOrcid.tsx
src/pages/my_registrations/MyRegistrationsList.tsx
src/pages/registration/ResourceTypePanel.tsx
src/pages/registration/contributors_tab/components/AffiliationsCell.tsx
src/pages/registration/contributors_tab/components/ContributorRow.tsx
src/pages/registration/resource_type_tab/components/DoiField.tsx
src/pages/registration/resource_type_tab/sub_type_forms/artistic_types/architecture/ArtisticArchitectureForm.tsx
src/pages/registration/resource_type_tab/sub_type_forms/artistic_types/design/ArtisticDesignForm.tsx
src/pages/registration/resource_type_tab/sub_type_forms/artistic_types/performing_arts/ArtisticPerformingArtsForm.tsx
src/translations/enTranslations.json
src/translations/nbTranslations.json
src/types/publicationFieldNames.ts
src/utils/dataTestIds.ts

Confirm dialog, and reset values when changing type

---

README.md
cypress.config.ts
package.json

Push testresultater til cypress dashboard

Cypress dashboard

---

src/App.tsx
src/pages/basic_data/institution_admin/ViewingScopeCell.tsx
src/pages/messages/MessageList.tsx
src/pages/messages/WorklistItems.tsx
src/pages/messages/WorklistPage.tsx
src/redux/userSlice.ts
src/types/registration.types.ts
src/types/user.types.ts

Ikke hent InstitutionUser for hver page load. Hent bare når det trengs, som for å vise avgrensning på worklist

Np 3056 avoid redundant fetch

---

src/pages/basic_data/institution_admin/AddEmployeePage.tsx

Bug hvor det alltid ble forsøkt å opprette en ny person. Payload inneholdt bare ny employment også, så med PUT ville man mistet alle eksisterende emplopyments

Np 9147 add employee bug

---

src/components/CreateCristinPersonDialog.tsx
src/types/user.types.ts

Løs feil hvor man ikke fikk opprettet seg selv i cristin fordi det ble sendt med tom liste for employments

Create person without employments

---

src/pages/basic_data/institution_admin/person_register/PersonRegisterPage.tsx
src/translations/enTranslations.json
src/translations/nbTranslations.json

PO-bestilling: https://sikt-no.slack.com/archives/C03QL4RS3RR/p1667374392466389
Før: 
Etter:

Update label for person register search field

---

src/redux/userSlice.ts

NP-17235 Simplify logic

---

src/components/StructuredSeoData.tsx
src/pages/public_registration/PublicRegistrationContent.tsx

Må verifisere denne når den er ute i dev

NP-17161 Add structured SEO data to landing page

---

cypress/e2e/registration_contributors.spec.ts
cypress/e2e/registration_validation.spec.ts
src/pages/registration/ContributorsPanel.tsx
src/pages/registration/contributors_tab/AddContributorModal.tsx
src/pages/registration/contributors_tab/Contributors.tsx
src/pages/registration/contributors_tab/components/AddContributorForm.tsx
src/pages/registration/contributors_tab/components/AffiliationsCell.tsx
src/pages/registration/contributors_tab/components/ContributorRow.tsx
src/translations/enTranslations.json
src/translations/nbTranslations.json
src/types/publication_types/mediaContributionRegistration.types.ts
src/utils/dataTestIds.ts

Fjern separat visning for "Hovedbidragsytere" og "andre bidragsytere"

Np 18098 merge contributor tables

---

src/pages/dashboard/Dashboard.tsx

Unngå at header deles over to linjer

Fix banner heading

---

src/components/institution/SelectInstitutionForm.tsx
src/pages/registration/contributors_tab/components/AffiliationsCell.tsx
src/translations/enTranslations.json
src/translations/nbTranslations.json
src/utils/dataTestIds.ts

Vis tilhørigheter som allerede ligger i posten når man skal legge til tilhørighet for en bidragsyter.

Np 18057 suggested affiliations

---

src/pages/public_registration/public_files/FilesLandingPageAccordion.tsx
src/pages/registration/new_registration/LinkRegistration.tsx
src/pages/registration/new_registration/LinkRegistrationForm.tsx
src/utils/general-helpers.ts
src/utils/registration-helpers.ts
src/utils/validation/doiSearchValidation.ts

Litt refaktorering og forenkling

Minor refactoring

---

src/components/PageHeader.tsx
src/components/TruncatableTypography.tsx
src/pages/basic_data/app_admin/InstitutionList.tsx
src/pages/basic_data/app_admin/UserList.tsx
src/pages/basic_data/institution_admin/person_register/PersonRegisterPage.tsx
src/pages/editor/EditorCurators.tsx
src/pages/infopages/PrivacyPolicy.tsx
src/pages/my_registrations/MyRegistrationsList.tsx
src/pages/public_registration/PublicPublicationContext.tsx
src/pages/registration/contributors_tab/Contributors.tsx
src/pages/registration/contributors_tab/components/CristinPersonList.tsx
src/themes/mainTheme.ts

Bruk Paper for Tables. Sett table head til bold. Skjul hele <caption> tag visuelt.

Table design changes

---

package-lock.json
package.json

Reverts BIBSYSDEV/NVA-Frontend#3417

Revert "Bump start-server-and-test from 1.15.1 to 1.15.2"

---

src/pages/registration/contributors_tab/AddContributorModal.tsx
src/pages/registration/contributors_tab/Contributors.tsx
src/pages/registration/contributors_tab/components/AddContributorForm.tsx
src/pages/registration/contributors_tab/components/AddUnverifiedContributorForm.tsx
src/translations/enTranslations.json
src/translations/nbTranslations.json

- Bruk "Bidragsyter" som begrep i stedet for "Bruker" og faktisk rollenavn flere plasser
- Vis søketerm i Navn-feltet når man skal legge til ikke-verifisert person
- Placeholder
- Småtjafs

Np 27687 contributors fixes

---

src/pages/basic_data/app_admin/CustomerDoiPasswordField.tsx

Unngå at frontend defaulter tilbake til init passord når man prøver å viske ut

Np 23268 allow removing doi password

---

src/pages/my_registrations/MyRegistrations.tsx
src/translations/enTranslations.json
src/translations/nbTranslations.json
src/types/registration.types.ts

Inkluder registreringer hvor bare metadata er publisert i listen over mine registreringer

List published metadata as published registration

---

src/pages/public_registration/PublicPublicationContext.tsx
src/pages/registration/resource_type_tab/sub_type_forms/media_types/MediaContributionForm.tsx
src/types/publicationFieldNames.ts
src/types/publication_types/mediaContributionRegistration.types.ts
src/utils/formik-helpers.ts

Caused by https://github.com/BIBSYSDEV/nva-datamodel-java/pull/335

NP-28838 Update series name field

---

src/pages/search/SearchPage.tsx
src/pages/search/person_search/PersonSearch.tsx
src/themes/mainTheme.ts
src/utils/searchHelpers.ts

Np 28592 a11y search buttons

---

src/components/RegistrationList.tsx
src/pages/projects/ProjectContributors.tsx
src/pages/registration/description_tab/projects_field/ProjectsField.tsx
src/pages/registration/description_tab/projects_field/projectHelpers.ts
src/pages/search/SearchPage.tsx
src/pages/search/project_search/ProjectListItem.tsx
src/pages/search/project_search/ProjectSearch.tsx
src/themes/mainTheme.ts
src/translations/enTranslations.json
src/translations/nbTranslations.json
src/types/project.types.ts
src/utils/searchHelpers.ts
src/utils/testfiles/mockProjects.ts

Np 28795 project search

---

src/pages/search/SearchPage.tsx
src/translations/enTranslations.json
src/translations/nbTranslations.json

NP-29038 Add search filter heading

---

cypress/e2e/registration.spec.ts
src/pages/registration/new_registration/EditRegistration.tsx
src/pages/registration/new_registration/LinkRegistration.tsx
src/pages/registration/new_registration/StartEmptyRegistration.tsx
src/pages/registration/new_registration/UploadRegistration.tsx

Start new registration when clicking the accordion. Previously one had to click "Start registration" one extra time afterwards

Np 27942 new registration button

---

src/components/AutocompleteTextField.tsx
src/pages/basic_data/fields/PositionField.tsx
src/pages/basic_data/institution_admin/AddAffiliationPanel.tsx
src/pages/basic_data/institution_admin/person_register/PersonRegisterPage.tsx

Set type='search' for search inputs

---

src/components/PageWithSideMenu.tsx

Invisible link icon button

---

src/pages/research_profile/ResearchProfile.tsx

Legg til paginering for registreringstreff på forskerprofil

Np 30286 paging research profile

---

src/pages/basic_data/app_admin/CustomerInstitutionMetadataForm.tsx
src/translations/enTranslations.json
src/translations/nbTranslations.json
src/types/customerInstitution.types.ts
src/utils/testfiles/mockCustomerInstitutions.ts
src/utils/validation/customerInstitutionValidation.ts

DOI URL fjernes fra konfig og blir heller en miljøvariabel for backend

NP-18627 Remove DOI URL field

---

src/pages/public_registration/PublicPublicationContext.tsx
src/pages/registration/resource_type_tab/sub_type_forms/artistic_types/architecture/AwardModal.tsx
src/pages/registration/resource_type_tab/sub_type_forms/artistic_types/architecture/PublicationMentionModal.tsx
src/translations/enTranslations.json
src/translations/nbTranslations.json

Fører til kluss mot Lokalise slik det var

Avoid conflicting plural keys

---

src/pages/projects/ProjectGeneralInfo.tsx
src/pages/registration/description_tab/projects_field/projectHelpers.ts
src/types/project.types.ts

håndter manglende funding-koder, og koder med slash

NP-32788 Handle different funding codes

---

src/pages/projects/form/ProjectFormDialog.tsx
src/pages/projects/form/ProjectFormPanel2.tsx
src/resources/cristinCategories.ts
src/translations/enTranslations.json
src/translations/nbTranslations.json
src/types/project.types.ts
src/utils/testfiles/mockProjects.ts

Nytt felt for å velge prosjektkategori

Np 36917 set project category

---

src/pages/projects/ProjectGeneralInfo.tsx

Tenker egen PR for å liste relaterte prosjekt

Np 36917 show project fields on landing page

---

src/components/RegistrationList.tsx

Vis ORCID og korresponderende ikon for bidragsytere når man søker opp registrering

NP-38667 Show ORCID link for searched registrations

---

src/components/PageWithSideMenu.tsx
src/pages/my_page/MyPagePage.tsx
src/utils/dataTestIds.ts

Åpner dialog på samme måte som fra registraring wizard. Ikke viktig for PO at man ble sendt til /projects i samme slengen

NP-38665 Add create project button on my page

---

src/pages/registration/contributors_tab/components/AffiliationsCell.tsx

Unngå at alle ikke-verifiserte tilknytkninger forsvinner når man prøver å fjerne en

Np 38270 keep other affiliations when confirming

---

public/index.html
src/index.tsx
src/themes/mainTheme.ts

Unngå at webkit-browsere viser en ekstra clear-knapp

Np 39133 hide clear search field

---

src/components/RegistrationList.tsx
src/pages/search/SearchPage.tsx
src/pages/search/registration_search/RegistrationSearch.tsx
src/pages/search/registration_search/RegistrationSearchBar.tsx

- Legg inn margin for søkefelt på små skjermer, slik at den ikke går helt ut til kanten.
- Legg til wrap for bidragsyterliste, slik at den ikke går utover skjermen

Improve responsiveness of front page

---

src/pages/messages/TasksPage.tsx

NP-41504 Add pagination to ticket search

---

src/components/RegistrationList.tsx
src/pages/basic_data/app_admin/central_import/CentralImportResultItem.tsx
src/pages/public_registration/PublicRegistrationContent.tsx
src/pages/public_registration/public_files/FilesLandingPageAccordion.tsx
src/pages/registration/ContributorsPanel.tsx
src/pages/registration/FilesAndLicensePanel.tsx
src/pages/registration/ResourceTypePanel.tsx
src/pages/registration/resource_type_tab/SelectRegistrationTypeField.tsx
src/utils/formik-helpers.ts
src/utils/registration-helpers.ts

Quick-fix for å unngå at ting krasjer om man starter med lenke til nettside.
Egen oppgave for å finne en bedre løsning: https://unit.atlassian.net/browse/NP-42715

Np 42521 starting with link error

---

src/pages/my_page/MyPagePage.tsx
src/pages/projects/ProjectLandingPage.tsx
src/pages/registration/description_tab/projects_field/ProjectsField.tsx
src/pages/search/project_search/ProjectListItem.tsx

Jobber videre med støtte for å legge til/endre finansiering

Allow all users to create and update projects

---

src/pages/messages/TasksPage.tsx

Skalerer litt dårlig logikken her. Tror vi burde dele det opp i flere komponenter, men ønsker egentlig ikke å bruke så mye tid på akkurat det nå siden skoen trykker mer andre plasser :/

NP-42075 Add ticket type facet

---

src/pages/projects/form/CreateProjectStartPage.tsx

Legg inn funder når man starter registrering med en funding

Np 44580 prefill funder

---

src/pages/projects/form/ProjectFormDialog.tsx
src/translations/nbTranslations.json

NP-44582 Warn user before closing dialog

---

src/pages/basic_data/institution_admin/person_register/PersonTableRow.tsx

Unngå evig lasting når man skal endre en person/bruker

Ensure positions are fetched

---

src/pages/public_registration/action_accordions/PublishingAccordion.tsx

Skjul meldingsboks når det ikke er noen aktiv forespørsel

Np 44724 hide empty messages box

---

documentation/deployment/deployment.md

Mermaid markdown: https://mermaid.js.org/syntax/gitgraph.html (extension for vscode: https://marketplace.visualstudio.com/items?itemName=bierner.markdown-mermaid)

Add figure to depict our branching and deployment strategy

---

src/pages/public_registration/action_accordions/DoiRequestAccordion.tsx
src/pages/public_registration/action_accordions/PublishingAccordion.tsx
src/pages/public_registration/action_accordions/SupportAccordion.tsx

Et lite steg i riktig retningen

NP-42253 Add border colors for ticket accordions on landing page

---

i18n-unused.config.js

https://github.com/mxmvshnvsk/i18n-unused#configuration-options
Nå vil vi bare få beskjed på ubrukte bokmål-keys, slik at vi slipper å fjerne ting fra vår kode som kommer lokalise

Ignore unsed i18n keys for english and nynorsk

---

cypress/e2e/menu.spec.ts

har et håp om at dette vil fikse problemene med at noen testkjøringer feiler i aws, men eneste måten å verifisere er å få testet det over tid da..

Split menu tests

---

src/pages/messages/TasksPage.tsx
src/pages/messages/components/TicketListItem.tsx
src/pages/my_page/MyPagePage.tsx
src/pages/public_registration/RegistrationLandingPage.tsx
src/translations/nbTranslations.json
src/utils/urlPaths.ts

Oppdater ticket-visning på min side

NP-44789 Update layout of my page messages

---

src/pages/registration/ErrorList.tsx

Remove redundant padding

---

src/layout/header/Menu.tsx

Oppdater redaktør-link for mobilvisning

Update editor path

---

src/pages/messages/components/TicketListItem.tsx

Minste motstands-vei for en liten bedring.
Før:
Etter:

NP-44809 Improve responsiveness of ticket list

---

src/pages/public_registration/ActionPanel.tsx
src/pages/public_registration/ActionPanelContent.tsx

Hindrer brukere fra å opprette tickets når de jobber i kontekst av en Kurator

NP-44831 Hide accordions from Tasks if no tickets exist

---

src/pages/public_registration/action_accordions/TicketAssignee.tsx
src/pages/registration/contributors_tab/ContributorIndicator.tsx
src/utils/registration-helpers.ts

Jobber videre med å legge til støtte for å sette andre kuratorer i egen PR

NP-44832 Update design for assigning a task

---

src/pages/public_registration/PublicRegistrationContent.tsx
src/pages/public_registration/action_accordions/DoiRequestAccordion.tsx
src/pages/public_registration/public_files/FileRow.tsx
src/pages/public_registration/public_files/FilesLandingPageAccordion.tsx
src/translations/enTranslations.json
src/translations/nbTranslations.json

Np 44854 show metadata not published

---

src/api/roleApi.ts
src/pages/public_registration/action_accordions/TicketAssignee.tsx
src/translations/nbTranslations.json
src/utils/dataTestIds.ts

Np 44832 select curator to ticket

---

src/components/ContributorIndicators.tsx
src/components/RegistrationList.tsx
src/pages/messages/components/TicketListItem.tsx

Hele raden/item med ticket vil nå være klikkbar som en link

Np 44851 make whole ticket item clickable

---

src/components/ContributorIndicators.tsx
src/components/RegistrationList.tsx
src/pages/messages/components/TicketListItem.tsx

NP-44866 Show draft label on ticket list

---

src/pages/registration/description_tab/projects_field/ProjectsField.tsx

Np 44570 react query project search in wizard

---

src/pages/messages/TasksPage.tsx
src/pages/my_page/MyPagePage.tsx
src/translations/nbTranslations.json
src/utils/dataTestIds.ts

Np 44897 filter unread messages

---

src/pages/public_registration/PublicRegistration.tsx

Update layout for landing page

---

src/pages/messages/TasksPage.tsx
src/pages/my_page/MyPagePage.tsx
src/translations/nbTranslations.json

Enda litt flere typer knapper å forholde oss til her da

NP-44930 Update unread filter button

---

src/layout/header/Menu.tsx
src/pages/editor/EditorCurators.tsx
src/pages/editor/EditorDoi.tsx
src/pages/editor/EditorPage.tsx
src/pages/editor/PublishStrategySettings.tsx
src/pages/messages/TasksPage.tsx
src/pages/messages/components/TicketListItem.tsx
src/pages/public_registration/ActionPanelContent.tsx
src/pages/public_registration/PublicDoi.tsx
src/pages/public_registration/RegistrationLandingPage.tsx
src/pages/public_registration/action_accordions/PublishingAccordion.tsx
src/pages/public_registration/action_accordions/TicketAssignee.tsx
src/pages/registration/description_tab/vocabularies/VocabularyBase.tsx
src/utils/routes/Routes.tsx

følg best practice: https://react-redux.js.org/api/hooks#no-op-selector-check

Update usage of useSelector

---

src/layout/header/Header.tsx
src/layout/header/LoginButton.tsx
src/layout/header/Menu.tsx
src/layout/header/MenuButton.tsx

Kremeksempel på hvorfor vi bør passe på å fjere all styling som egentlig ikke trengs 😬 Liten tue kan velte stort lass, osv

NP-44969 Show menu items on Safari

---

src/pages/basic_data/BasicDataPage.tsx
src/pages/my_page/MyPagePage.tsx

Unngå "Not found"-meldingen som ble vist en liten brøkdel av et søkund fordi vi håndterte redirects selv i useEffect i stedet for direkte med react-router

NP-44983 Handle redirects with react-router

---

cypress/support/commands.ts
src/api/mock-interceptor.ts
src/pages/public_registration/public_files/FileRow.tsx
src/pages/registration/FilesAndLicensePanel.tsx
src/pages/registration/RegistrationForm.tsx
src/pages/registration/files_and_license_tab/FilesTableRow.tsx
src/redux/userSlice.ts
src/types/user.types.ts
src/utils/registration-helpers.ts
src/utils/testfiles/mockCustomerInstitutions.ts
src/utils/testfiles/mock_feide_user.ts

Krev egen rolle for å endre filer på studentoppgave, og embargo-fil på studentoppgave.

Np 38866 add access rights to thesis

---

src/pages/registration/resource_type_tab/SelectRegistrationTypeField.tsx
src/pages/registration/resource_type_tab/components/RegistrationTypesRow.tsx
src/translations/nbTranslations.json

NP-38867 Disable certian degree types

---

src/pages/my_page/user_profile/MyProjectRegistrations.tsx

Fix bug introduced in https://github.com/BIBSYSDEV/NVA-Frontend/pull/4287

NP-45008 Update logic for project filter

---

cypress/e2e/search.spec.ts
src/components/ListPagination.tsx
src/components/RegistrationList.tsx
src/pages/basic_data/app_admin/central_import/CentralImportPage.tsx
src/pages/editor/EditorCurators.tsx
src/pages/search/CristinSearchPagination.tsx
src/pages/search/SearchPage.tsx
src/pages/search/person_search/PersonSearch.tsx
src/pages/search/project_search/ProjectSearch.tsx
src/pages/search/registration_search/RegistrationSearch.tsx
src/translations/nbTranslations.json
src/utils/constants.ts
src/utils/hooks/useSearchRegistrations.ts

Ny komponent for paginering
Desktop:
Mobil:

Np 44931 custom pagination component

---

src/pages/messages/components/DoiRequestMessagesColumn.tsx
src/pages/messages/components/PublishingRequestMessagesColumn.tsx
src/translations/enTranslations.json
src/translations/nbTranslations.json
src/utils/constants.ts
src/utils/general-helpers.ts

Småoppgaver som kommer fra ukens designprat. Hver commit er egentlig en separat oppgave, og kan ses på for seg selv, heller enn hele PRen i ett

Design changes

---

src/api/publicationChannelApi.ts
src/pages/registration/resource_type_tab/components/JournalField.tsx
src/pages/registration/resource_type_tab/components/JournalFormDialog.tsx
src/pages/registration/resource_type_tab/components/PublisherField.tsx
src/pages/registration/resource_type_tab/components/PublisherFormDialog.tsx
src/pages/registration/resource_type_tab/components/SeriesField.tsx

Legg kanalen som ble opprettet til som valgt tidsskrift/utgiver/serie

Np 45020 add created channel

---

src/components/ListPagination.tsx
src/pages/basic_data/app_admin/UserList.tsx
src/pages/basic_data/institution_admin/person_register/PersonRegisterPage.tsx
src/pages/editor/EditorCurators.tsx
src/pages/messages/TasksPage.tsx
src/pages/messages/components/TicketList.tsx
src/pages/my_page/MyPagePage.tsx
src/pages/my_page/user_profile/MyProjectRegistrations.tsx
src/pages/my_page/user_profile/MyProjects.tsx
src/pages/my_page/user_profile/MyResults.tsx
src/pages/my_registrations/MyRegistrationsList.tsx
src/pages/projects/ProjectResultsAccordion.tsx
src/pages/projects/RelatedProjects.tsx
src/pages/registration/contributors_tab/Contributors.tsx
src/pages/registration/contributors_tab/components/AddContributorForm.tsx
src/pages/registration/contributors_tab/components/CristinPersonList.tsx
src/pages/research_profile/ResearchProfile.tsx
src/translations/nbTranslations.json

Bruk den nye Pagination-komponenten rundt omkring

Np 44931 update pagination

---

src/components/ListPagination.tsx
src/pages/messages/components/TicketList.tsx
src/pages/search/registration_search/RegistrationSearch.tsx

Se diskusjon i https://unit.atlassian.net/browse/NP-45094

Np 44931 ensure valid pagination interval

---

src/pages/basic_data/institution_admin/person_register/PersonTableRow.tsx

Fjern spesialroller knyttet til kurator når man fjerner kurator-rollen

NP-45146 Remove specific curator roles

---

src/pages/basic_data/BasicDataPage.tsx
src/pages/basic_data/app_admin/AdminCustomerInstitutionsContainer.tsx
src/pages/basic_data/app_admin/central_import/CentralImportDuplicationCheckPage.tsx
src/pages/basic_data/app_admin/central_import/CentralImportPage.tsx
src/pages/basic_data/institution_admin/AddEmployeePage.tsx
src/pages/basic_data/institution_admin/person_register/PersonRegisterPage.tsx
src/pages/my_page/MyPagePage.tsx
src/pages/registration/contributors_tab/Contributors.tsx
src/translations/enTranslations.json
src/translations/nbTranslations.json
src/translations/nnTranslations.json

NB! Avhenger av https://github.com/BIBSYSDEV/NVA-Frontend/pull/4404
Legger inn høyremeny for visning av importkandidat.
Utbedringer av høyremeny kommer i egen PR.

Np 45038 actions panel central import

---

src/pages/basic_data/BasicDataPage.tsx
src/redux/userSlice.ts
src/types/user.types.ts

Vente med merge til backend har rullet ut oppdatert rolle

NP-45159 Update name of importer role

---

src/translations/nbTranslations.json

klusset til forrige deploy til staging og main, så må merge de branchene tilbake til develop... mega-noob move, men tror dette er enkleste løsning altså 🙃

Merge develop

---

src/api/registrationApi.ts
src/pages/basic_data/BasicDataPage.tsx
src/pages/basic_data/app_admin/central_import/CentralImportCandidateMerge.tsx
src/pages/basic_data/app_admin/central_import/CentralImportDuplicateSearch.tsx
src/pages/basic_data/app_admin/central_import/CentralImportDuplicationCheckPage.tsx
src/translations/nbTranslations.json
src/utils/urlPaths.ts

Legg til mulighet for å velge et publisert resultat man vil merge importkandidaten med.
Støtte for å overskrive tittel og sammendrag i første omgang, som en POC

Np 45247 open import candidate merge

---

src/pages/basic_data/institution_admin/person_register/PersonTableRow.tsx

Sørg for å vise riktig data når man oppdaterer brukere

NP-45252 Refetch data after updating user

---

src/pages/basic_data/app_admin/central_import/CentralImportCandidateMerge.tsx
src/translations/nbTranslations.json

Legg inn mer info og felter for å slå sammen importkandidat med resultat

Np 45247 merge more import data

---

src/pages/search/registration_search/RegistrationSearchBar.tsx
src/pages/search/registration_search/filters/RegistrationFacetsFilter.tsx
src/types/registration.types.ts
src/utils/testfiles/mockSearchResults.ts

Unngå at hele frontend krasjer etter en modellendring

Fix result search aggregation type

---

src/components/PublicationPointsTypography.tsx
src/pages/messages/components/NviCandidateListItem.tsx
src/pages/messages/components/NviCandidatePage.tsx
src/types/nvi.types.ts

Viser publiseringspoeng per institusjon som skal ha det, inkludert status. Noen forenklinger mtp design for å få det fortere gjennom til testing.

NP-45288 Show publication points per institution

---

cypress/e2e/menu.spec.ts

Denne er for å trigge nytt bygging etter kreativ triksing i git som gjorde at amplify ikke lenger ville bygge siste commit i branchen

Uncomment (skipped) tests (#4555)

---

src/components/MessageForm.tsx
src/pages/messages/components/NviCandidatePage.tsx

NP-45290 Allow to cancel NVI rejection

---

package-lock.json
package.json

Degrader Cypress for å unngå error i CodeBuild

Degrade cypress

---

src/pages/messages/components/NviCandidateListItem.tsx
src/types/nvi.types.ts
src/utils/date-helpers.ts

Oppdater etter endringer i datamodell

Update date model

---

src/pages/messages/components/NviApprovalStatuses.tsx
src/pages/messages/components/NviCandidateActions.tsx
src/pages/messages/components/NviCandidatePage.tsx
src/translations/nbTranslations.json
src/types/nvi.types.ts

Ikke tillat endringer på kandidater som ikke er i en åpen periode (NB! I skrivende stund har alle kandidater status `OpenPeriod`, men dette endres plutselig)

NP-45338 Handle NVI periods

---

src/api/apiPaths.ts
src/api/scientificIndexApi.ts
src/pages/basic_data/BasicDataPage.tsx
src/pages/basic_data/app_admin/NviPeriodsPage.tsx
src/translations/nbTranslations.json
src/types/nvi.types.ts
src/utils/dataTestIds.ts
src/utils/urlPaths.ts

Første steg for å håndtere NVI-kandidater for APp-admin. Bare opplisting av kandidater i denne PRen

Np 45361 list nvi periods

---

src/api/scientificIndexApi.ts
src/pages/basic_data/app_admin/NviPeriodsPage.tsx
src/pages/basic_data/app_admin/UpsertNviPeriodDialog.tsx
src/translations/nbTranslations.json
src/utils/nviHelpers.ts

Åpne for oppdatering av NVI-periode

Edit NVI period

---

src/pages/messages/TasksPage.tsx
src/pages/messages/components/ViewingScopeFilter.tsx
src/translations/nbTranslations.json

Np 45367 show org filters

---

src/pages/messages/TasksPage.tsx
src/pages/messages/components/OrganizationScope.tsx
src/pages/messages/components/OrganizationScopeItem.tsx
src/pages/messages/components/ViewingScopeFilter.tsx
src/pages/messages/components/ViewingScopeItem.tsx
src/translations/nbTranslations.json
src/utils/dataTestIds.ts

Legg inn scope filter for NVI.
Dette skal også brukes av ticket søk etter hvert, men er ikke på plass enda (må løses litt på backend der først)

Np 45367 add unit filter

---

src/pages/messages/TasksPage.tsx
src/pages/messages/components/OrganizationScope.tsx
src/translations/nbTranslations.json

Dette er ikke klart på ticket-søk enda, derfor er det bare lagt til på NVI for nå

NP-45367 Add filter to exclude hits for subunits

---

src/themes/mainTheme.ts

Støttet etter denne: https://github.com/BIBSYSDEV/NVA-Frontend/pull/4688

Add nynorsk support for MUI

---

src/layout/header/LanguageSelector.tsx

Etter designprat 25.10: https://sikt-no.slack.com/archives/CPHGQRNAJ/p1698236253406739?thread_ts=1698233455.892149&cid=CPHGQRNAJ

NP-45474 Remove flags from language selector

---

src/pages/messages/components/NviCandidatePage.tsx

Veldig enkel visning, men tror jeg bare gjør det så enkelt som mulig her nå. Vi har samme for registreringer etc også, så det trengs egentlig en overhaling av alle

Handle blocked candidate fetch

---

src/pages/registration/new_registration/LinkRegistration.tsx

Bug som gjør at man ikke lenger kan søke på doi uten å oppgi hele URLen

Allow starting with short version of doi

---

src/pages/registration/resource_type_tab/components/JournalField.tsx
src/pages/registration/resource_type_tab/components/JournalFormDialog.tsx
src/pages/registration/resource_type_tab/components/PublisherField.tsx
src/pages/registration/resource_type_tab/components/PublisherFormDialog.tsx
src/pages/registration/resource_type_tab/components/SeriesField.tsx

Bruk søketerm som default navn når man oppretter ny kanal

Prefill channel name from search when creating

---

src/pages/messages/TasksPage.tsx

Avvent merge til dette virker som ønsket mot backend

Set viewing scope for ticket search

---

src/pages/public_registration/PublicRegistrationContent.tsx

Fix external link count for DMP

---

src/pages/messages/components/NviCorrectionList.tsx

Update link to correction list

---

src/pages/registration/contributors_tab/Contributors.tsx

Trenger en siste bekreftelse fra PO før merge: https://unit.atlassian.net/browse/NP-44968?focusedCommentId=98755

NP-44968 Preserve ORCID when verifying contributor

---

src/components/SearchForm.tsx
src/pages/messages/TasksPage.tsx
src/pages/messages/components/NviCandidatesList.tsx
src/pages/messages/components/TicketList.tsx
src/pages/my_page/MyPagePage.tsx
src/translations/nbTranslations.json

Legg til søkefelt som søker på alle properties i toppen for både tickets og NVI

NP-45439 Allow searching for tickets and NVI candidates

---

src/pages/public_registration/PublicGeneralContent.tsx
src/translations/nbTranslations.json
src/types/registration.types.ts
src/utils/dataTestIds.ts

Vis lenke til Cristin fra Landing Page om posten er importert derfra

NP-45609 Show link to cristin result from landing page

---

src/pages/messages/TasksPage.tsx
src/translations/nbTranslations.json
src/utils/dataTestIds.ts

Add filter for my NVI results

---

src/api/apiPaths.ts
src/api/scientificIndexApi.ts
src/pages/registration/RegistrationForm.tsx
src/translations/nbTranslations.json

Np 45461 warning for editing nvi result

---

src/api/cristinApi.ts
src/pages/dashboard/HomePage.tsx
src/pages/search/SearchPage.tsx
src/pages/search/person_search/PersonFacetsFilter.tsx
src/pages/search/person_search/PersonSearch.tsx

Noen endringer/forenklinger basert på jobb for prosjektfasetter: https://github.com/BIBSYSDEV/NVA-Frontend/pull/4802

NP-45279 Some minor refactoring of person facets

---

src/pages/basic_data/BasicDataPage.tsx
src/pages/basic_data/app_admin/central_import/CentralImportPage.tsx

NP-45673 Add free text search for import candidates

---

src/api/apiPaths.ts
src/api/cristinApi.ts
src/pages/dashboard/HomePage.tsx
src/pages/search/SearchPage.tsx
src/pages/search/project_search/ProjectFacetsFilter.tsx
src/pages/search/project_search/ProjectSearch.tsx
src/translations/nbTranslations.json
src/types/common.types.ts
src/types/project.types.ts
src/types/user.types.ts
src/utils/dataTestIds.ts

Avhenger av https://github.com/BIBSYSDEV/nva-cristin-service/pull/335
Egen PR for fasetter på kategori, funding source, og participants, da de trenger litt mer tilpasninger i selve søket først

Np 45281 project facets

---

src/pages/basic_data/app_admin/central_import/CentralImportDuplicateSearch.tsx
src/pages/basic_data/app_admin/central_import/DuplicateSearchFilterForm.tsx
src/types/importCandidate.types.ts

Videreføring av https://github.com/BIBSYSDEV/nva-publication-api/pull/1399
Skal virker etter neste reindeksering av importkandidater

NP-45682 Prefill ISSN values

---

src/pages/registration/FilesAndLicensePanel.tsx
src/utils/registration-helpers.ts

NB! backend skal følge opp dette slik at det blir støtte for å endre på alle felter. Per nå er det bare lagt til rette for det i frontend, men verdiene vil ikke gjenspeiles når man trykker importer

Np 45683 allow importer to edit files

---

src/pages/basic_data/app_admin/central_import/CentralImportResultItem.tsx
src/types/importCandidate.types.ts
src/utils/general-helpers.ts
src/utils/testfiles/mockImportCandidate.ts

NP-45687 Show age of import candidate

---

src/components/ConfirmMessageDialog.tsx
src/pages/basic_data/app_admin/central_import/CentralImportDuplicationCheckPage.tsx
src/types/importCandidate.types.ts

Meldingen som sendes vil ikke vises før den er indeksert i kandidatsøket. Lager en egen PR som benytter kandidat fra databasen i stedet, slik at vi unngår å vise utdatert data her. Ikke 100% sikker på at vi ønsker det, men vil sjekke det ut.

NP-45694 Add comment when denying import candidate

---

src/api/fileApi.ts
src/pages/public_registration/public_files/FileRow.tsx
src/pages/registration/FilesAndLicensePanel.tsx
src/pages/registration/files_and_license_tab/FilesTableRow.tsx
src/translations/nbTranslations.json
src/utils/registration-helpers.ts

Np 17982 show uploaded file from wizard

---

src/api/searchApi.ts
src/components/SortSelector.tsx
src/pages/basic_data/BasicDataPage.tsx
src/pages/basic_data/app_admin/central_import/CentralImportDuplicationCheckPage.tsx
src/pages/basic_data/app_admin/central_import/CentralImportPage.tsx
src/translations/nbTranslations.json

noen problemer hvor søket ser ut til å sortere litt ulikt hver gang, men ser ikke noen annen forklaring enn at det er noe trøbbel med søket der.
Kommer til å lage egen PR for at resultatsøket på forsiden skal bruke samme komponent etterpå

Np 45707 sort import candidates

---

src/pages/basic_data/app_admin/central_import/CentralImportCandidateMerge.tsx
src/pages/basic_data/app_admin/central_import/CompareFields.tsx
src/pages/basic_data/app_admin/central_import/CompareJournalFields.tsx
src/translations/nbTranslations.json

Np 45695 add fields merge import candidate

---

src/layout/header/Header.tsx
src/layout/header/Menu.tsx

Oppdater hvilke elementer som vises for ulike skjermstørrelser, og hvordan de er plassert

Np 45731 header on small screens

---

src/utils/hooks/useAuthentication.ts

https://docs.amplify.aws/react/prev/build-a-backend/auth/enable-sign-up/#sign-out

NP-45777 Revoke tokens on sign out

---

src/pages/registration/resource_type_tab/sub_type_forms/DegreeForm.tsx

ISBN field is removed for Bachelor and Master

removed isbn field for bachelor and master degree

---

amplify.yml
public/robots.txt
robots/dev-robots.txt
robots/main-robots.txt

Indekser prod, men ikke andre miljø

Np 2253 robots.txt for test environments

---

src/pages/search/advanced_search/OrganizationFilters.tsx
src/translations/nbTranslations.json

Bruk placeholder i stedet for label

NP-45795 Omit label on unit search field

---

src/pages/public_registration/PublicRegistrationContent.tsx
src/pages/registration/resource_type_tab/sub_type_forms/research_data_types/DataManagementPlanForm.tsx
src/pages/registration/resource_type_tab/sub_type_forms/research_data_types/DatasetForm.tsx
src/types/publication_types/researchDataRegistration.types.ts
src/utils/registration-helpers.ts

Kjapp hot-fix for å løse datamodellendringer som har blitt rullet ut i test

Update related model for DMP and Dataset (staging)

---

src/pages/search/registration_search/RegistrationSearchBar.tsx

Nullstill søk når bruker trykker på logo eller søket i header

NP-45753 Reset search when user go to search page again

---

src/App.tsx
src/components/RegistrationList.tsx
src/pages/search/SearchPage.tsx
src/pages/search/advanced_search/AdvancesSearchPage.tsx
src/pages/search/advanced_search/CategoryFilterDialog.tsx
src/pages/search/advanced_search/OrganizationFilters.tsx
src/pages/search/registration_search/RegistrationSearchResults.tsx

Np 45795 adjust advanced search styling

---

src/components/RegistrationList.tsx
src/pages/public_registration/PublicRegistration.tsx

Tillat å gå tilbake til søket etter å ha åpnet et søketreff
En del problemer med responsiviteten til denne siden. Var ikke helt rett frem å fikse alt, så lager ny bug på det siden det var der fra før: https://unit.atlassian.net/browse/NP-45926

Np 45830 browse search results

---

src/pages/public_registration/public_files/FileRow.tsx
src/pages/public_registration/public_files/FilesLandingPageAccordion.tsx
src/pages/registration/FilesAndLicensePanel.tsx
src/pages/registration/files_and_license_tab/DownloadFileButton.tsx
src/pages/registration/files_and_license_tab/FilesTableRow.tsx
src/pages/registration/files_and_license_tab/UnpublishableFileRow.tsx

Aldri vis ikke-publiserbare filer på landing page. La eier/curator se fil fra wizard.

Np 45939 omit unpublishable files from landing page

---

src/api/searchApi.ts
src/pages/public_registration/PublicRegistrationContent.tsx
src/pages/registration/resource_type_tab/sub_type_forms/research_data_types/DataManagementPlanForm.tsx
src/pages/registration/resource_type_tab/sub_type_forms/research_data_types/DatasetForm.tsx

Ref https://sikt-no.slack.com/archives/CN005AQCE/p1704886423793079?thread_ts=1704881033.221819&cid=CN005AQCE

Cancel result search request on unmount

---

src/pages/search/advanced_search/AdvancedSearchPage.tsx
src/pages/search/advanced_search/OrganizationFilters.tsx

Bruk `topLevelOrganization` i stedet for `unit` når man velger institusjon

NP-45794 Use topLevelOrganization for institution search

---

src/pages/public_registration/action_accordions/PublishingAccordion.tsx
src/pages/registration/ErrorList.tsx

Håndter en enkelt vranglås for ticket-statuser. Merk at det fortsatt er en del grums her, siden vi bare tar hensyn til den siste ticketen

Np 45959 update publishing action panel

---

src/pages/public_registration/PublicRegistrationContributors.tsx
src/pages/registration/contributors_tab/ContributorIndicator.tsx
src/pages/registration/contributors_tab/Contributors.tsx
src/pages/registration/contributors_tab/components/AffiliationsCell.tsx
src/types/contributor.types.ts
src/utils/institutions-helpers.ts
src/utils/nviHelpers.ts
src/utils/testfiles/mockRegistration.ts

Håndter `UnconfirmedOrganization` på bidragsytere

NP-46010 Handle unconfirmed affiliations

---

src/api/searchApi.ts
src/pages/dashboard/HomePage.tsx

Dette vil forhåpentligvis speede opp søket i flere tilfeller. Bare forsiden hvor vi trenger aggregeringer atm

NP-46033 Specify when we want to include aggregations in search response

---

src/api/cristinApi.ts
src/pages/dashboard/HomePage.tsx
src/pages/projects/form/RelatedProjectsField.tsx
src/pages/registration/description_tab/projects_field/ProjectsField.tsx
src/pages/search/SearchPage.tsx
src/translations/nbTranslations.json

Tidligere søkte vi bare på prosjekttittel. Nå søker vi på tittel, prosjekt-ID, deltaker, og GrantID.

NP-45852 Search for more properties on cristin project

---

src/pages/messages/components/NviCandidateListItem.tsx
src/types/nvi.types.ts

Pass på at endringer har tredd i kraft i prod før merge (klart fra kl 10, 23.01.24)

NP-46047 Update nvi model for approval

---

src/pages/basic_data/institution_admin/person_register/PersonRegisterPage.tsx
src/pages/editor/EditorCurators.tsx

Legg til søkefilter for kuratorer, som har irritert meg en stund at mangler

NP-45912 Add name search for curators

---

src/layout/header/Header.tsx

Når anonym bruker åpner appen ble de bli møtt med feilmelding pga manglende nøkkel til react-query

NP-46161 Avoid fetching institution when id is not present

---

src/api/cristinApi.ts
src/pages/dashboard/HomePage.tsx
src/pages/search/CristinSearchPagination.tsx
src/translations/nbTranslations.json

- Add sorting by name above result lists for person and project search

NP-46072 Add sorting by name to project and person search

---

src/pages/basic_data/institution_admin/AddEmployeePage.tsx
src/pages/basic_data/institution_admin/edit_user/TasksFormSection.tsx
src/pages/basic_data/institution_admin/edit_user/UserFormDialog.tsx
src/translations/nbTranslations.json

Legg inn støtte for å gi roller til studentopppgave igjen, etter at det ble glemt bort ifbm endringer rundt ansvarsområde

Np 46193 add roles for degree

---

src/pages/basic_data/app_admin/UpsertNviPeriodDialog.tsx
src/pages/messages/components/NviCandidatePage.tsx
src/types/nvi.types.ts
src/utils/testfiles/mockNviCandidate.ts

Endinger for typer rundt NVI rapportert av @truhacevkir

Update NVI models

---

src/pages/messages/components/DoiRequestMessagesColumn.tsx
src/pages/messages/components/PublishingRequestMessagesColumn.tsx
src/pages/public_registration/ActionPanelContent.tsx
src/pages/public_registration/action_accordions/CompletedPublishingRequestStatusBox.tsx
src/pages/public_registration/action_accordions/PublishingAccordion.tsx
src/translations/nbTranslations.json

Denne oppgaven er en forutsetning for de andre oppgavene for publiseringsflyt: https://unit.atlassian.net/browse/NP-46180
- Forenkling av meldinger som vises på Oppgaver (fokuser bare på hva som _skal_ gjøres)
- List opp alle godkjenninger i publishing accordion

NP-46180 Handle multiple publishing requests

---

src/api/searchApi.ts
src/pages/dashboard/HomePage.tsx
src/pages/search/registration_search/RegistrationSearchBar.tsx
src/pages/search/registration_search/filters/AdvancedSearchRow.tsx
src/translations/nbTranslations.json
src/utils/searchHelpers.ts

Add TilskuddsID (fundingIdentifier) as filter as well

NP-46204 Add course to search filters

---

src/utils/registration-helpers.ts

Henger litt sammen med tilgangskontroll-jobben som pågår. Hvilke typer som skal ha ekstra beskyttelse bør ligge bare en plass

Use single array of types that should be extra protected

---

src/api/searchApi.ts
src/pages/dashboard/HomePage.tsx
src/pages/search/registration_search/RegistrationSearchBar.tsx
src/pages/search/registration_search/filters/AdvancedSearchRow.tsx
src/translations/nbTranslations.json
src/utils/searchHelpers.ts

- Renaming Tilskudds-ID as well

NP-46213 Add search filter for cristin id

---

package-lock.json
package.json

Rull tilbake versjoner for uppy, da de førte til noen warnings i konsollen

Revert uppy bumping

---

src/api/apiPaths.ts
src/api/searchApi.ts
src/components/SelectableButton.tsx
src/pages/messages/TasksPage.tsx
src/types/publication_types/ticket.types.ts

Link to Jira issue: https://unit.atlassian.net/browse/NP-45807
Vis varsel for tickets. Counter skal vises for i header også. Ser videre på det, men tenker å ta det i en egen [PR](https://github.com/BIBSYSDEV/NVA-Frontend/pull/5316).

NP-45807 Show ticket notifications

---

src/pages/messages/components/TicketList.tsx

NP-46334 Fix Grid styling for filter on my page

---

src/types/publication_types/ticket.types.ts

Remove NotApplicable from ticket status array

---

src/translations/nbTranslations.json

Update pagination text

---

src/api/searchApi.ts
src/translations/nbTranslations.json

Link to Jira issue: https://unit.atlassian.net/browse/NP-46415
Første PR for dette inneholdt ikke alle parametre som var ønsket: https://github.com/BIBSYSDEV/NVA-Frontend/pull/5336

NP-46415 Add more fields to query search

---

src/layout/header/Header.tsx

Update design on Header.
Link to Jira issue:
https://unit.atlassian.net/browse/NP-45701

NP-45701 Update header

---

src/pages/basic_data/BasicDataPage.tsx
src/pages/editor/EditorPage.tsx

Update the icon on left side menu to reflect the icon in header for customer
Link to Jira issue:
N/A

Update customer icon on editor and basic data

---

src/components/DialoguesWithoutCuratorButton.tsx
src/layout/header/Header.tsx
src/pages/messages/TasksPage.tsx
src/types/publication_types/ticket.types.ts

Link to Jira issue: https://unit.atlassian.net/browse/NP-45807
Oppdater aggregeringer av Oppgaverfasetter etter API-endring

NP-45807 Update ticket aggregations

---

src/api/cristinApi.ts
src/components/AreaOfResponsibiltySelector.tsx
src/components/TicketListDefaultValueWrapper.tsx
src/pages/messages/TasksPage.tsx
src/utils/hooks/useSetDefaultTicketSearchParams.ts
src/utils/institutions-helpers.ts

Link to Jira issue: https://unit.atlassian.net/browse/NP-46408

NP-46408 Add default filters for task page

---

src/pages/dashboard/HomePage.tsx

Link to Jira issue: https://unit.atlassian.net/browse/NP-46447

NP-46447 Flytt avansert søk opp til toppen av sidemeny

---

src/pages/registration/contributors_tab/AddContributorModal.tsx
src/pages/registration/contributors_tab/components/AddContributorForm.tsx
src/pages/registration/contributors_tab/components/AffiliationsCell.tsx
src/pages/registration/contributors_tab/components/ContributorRow.tsx
src/translations/nbTranslations.json

Link to Jira issue: https://unit.atlassian.net/browse/NP-46468

NP-46468 Update layout of affiliation buttons

---

src/components/CategorySelector.tsx
src/pages/editor/CategoriesWithFilesOverview.tsx
src/pages/editor/EditorPage.tsx
src/utils/urlPaths.ts

Link to Jira issue: https://unit.atlassian.net/browse/NP-46423

NP-46423 Read-only CategoriesWithFiles

---

src/pages/public_registration/DeletedPublicationInformation.tsx
src/pages/public_registration/RegistrationLandingPage.tsx
src/translations/nbTranslations.json

NP-46417-unpublish-adjustments

---

src/pages/registration/RegistrationFormActions.tsx
src/translations/nbTranslations.json

NP-46488-adjust-get-help-from-curator-button

---

src/layout/header/Logo.tsx

NP-46394-adjust-top-menu

---

src/layout/header/Header.tsx

Løst feil hvor notification badge i header ikke ble en link sånn som resten av knappen.
Løsningen ble å legge badge inni knappen i stedet, som foreslått her: https://github.com/BIBSYSDEV/NVA-Frontend/pull/5316#discussion_r1519997960

Ensure that also the notification badge is clackable

---

src/pages/registration/description_tab/RegistrationFunding.tsx

Fiks responsivitet for funding input i wizard.
Før
Etter 

Fix responsiveness of funding input

---

src/pages/editor/EditorPage.tsx
src/pages/editor/InstitutionSupport.tsx
src/translations/nbTranslations.json
src/utils/dataTestIds.ts
src/utils/urlPaths.ts

Created a new sub-page on editor page where a link to the institutions help center can be added.
Link to Jira issue: https://unit.atlassian.net/browse/NP-46451

NP-46451 Institution support

---

src/layout/header/Header.tsx
src/translations/nbTranslations.json

Added aria-label to header to fix a11y warning.

Fix header a11y warning

---

src/api/searchApi.ts

decreased export size

---

src/layout/header/Header.tsx

Set size of icons in header which are wrapped in a <Badge /> (this overwrited the default styling of the icon, making it 4px larger)

Fixed size of icons with badges

---

src/pages/basic_data/fields/PositionField.tsx

Link to Jira issue: [NP-46493](https://unit.atlassian.net/browse/NP-46493)
Sort the employment dropdown in edit mode in person-register.
[NP-46493]: https://unit.atlassian.net/browse/NP-46493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

NP-46493 Sort employments dropdown in edit person (register)

---

src/pages/basic_data/institution_admin/AddAffiliationSection.tsx

Added OrganizationRenderOption to the affiliation dropdown. on Add/Update person. AFAIK this is not applied to all relevant dropdowns.

Added org render option to add/update emplyment

---

src/components/SelectCustomerInstitutionDialog.tsx

Use verbose renderOption ( OrganizationRenderOption ) when selecting which customer to log in to.

NP-46532 Added verbode organization info in dropdown

---

src/pages/public_registration/ActionPanelContent.tsx
src/pages/public_registration/RegistrationLandingPage.tsx
src/pages/registration/FilesAndLicensePanel.tsx
src/utils/registration-helpers.ts

Link to Jira issue: https://unit.atlassian.net/browse/NP-46538
Bruk `allowedOperations` i stedet for frontend-logikk til å bestemme hva som skal vises av operasjoner i wizard.
Herk å verifisere at dette ikke knekker noe, men har ikke oppdaget noen feil selv enda. Tror dette er noe som er like greit å få testet så fort som mulig i reelle miljø, så må vi bare rette opp snarest om det fører itl noen feil vi ikka har oppdaget før. e2e-testene kan fange opp noe i dev også

Np 46538 remove deprecated role checks

---

src/pages/search/advanced_search/AdvancedSearchPage.tsx
src/pages/search/advanced_search/JournalFilter.tsx
src/pages/search/advanced_search/PublisherFilter.tsx
src/pages/search/advanced_search/SeriesFilter.tsx

Link to Jira issue: https://unit.atlassian.net/browse/NP-46545
Slå opp kanal i stedet for å prøve å søke opp basert på ID. Dette fører nå til en bug, eks: https://dev.nva.sikt.no/search?journal=801A0B10-2E0B-40AD-9786-3AAD9907ED84

Np 46545 fetch selected channel

---

src/pages/editor/curators/OrganizationCuratorRow.tsx
src/themes/mainTheme.ts

Link to Jira issue: https://unit.atlassian.net/browse/NP-46460
Oppdater ikon for manglende roller, sånn at de ikke ser klikkbare ut lenger.

NP-46460 Set color of missing roles

---

src/pages/public_registration/ActionPanel.tsx
src/pages/public_registration/LogPanel.tsx
src/translations/nbTranslations.json

Link to Jira issue: [NP-46187](https://unit.atlassian.net/browse/NP-46187)
Legger til et innslag i logglisten for når registreringen ble opprettet, og av hvem og hvilken institusjon denne personen har registrert på vegne av.
[NP-46187]: https://unit.atlassian.net/browse/NP-46187?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Np 46187 add log for registration created

---

src/pages/public_registration/ActionPanel.tsx
src/pages/public_registration/LogPanel.tsx
src/translations/nbTranslations.json
src/utils/dataTestIds.ts

Link to Jira issue: [NP-46187](https://unit.atlassian.net/browse/NP-46187)
Legger til faner på action panel på registreringer, slik at man får tilgang til en enkel logg.
[NP-46187]: https://unit.atlassian.net/browse/NP-46187?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

NP-46187 Add logg pane on results

---

src/pages/public_registration/LogPanel.tsx
src/translations/nbTranslations.json

Link to Jira issue: [NP-46187](https://unit.atlassian.net/browse/NP-46187)
Legger til log entries for dato registreringen sist ble endret, og innslag for avvisning av filer.
[NP-46187]: https://unit.atlassian.net/browse/NP-46187?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Np 46187 add last modifier log entry

---

src/pages/editor/RightsRetentionStrategySettings.tsx

Link to Jira issue: https://unit.atlassian.net/browse/NP-46582
Fixed a bug where hitting "save" would rewrite chnages done to publishing strategy

NP-46582 enable reinitialize on rrs form

---

src/components/SelectCustomerInstitutionDialog.tsx
src/layout/header/Menu.tsx
src/pages/editor/EditorInstitution.tsx

Link to Jira issue: https://unit.atlassian.net/browse/NP-45742
Oppdater ID- og access token etter bruker velger customer om det er flere gyldige verdier. Dette for å ha riktige verdier for customer, username, etc.

Np 45742 update token after customer selection

---

src/translations/nbTranslations.json
src/types/nvi.types.ts

Link to Jira issue: https://unit.atlassian.net/browse/NP-46585
Legg til støtte for ny NVI-status

NP-46585 Add New status for NVI candidate

---

src/components/RegistrationList.tsx
src/pages/my_registrations/MyRegistrationsList.tsx
src/types/registration.types.ts
src/utils/testfiles/mockMyRegistrations.ts

Link to Jira issue: [TODO](https://unit.atlassian.net/browse/NP-46266)
Added abstract to the list of publications on MyRegistrations (endpoint: publication/by-owner).
Also made the default bgColor of all RegistrationListItems white.

Np 46266 default result presentation

---

src/components/SelectCustomerInstitutionDialog.tsx

Link to Jira issue: https://unit.atlassian.net/browse/NP-45742
Reverter bug som ser ut til å være introdusert i https://github.com/BIBSYSDEV/NVA-Frontend/pull/5522.
Vi må nok se mer på denne oppgaven siden, for å finne en varig fiks på henting av nye token når bruker velger kunde _etter_ innlogging.

Remove error with refreshing access- and id token

---

src/api/roleApi.ts
src/pages/basic_data/app_admin/AddAdminDialog.tsx
src/pages/basic_data/institution_admin/AddEmployeePage.tsx
src/pages/basic_data/institution_admin/edit_user/UserFormDialog.tsx

Link to Jira issue: https://unit.atlassian.net/browse/NP-46591
Opprett NVA-User med Cristin-ID i stedet for NIN. Dette er første steg for å kunne tillate redaktør å opprette Users.

NP-46591 Create user with Cristin ID

---

src/api/roleApi.ts
src/pages/editor/curators/AddCuratorDialog.tsx
src/pages/editor/curators/AddCuratorForm.tsx

Link to Jira issue: https://unit.atlassian.net/browse/NP-46591
Tillat redaktør å opprette bruker om angipp person ikke har NVA-User fra før.

NP-46591 Allow creating new user as editor

---

src/components/AutocompleteTextField.tsx
src/pages/editor/curators/OrganizationCurators.tsx
src/pages/editor/curators/OrganizationCuratorsAccordion.tsx
src/translations/nbTranslations.json

Link to Jira issue: https://unit.atlassian.net/browse/NP-46590
Tillat brukere å søke opp en bestemt kurator, for å se denne kuratorens roller og ansvarsområder.

Np 46590 search for curator

---

src/pages/public_registration/action_accordions/SupportAccordion.tsx

Link to Jira issue: [NP-46541](https://unit.atlassian.net/browse/NP-46541)
Keep support ticket open by default until read by owner.
[NP-46541]: https://unit.atlassian.net/browse/NP-46541?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

NP-46541 Keep support ticket open until read by owner

---

CODEOWNERS

Legg til Nina som codeowner, sånn at hun automatisk settes som reviewer på PRs

Add new codeowner

---

CODEOWNERS
package-lock.json
package.json
src/api/roleApi.ts
src/api/searchApi.ts
src/components/AutocompleteTextField.tsx
src/components/CategorySearchFilter.tsx
src/pages/editor/curators/AddCuratorDialog.tsx
src/pages/editor/curators/AddCuratorForm.tsx
src/pages/editor/curators/OrganizationCurators.tsx
src/pages/editor/curators/OrganizationCuratorsAccordion.tsx
src/pages/messages/TasksPage.tsx
src/pages/messages/components/TicketDateIntervalFilter.tsx
src/pages/messages/components/TicketList.tsx
src/pages/my_page/MyPagePage.tsx
src/pages/public_registration/LogPanel.tsx
src/pages/public_registration/action_accordions/SupportAccordion.tsx
src/pages/registration/description_tab/DatePickerField.tsx
src/pages/registration/description_tab/RegistrationFunding.tsx
src/pages/search/PublicationYearIntervalFilter.tsx
src/pages/search/advanced_search/AdvancedSearchPage.tsx
src/pages/search/advanced_search/CategoryFilterDialog.tsx
src/pages/search/registration_search/filters/RegistrationFacetsFilter.tsx
src/translations/enTranslations.json
src/translations/nbTranslations.json
src/translations/nnTranslations.json
src/types/registration.types.ts
src/utils/dataTestIds.ts
src/utils/date-helpers.ts
src/utils/registration-helpers.ts

:rocket: Ny funksjonalitet :rocket:
- Nye filter for tickets:
- Støtte for å søke på opprettetelsesdato (NP-46263)
- Støtte for å søke på kategori (NP-46264)
- Mer funksjonalitet for kuratoroversikt:
- Støtte for å søke opp kurator, og se alle enheter som inngår i den brukerens ansvarsområde (NP-46590)
- Redaktør kan legge til en kurator som ikke har logget inn i NVA tidligere (NP-46591)
- Vis antall arkiverte filer i loggen for resultat (NP-46613)
:bug: Bugfiks :bug:
- Sørg for at brukerstøtte-feltet vises når den har en ulest melding (NP-46541)
- Unngå at filer-panelet krasjer når importør åpner en importkandidat (NP-46652)
- Løst feil hvor knapp for å oppgi årstall tok for mye plass (NP-46554)
- Løst feil hvor knapp for å fjerne finansiering tok for mye plass (NP-46609)

Update staging 26.04.24

---

src/pages/registration/files_and_license_tab/FilesTableRow.tsx
src/translations/nbTranslations.json
src/utils/dataTestIds.ts

Link to Jira issue: [NP-38975](https://unit.atlassian.net/browse/NP-38975)
Add older license versions to the dropdown menu, hidden by "...". 
[NP-38975]: https://unit.atlassian.net/browse/NP-38975?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

NP-38975 Add older license versions to dropdown

---

src/types/license.types.ts

Link to Jira issue: [NP-46679](https://unit.atlassian.net/browse/NP-46679)
Legger til versjon 2.5 for lisenser.
[NP-46679]: https://unit.atlassian.net/browse/NP-46679?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

NP-46679 Add license version 2.5

---

package-lock.json
package.json

Reverts BIBSYSDEV/NVA-Frontend#5585

Revert "Bump @mui/material from 5.15.15 to 5.15.16"

---

src/api/apiPaths.ts
src/api/searchApi.ts
src/pages/search/ExportResultsButton.tsx
src/utils/dataTestIds.ts

Link to Jira issue: https://unit.atlassian.net/browse/NP-46630
Using new endpoint for download of registrations.

NP-46630: Used new endpoint for export

---

src/pages/messages/TasksPage.tsx
src/pages/messages/components/TicketList.tsx

Link to Jira issue: https://unit.atlassian.net/browse/NP-46709
Added category filter to TasksPage (read. removed the check to see if the user was on MyPage)

NP-46709 Added category filter to TasksPage

---

src/pages/registration/RegistrationFormActions.tsx

Link to Jira issue: [Leave page vs Save in wizard trouble](https://unit.atlassian.net/browse/NP-46462)
Fixed bug where user was asked to confirm if they wanted to leave the registration wizard, even after having just saved.

Fixed leaving-bug in registration wizard

---

src/pages/public_registration/action_accordions/PublishingAccordion.tsx
src/pages/registration/RegistrationForm.tsx
src/utils/formik-helpers.ts

Link to Jira [Validation bug when navigating between wizard and landing page](https://unit.atlassian.net/browse/NP-46502)
Fixed bug where the errors in the accordion to the right on the registration landing page would reflect errors in the registration, even when all errors were resolved.

NP-46502: Fixed bug with lag in validation update in registration wizard

---

src/pages/my_page/user_profile/MyFieldAndBackground.tsx
src/pages/research_profile/ResearchProfile.tsx
src/types/common.types.ts
src/types/keywords.types.ts

Update the data-model for Keywords to reflect incoming changes, as well as add type for Country (not in use yet).
Link to changes in data-model: https://unit.atlassian.net/browse/NP-46412
Not able to test this, but the changes are not too comprehensive.

Updated data-model for Keywords and added type for Country

---

documentation/deployment/deployment.md

Updated the deploy documentation

---

src/api/fileApi.ts
src/pages/registration/files_and_license_tab/DownloadFileButton.tsx

Link to Jira issue: https://unit.atlassian.net/browse/NP-46149
Håndter nedlasting av filer på en importkandidat. Filer på importkandidater og registreringer må lastes ned fra ulike endepunkter.

Np 46149 import candidate file preview

---

src/pages/basic_data/app_admin/central_import/CentralImportCandidateMerge.tsx
src/pages/basic_data/app_admin/central_import/CompareDoiField.tsx
src/pages/basic_data/app_admin/central_import/CompareFields.tsx

Link to Jira issue: https://unit.atlassian.net/browse/NP-46671
Vis åpne-knapp for DOI når importør merger en importkandidat med resultat.

Np 46671 import candidate merge link

---

src/pages/registration/resource_type_tab/sub_type_forms/ChapterForm.tsx
src/utils/validation/registration/registrationValidation.ts

Link to Jira issue: [NP-46711](https://unit.atlassian.net/browse/NP-46711)
Legger til NPI fagfelt i registreringswizard for Kapittel, likt som for bok.
[NP-46711]: https://unit.atlassian.net/browse/NP-46711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

NP-46711 Add NPI to Chapter

---

src/utils/registration-helpers.ts

Link to Jira issue: https://unit.atlassian.net/browse/NP-46701
Legg til redatør som rollle for flere kategorier.

NP-46701 Add editor role for more categories

---

src/pages/basic_data/app_admin/central_import/CentralImportCandidateMerge.tsx
src/pages/basic_data/app_admin/central_import/CompareDoiField.tsx

Link to Jira issue: https://unit.atlassian.net/browse/NP-46676
Vis DOI, og tillat å legge inn DOI som `AssociatedLink` om posten ikke allerede har en DOI.

NP-46676 Show DOI from existing result

---

src/pages/registration/resource_type_tab/components/JournalFormDialog.tsx
src/pages/registration/resource_type_tab/components/PublisherFormDialog.tsx
src/translations/nbTranslations.json

Link to Jira issue: https://unit.atlassian.net/browse/NP-46673
Vis lenke til portal.issn.org for at brukere skal kunne søke opp kanalen de ønsker å opprette hos Kanalregisteret

NP-46673 Add link to ISSN portal to find data about channel

---

src/components/institution/AffiliationHierarchy.tsx
src/components/institution/OrganizationTree.tsx
src/components/institution/SelectInstitutionForm.tsx
src/pages/registration/contributors_tab/components/AffiliationsCell.tsx
src/pages/research_profile/ResearchProfile.tsx
src/pages/search/advanced_search/OrganizationFilters.tsx

Link to Jira issue: https://unit.atlassian.net/browse/NP-46674
Vis valgt org med ny visning for bidragsytere.

Np 46674 show country code for contributor affiliations

---

src/api/apiPaths.ts

Oppdater API-path for importkandidater

Update import-candidate API path

---

src/api/searchApi.ts
src/pages/search/registration_search/RegistrationSearch.tsx
src/translations/nbTranslations.json

Link to Jira issue: https://unit.atlassian.net/browse/NP-46852
Legg til mulighet for å søke på relevans for resultat. I første omgang skal dette være valgbart, og ikke valgt som standard, sånn at vi får testet det litt i praksis først.

NP-46852 Add relevance sort param to result search

---

src/pages/registration/contributors_tab/components/ContributorRow.tsx
src/translations/nbTranslations.json

Link to Jira [Top-align contributor column](https://unit.atlassian.net/browse/NP-46796)
Move the alignment of the table rows from center to top. Also filled in the role field and added label to make it more similar to design, and match the number field. Also fixed alignment of the icons.
Before:
After:

Top-align contributor

---

src/pages/basic_data/app_admin/central_import/CompareJournalFields.tsx

Link to Jira issue: https://unit.atlassian.net/browse/NP-46932
Løs feil for overskriving av sidetall for importkandidat

NP-46932 Fix merging of pages from for import candidate

---

src/pages/basic_data/institution_admin/AddAffiliationSection.tsx
src/pages/my_page/user_profile/MyProfile.tsx
src/translations/nbTranslations.json

Minor text changes

---

src/translations/nbTranslations.json

Mindre tekstendringer basert på tilbakemeldinger fra oversetter.

Minor translation changes

---

src/types/publication_types/mediaContributionRegistration.types.ts

Konseptet `peerReviewed` ble tatt vekk for lenge siden

Remove nonexistant property

---

src/components/RegistrationList.tsx
src/pages/public_registration/PublicRegistrationContributors.tsx
src/utils/registration-helpers.ts

Link to Jira issue: https://unit.atlassian.net/browse/NP-46896
Vis bare bidragsytere med fremhevede roller blant søketreff.

Np 46896 show only primary roles on search hits

---

src/pages/registration/resource_type_tab/sub_type_forms/degree_types/PhdForm.tsx
src/pages/registration/resource_type_tab/sub_type_forms/research_data_types/RelatedResourceRow.tsx
src/types/registration.types.ts
src/utils/dataTestIds.ts

Link to Jira issue: https://unit.atlassian.net/browse/NP-47042
Støtte for å legge til et nytt resultat med fritkest for PhD. Skulle gjerne hatt noen flere ting her, bl.a. validering, men ser det kommer til å bli en god del jobb, så lar det bare være siden det heller ikke er der i dag. Dette er bare valgfrie felter også, så det er ingen krise om noen legger til et tomt felt.
Har dog gjort noen mindre forbedringer på layout, ved å unngå at det blir for mye spacing.

NP-47042 Allow adding new uncomfirmed document to PhD

---

src/components/SearchForm.tsx
src/pages/search/SearchTextField.tsx
src/pages/search/advanced_search/AdvancedSearchPage.tsx
src/pages/search/advanced_search/OrganizationFilters.tsx
src/translations/nbTranslations.json
src/utils/dataTestIds.ts

Link to Jira issue: https://unit.atlassian.net/browse/NP-46958
Legger til filter for emnekode i avansert søk.
Har også gjort noen mindre forbedringer på responsivitet. Ser vi har en god del mer vi skulle gjort her, spesielt siden dette er åpent for absolutt alle. Men fant fort ut at det ikke var bare-bare, så har bare gjort noen quick-wins.

NP-46958 Add filter for course code

---

src/pages/registration/FileList.tsx
src/utils/registration-helpers.ts

Link to Jira issue: https://unit.atlassian.net/browse/NP-46885
Lås ned Lisensiatavhandling på samme måte som alle andre studentoppgaver.

NP-46885 Lock down licenciate category like other degrees

---

src/pages/messages/components/DeleteIconButton.tsx
src/pages/registration/FileList.tsx
src/pages/registration/FilesAndLicensePanel.tsx
src/pages/registration/files_and_license_tab/DownloadFileButton.tsx
src/pages/registration/files_and_license_tab/FilesTableRow.tsx
src/translations/nbTranslations.json
src/utils/dataTestIds.ts

Link to Jira: [NP-47068](https://unit.atlassian.net/browse/NP-47068)
Implement new design for file table in wizard.
Before:
After:
As you can see, the differences aren't too big, mostly it was making the name-field into a collection of more information (file-size, download, delete) resulting in fewer columns.
These aren't centered across tables yet, but I will do that in a later PR including mobile view. This should be considered independently though (could we release it like this).
[NP-47068]: …

New design for file table

---

src/components/RegistrationList.tsx
src/pages/public_registration/PublicRegistrationContent.tsx
src/pages/public_registration/action_accordions/SupportAccordion.tsx
src/translations/nbTranslations.json

NP-47170-helper-text

---

src/layout/header/Header.tsx
src/pages/my_page/MyPagePage.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-47089
Send bruker direkte til visning over uleste meldinger om man går på min side og man har en varsel (for ulest melding).

Np 47089 open my page dialogue when notifications

---

src/pages/messages/components/TicketList.tsx

Liten design-fiks.
Før:
Etter:

Fix grid item size of date interval fields

---

src/pages/registration/FileList.tsx
src/pages/registration/files_and_license_tab/FilesTableRow.tsx
src/utils/registration-helpers.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-47056
- Vis fil-versjon for alle tidsskrift-, bok- og kapittelkategorier
- Vis RRS-felter bare for Vitenskapelig artikkel og Vitenskapelig oversiktsartikkel

Np 47056 accepted file verions on more categories

---

src/components/institution/SelectInstitutionForm.tsx

Fix inconsistant gaps

---

src/pages/search/advanced_search/AdvancedSearchPage.tsx
src/pages/search/advanced_search/LanguageFilter.tsx

Fix weird label for language selector

---

.eslintrc.cjs
src/pages/basic_data/institution_admin/FindPersonPanel.tsx
src/pages/editor/PublishingStrategyOverview.tsx
src/pages/messages/components/NviCandidateActions.tsx
src/pages/public_registration/LogPanel.tsx
src/pages/public_registration/action_accordions/DeletePublication.tsx
src/pages/public_registration/action_accordions/DuplicateWarningDialog.tsx
src/pages/public_registration/action_accordions/PublishingAccordion.tsx
src/pages/public_registration/public_links/ShowRelatedDocuments.tsx
src/pages/registration/FileList.tsx
src/pages/registration/SupportModalContent.tsx
src/pages/registration/contributors_tab/components/AddAffiliationModal.tsx
src/pages/registration/contributors_tab/components/EditAffiliationModal.tsx
src/pages/registration/description_tab/RegistrationFunding.tsx
src/pages/registration/description_tab/projects_field/ProjectsField.tsx
src/pages/registration/resource_type_tab/components/JournalField.tsx
src/pages/registration/resource_type_tab/components/PublisherField.tsx
src/pages/registration/resource_type_tab/components/SearchContainerField.tsx
src/pages/registration/resource_type_tab/components/SeriesField.tsx

Alle endringer her er for å fikse error som oppstår når vi tar hensyn til eslint regel for `react/jsx-key`
https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-key.md

Resolve eslint errors for jsx-key

---

.eslintrc.cjs
src/pages/my_page/user_profile/UserOrcidHelperModal.tsx

Legg children inn som faktisk children i stedet for å sende ned som vanlig prop.
```diff
- <MyComponent children={children} />
+ <MyComponent>{children}</MyComponent>
```
Dette for å tilfredsstille eslint-regelen [no-children-prop ](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/no-children-prop.md)

Use actual children instead of sending as props

---

package-lock.json
package.json
src/pages/registration/description_tab/projects_field/ProjectContributorRow.tsx
src/pages/registration/resource_type_tab/components/JournalField.tsx
src/pages/registration/resource_type_tab/components/PublisherField.tsx
src/pages/registration/resource_type_tab/components/SearchContainerField.tsx
src/pages/registration/resource_type_tab/components/SeriesField.tsx
src/pages/research_profile/ResearchProfile.tsx

Fixed issues with new prettier ternary formatting

Update prettier to 3.3.3

---

src/components/Log/RegistrationLog.tsx

Sentrerer teksten "Metadata sist oppdatert: 02.08.2024" i toppen av registreringsloggen.

NP-47242 Center metadata modified text at the top of the log

---

src/translations/nbTranslations.json

Liten justering etter innspill fra PO

Minor text change for publishing information

---

src/translations/nbTranslations.json

Bruk eksplisitt melding om hva som mangler

Update text for missing employment type or start date

---

src/translations/nbTranslations.json

Link to Jira issue: https://sikt.atlassian.net/browse/NP-47262

NP-47262 Update NVI text

---

src/pages/messages/components/NviCandidateActions.tsx
src/translations/nbTranslations.json

Link to Jira issue: https://sikt.atlassian.net/browse/NP-47261
Før:
Etter:

Np 47261 add nvi helper text

---

src/pages/reports/NviReports.tsx

Oppdater NVI-rapport til å inkludere data fra 2023: https://dev.nva.sikt.no/reports/nvi

Include NVI data from 2023 in NVI report

---

src/pages/my_page/user_profile/UserRoleAndHelp.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-47297
Før:
Etter:

NP-47297 Hide area of responsibility heading when redundant

---

src/components/ListPagination.tsx
src/components/ProjectSortSelector.tsx
src/pages/my_page/user_profile/MyProjectRegistrations.tsx
src/pages/search/project_search/ProjectSearch.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-47267
Legg til sortering av mine prosjektregistreringer

Add alphabetical sorting of project registrations

---

src/pages/public_registration/PublicPublicationContext.tsx
src/pages/registration/FilesAndLicensePanel.tsx

Fiks feil for link til valgt kanal, ref https://sikt-no.slack.com/archives/CPHGQRNAJ/p1723537877861549

Update channel link

---

src/types/project.types.ts
src/utils/formik-helpers/project-form-helpers.ts

Fjerner eksportering av verdier som aldri importeres

Remove unused exports

---

src/pages/public_registration/ChapterPublisherInfo.tsx
src/pages/public_registration/PublicPublicationContext.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-46837
Vis serie for boka/rapporten ett kapittel er en del av, i tillegg til utgiver som vises i dag.

NP-46837 Show series info for chapters

---

src/pages/public_registration/PublicPublicationContext.tsx
src/types/registration.types.ts
src/utils/registration-helpers.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-46891
Vis ISSN-verdier for unconfirmed jounrnal og series på landing page.

Np 46891 show issn for unconfirmed journal

---

src/pages/messages/components/NviCorrectionListNavigationAccordion.tsx

Fjern beta-tag for de rettelistene vi har

Remove correction list beta tag

---

src/api/hooks/useFetchUserQuery.ts
src/components/Log/LogActionActor.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-47334
Unngå oppslag på personer med ugyldig brukernavn. Endrer også til å vise "Ukjent" når vi ikke vet hvem som har gjort en action som førte til et logginnslag.
Før:
Etter:

Avoid trying to fetch user with invalid username

---

src/api/hooks/useDuplicateRegistrationSearch.ts
src/pages/public_registration/action_accordions/PublishingAccordion.tsx

Unngå at publiser-knapp får evig loading.
Eksempel: https://dev.nva.sikt.no/registration/0190737a005e-af3d7ac7-3955-4408-b476-903582e142ea/
Bug introdusert her: https://github.com/BIBSYSDEV/NVA-Frontend/pull/6058

Avoid infinite loading of publish button

---

src/api/searchApi.ts
src/components/HrcsActivityAutocompleteOption.tsx
src/pages/registration/description_tab/vocabularies/HrcsActivityInput.tsx
src/pages/search/advanced_search/AdvancedSearchPage.tsx
src/pages/search/advanced_search/VocabularSearchField.tsx
src/translations/nbTranslations.json
src/utils/dataTestIds.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-47269
Gikk fort og gæli denne, men det som er her nå ser ut til å virke fint iaf. Foreløpig er dette en komponent, og ikke delt i to som snakket om på standup. Dette for å spare tid og kompleksistet, ved å duplisere/gjenbruke mye av dette. Sparer også litt skjermplass på avansewrr søkeside

Np 47269 vocabulary search

---

src/translations/nbTranslations.json

Link to Jira issue: [NP-47361](https://sikt.atlassian.net/browse/NP-47361)
Changed tooltip in category view
Old: 
[NP-47361]: https://sikt.atlassian.net/browse/NP-47361?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Changed tooltip

---

src/pages/public_registration/PublicPublicationContext.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-47364
Legg til navn på felt før navnet på arrangement
Før:
Etter:

Add label for event name for presentation types

---

src/context/NviCandidateContext.ts
src/pages/registration/RegistrationForm.tsx
src/pages/registration/description_tab/DatePickerField.tsx
src/pages/registration/resource_type_tab/SelectRegistrationTypeField.tsx
src/pages/registration/resource_type_tab/components/JournalField.tsx
src/pages/registration/resource_type_tab/components/PublisherField.tsx
src/pages/registration/resource_type_tab/components/SearchContainerField.tsx
src/pages/registration/resource_type_tab/components/SeriesField.tsx
src/utils/nviHelpers.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-47065
Quick-fix av kritisk feil i pågående testing. Vil komme mer jobb her i nær fremtid.
Det som gjenstår til senere PR(s):
- Vis informasjon til bruker om hvorfor feltene er disabled
- Disable alle felter for bidragsytere

Np 47065 block fields for approved nvi candidate

---

package-lock.json
package.json
src/components/RegistrationErrorActions.tsx
src/context/NviCandidateContext.ts
src/pages/projects/form/ProjectContributors.tsx
src/pages/public_registration/action_accordions/PublishingAccordion.tsx
src/pages/public_registration/action_accordions/SupportAccordion.tsx
src/pages/registration/RegistrationForm.tsx
src/pages/registration/description_tab/DatePickerField.tsx
src/pages/registration/resource_type_tab/SelectRegistrationTypeField.tsx
src/pages/registration/resource_type_tab/components/JournalField.tsx
src/pages/registration/resource_type_tab/components/PublisherField.tsx
src/pages/registration/resource_type_tab/components/SearchContainerField.tsx
src/pages/registration/resource_type_tab/components/SeriesField.tsx
src/translations/nbTranslations.json
src/utils/nviHelpers.ts

Oppdater test med ny funksjonalitet for testing:
- Fiks bug i prosjekt form
- Endre tekst når publisert resultat har valideringsfeil
- Lås de enkleste NVI-kritiske feltene når alle institusjoner har godkjent kandidaten

Update staging 20.08.24 (2)

---

src/components/RegistrationErrorActions.tsx
src/components/RegistrationList.tsx
src/components/RouteLeavingGuard.tsx
src/pages/basic_data/app_admin/central_import/CentralImportCandidateMerge.tsx
src/pages/public_registration/PublicRegistrationContent.tsx
src/pages/public_registration/action_accordions/PublishingAccordion.tsx
src/pages/public_registration/public_files/FilesLandingPageAccordion.tsx
src/pages/registration/RegistrationFormActions.tsx
src/pages/registration/new_registration/LinkRegistration.tsx
src/pages/registration/new_registration/StartEmptyRegistration.tsx
src/pages/registration/new_registration/UploadRegistration.tsx
src/types/locationState.types.ts
src/utils/dataTestIds.ts
src/utils/urlPaths.ts

Reverts BIBSYSDEV/NVA-Frontend#6060

Revert "Np 47279 k50 add cancel button in registration wizard"

---

src/components/OrganizationNameAndIcon.tsx
src/types/associatedArtifact.types.ts
src/utils/log/importEntryGenerator.ts
src/utils/log/logFactory.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-47331
- Utvid toleransen på hvilke timestamps som skal håndteres som samtidig, fra 1sek til 10sek (relatert til https://github.com/BIBSYSDEV/NVA-Frontend/pull/6115)
- Sikre håndtering  (Relatert til https://github.com/BIBSYSDEV/NVA-Frontend/pull/6114)
Før (høyremeny utvidet seg så mye den måtte):
Etter:

Np 47331 minor log fixes

---

src/utils/log/importEntryGenerator.ts

Vis rikitg header for importerte filer, ved å ta hensyn til flertall

Fix pluralization of imported files

---

src/pages/public_registration/ActionPanelContent.tsx
src/pages/public_registration/action_accordions/DoiRequestAccordion.tsx
src/pages/public_registration/action_accordions/SupportAccordion.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-46726
Vis siste DOI i stedet for den første. Forenkler også litt ved å bruke `.findLast()` i stedet for `.filter().pop()`.

NP-46726 Show last ticket for DOI and support

---

src/pages/messages/components/DoiRequestMessagesColumn.tsx
src/pages/messages/components/LastMessageBox.tsx
src/pages/messages/components/PublishingRequestMessagesColumn.tsx
src/pages/messages/components/SupportMessagesColumn.tsx
src/pages/messages/components/TicketListItem.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-47447
Vis siste melding lagt til på publisering- og DOI-forespørsel, på samme måte som support-henvendelse.

Np 47447 show last ticket message

---

src/pages/project/project_wizard/ProjectFormStepper.tsx
src/pages/projects/ProjectLandingPage.tsx
src/translations/nbTranslations.json

Link to Jira issue: [https://sikt.atlassian.net/browse/NP-47494](https://sikt.atlassian.net/browse/NP-47494)
Changed text from "Prosjektdeltakere" to "Medlemmer" i tabs view and landing page:

Changed text from "Prosjektdeltakere" to "Medlemmer"

---

src/pages/project/project_wizard/CreateProject.tsx
src/utils/dataTestIds.ts

Link to Jira issue: [https://sikt.atlassian.net/browse/NP-47492](https://sikt.atlassian.net/browse/NP-47492)
Added cancel-button to the new project-page

Added cancel-button to the new project-page

---

src/pages/messages/components/NviStatusPage.tsx

Flytt eksport av NVI-status til beta-tag siden dette ikker klart i test og prod i backend enda

NP-46984 Move NVI export to beta container

---

src/translations/nbTranslations.json
src/types/project.types.ts

Husk å ta vekk ubrukte oversettelser og exports fortløpende :)

Remove unused code

---

src/api/cristinApi.ts
src/api/hooks/useSearchForOrganizations.ts
src/components/institution/SelectInstitutionForm.tsx
src/pages/basic_data/app_admin/OrganizationSearchField.tsx
src/pages/search/advanced_search/OrganizationFilters.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-47523
Tillat bruker å hente flere treff ved søk etter organization.
Bygger videre på samme implementasjon som for kanalsøk introdusert her: https://github.com/BIBSYSDEV/NVA-Frontend/pull/5857

Np 47523 institution pagination

---

src/pages/public_registration/PublicGeneralContent.tsx
src/pages/registration/resource_type_tab/sub_type_forms/research_data_types/DatasetForm.tsx
src/types/publication_types/researchDataRegistration.types.ts
src/utils/validation/registration/referenceValidation.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-47342
Lagt til utgiver-felt for datasett

Np 47342 add publisher to dataset

---

src/api/searchApi.ts
src/components/CategorySearchFilter.tsx
src/components/CategorySelector.tsx
src/pages/messages/components/NviCorrectionList.tsx
src/pages/messages/components/NviCorrectionListNavigationAccordion.tsx
src/translations/nbTranslations.json
src/utils/dataTestIds.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-47570
Legger til to nye rettelister:

Np 47570 add more correction lists

---

src/pages/project/helpers/projectContributorHelpers.ts
src/pages/project/tests/mockObjects.ts
src/pages/project/tests/projectContributorHelpers.test.ts

Still no jira issue, just a testing initiative because of complex logic.

Implemented all the empty tests and fixed the bugs I found

---

src/pages/project/helpers/projectContributorHelpers.ts
src/pages/project/helpers/projectRoleHelpers.ts
src/pages/project/project_wizard/ProjectManager.tsx
src/pages/project/tests/mockObjects.ts
src/pages/project/tests/projectContributorHelpers.test.ts
src/pages/project/tests/projectRoleHelpers.test.ts
src/pages/projects/ProjectAddAffiliationModal.tsx
src/pages/projects/ProjectEditAffiliationModal.tsx
src/pages/projects/form/ContributorRow.tsx
src/pages/projects/form/ProjectParticipants.tsx

No Jira issue-just my own initiative to test code with too much logic.
This time testing:
* Remove project contributor
* Add, edit and remove affiliation

Third testing PR

---

src/pages/public_registration/PublicRegistrationContent.tsx
src/translations/nbTranslations.json

- Endre heading av relaterte resultater for PhD ([Jira](https://sikt.atlassian.net/browse/NP-47637))
- Oppdater tekst for sletting av avpublisert resultat ([Slacktråd](https://sikt-no.slack.com/archives/CPHGQRNAJ/p1726670622416479?thread_ts=1726645328.036299&cid=CPHGQRNAJ))
- Tydeliggjør footer-tekst for å be om støtte vie epost

Np 47637 text changes

---

src/components/CategorySearchFilter.tsx
src/pages/messages/components/TicketList.tsx

Fiks en label-feil introdusert her: https://github.com/BIBSYSDEV/NVA-Frontend/pull/6232
Før:
Etter:

Hide category selector heading for tasks and my page

---

src/pages/messages/components/NviCorrectionList.tsx
src/pages/messages/components/NviCorrectionListNavigationAccordion.tsx
src/translations/nbTranslations.json
src/utils/dataTestIds.ts

Rett opp feilstavelser av `Anthology`, ref: https://github.com/BIBSYSDEV/NVA-Frontend/pull/6299#discussion_r1776863392

Fix anthology typos

---

src/pages/messages/components/NviStatusTableRow.tsx

Fjern stygg glipp hardkodet loadingstatus introdusert her: https://github.com/BIBSYSDEV/NVA-Frontend/pull/6314

Remove hardcoded loading state

---

src/pages/projects/AddProjectContributorForm.tsx

Added beta-tag to add unidentified project contributor

Added beta-tag to add unidentified project contributor

---

src/pages/basic_data/app_admin/NviPeriodsPage.tsx
src/pages/basic_data/app_admin/central_import/CentralImportCandidateMerge.tsx
src/pages/basic_data/app_admin/central_import/CentralImportDuplicationCheckPage.tsx
src/pages/editor/EditorDoi.tsx
src/pages/editor/InstitutionSupport.tsx
src/pages/my_page/user_profile/MyFieldAndBackground.tsx
src/pages/my_page/user_profile/MyProfile.tsx
src/pages/my_page/user_profile/MyProjectRegistrations.tsx
src/pages/my_page/user_profile/MyProjects.tsx
src/pages/my_page/user_profile/MyResults.tsx
src/pages/my_page/user_profile/UserRoleAndHelp.tsx
src/translations/nbTranslations.json

Legg til page titles hvor de mangler fra før

Add page titles

---

src/pages/messages/TasksPage.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-47577
Rett opp en feil ved første implementasjon, da dette skal være tilgjengelig for alle kuratorer, ikke bare publiseringskurator.
Venter på en backendfiks før beta-tag kan fjernes for dette: https://sikt.atlassian.net/browse/NP-47737

NP-47577 Show portfolio for any curator

---

src/components/institution/AffiliationSkeleton.tsx
src/pages/basic_data/institution_admin/AddAffiliationSection.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-47774
- Filtrer enheter på "Legg til ansatt" basert på label for alle språk
- Merk: Dette _kan_ føre til noe annet rart, men har ikke oppdaget noen uheldige effekter. Her vil det bli rart hver gang, så vil uansett argumentere for at vi ikke kan ha det sånn det har vært før
- Løs feil hvor innholdet hopper veldig mye mens man venter på at navn på tilknytnigner skal vises:

Np 47774 filter unit names on all languages

---

src/pages/public_registration/ActionPanelContent.tsx
src/pages/public_registration/action_accordions/PublishingAccordion.tsx
src/pages/registration/RegistrationFormActions.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-47766
La ut branchen for testing her: https://np-47766-use-allowed-operations-for-ticket-creation.d1idrxv83qym4u.amplifyapp.com/
Bruk `allowedOperations` i ende større grad for å bestemme hva bruker har tilgang til å se. Dette burde løse mange av problemene med tickets fra ulike institusjoner.

Np 47766 use allowed operations for ticket creation

---

package-lock.json
package.json
src/pages/public_registration/ActionPanelContent.tsx
src/pages/public_registration/action_accordions/PublishingAccordion.tsx
src/pages/registration/RegistrationFormActions.tsx

Fiks tilgangskontroller for tickets

Update staging 08.10.24

---

src/api/registrationApi.ts
src/pages/public_registration/action_accordions/DoiRequestAccordion.tsx
src/pages/public_registration/action_accordions/SupportAccordion.tsx
src/pages/registration/SupportModalContent.tsx

Link to Jira issue: [https://sikt.atlassian.net/browse/NP-47771](https://sikt.atlassian.net/browse/NP-47771)
Use new API feature that lets us create and post ticket with message in one call instead of two. The call is backwards compatible so we don't have to make more changes than we need.
Fixed for:
* Support ticket
* Doi request

Sending message on ticket creation

---

package-lock.json
package.json
src/api/registrationApi.ts
src/pages/basic_data/app_admin/CustomerInstitutionInformationFromCristin.tsx
src/pages/project/helpers/projectContributorHelpers.ts
src/pages/project/helpers/projectRoleHelpers.ts
src/pages/project/project_wizard/ProjectContributorsForm.tsx
src/pages/project/project_wizard/ProjectManager.tsx
src/pages/project/tests/mockObjects.ts
src/pages/project/tests/projectContributorHelpers.test.ts
src/pages/project/tests/projectRoleHelpers.test.ts
src/pages/projects/AddProjectContributorForm.tsx
src/pages/projects/AddProjectContributorModal.tsx
src/pages/projects/ProjectAddAffiliationModal.tsx
src/pages/projects/ProjectContributors.tsx
src/pages/projects/ProjectEditAffiliationModal.tsx
src/pages/projects/ProjectOrganizationBox.tsx
src/pages/projects/form/ContributorRow.tsx
src/pages/projects/form/ProjectParticipants.tsx
src/pages/public_registration/action_accordions/DoiRequestAccordion.tsx
src/pages/public_registration/action_accordions/PublishingAccordion.tsx
src/pages/public_registration/action_accordions/SupportAccordion.tsx
src/pages/registration/SupportModalContent.tsx
src/pages/registration/description_tab/projects_field/projectHelpers.ts
src/translations/nbTranslations.json
src/types/project.types.ts

Fiks siste kjente feil rundt tilgangskontroll av tickets, og legg inn støtte for lokal prosjektleder

Update staging 09.10.24

---

src/pages/editor/EditorInstitution.tsx
src/pages/editor/InstitutionSupport.tsx
src/types/customerInstitution.types.ts

Updated field name of customer service center uri to relfect data-model

Updated field name of customer service center uri

---

src/matomo/matomo.ts

Reverts BIBSYSDEV/NVA-Frontend#6380

Revert "Configure logging of console errors"

---

src/pages/editor/PortfolioSearchPage.tsx

Reverts BIBSYSDEV/NVA-Frontend#6367
Merge denne når vi ikke lenger vil ha mulighet til å selv trigger errors i test

Revert "Trigger errors to test Crash Analytics"

---

src/pages/editor/InstitutionPage.tsx
src/pages/messages/TasksPage.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-47357
Fjern beta-tag nå som APIet ser ut til å returnere det vi forventer

Remove beta tag for result portfolio

---

buildspecs/codebuild_validation.yml
buildspecs/testsruns.yml
src/pages/project/tests/projectContributorHelpers.test.ts

Added vitest tests to build. Added with one failing test to verify that build will fail and it did, so fixed the failing test.

Added vitest tests to building

---

src/pages/my_page/user_profile/MyProfile.tsx
src/pages/my_page/user_profile/ProfilePictureUploader.tsx
src/translations/nbTranslations.json

Link to Jira issue: [https://sikt.atlassian.net/browse/NP-47179](https://sikt.atlassian.net/browse/NP-47179)
Added juridical text to person photo:

Added juridical text to person photo

---

src/pages/registration/SupportModalContent.tsx
src/translations/nbTranslations.json

Link to Jira issue: https://sikt.atlassian.net/browse/NP-47847
Added link for institution service center on curator support modal

NP-47847 added institution support link to curator support modal

---

src/api/searchApi.ts
src/pages/messages/components/NviCorrectionList.tsx
src/pages/messages/components/NviCorrectionListNavigationAccordion.tsx
src/translations/nbTranslations.json
src/utils/dataTestIds.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-47868
Legg til korreksjonsliste for uidentifiserte bidragsytere med identifiserte tilknytninger.

NP-47868 Add correction list for unidentified contributor with identified affiliation

---

src/pages/basic_data/institution_admin/AddEmployeePage.tsx

Forslag til noen mindre endringer på https://github.com/BIBSYSDEV/NVA-Frontend/pull/6428 som kan forenkle(?) submit-flyten

NP-47188 Try to simplify new user submit

---

src/pages/my_page/user_profile/MyFieldAndBackground.tsx
src/translations/nbTranslations.json

Link to Jira issue: [https://sikt.atlassian.net/browse/NP-47180](https://sikt.atlassian.net/browse/NP-47180)
New juridical texts to the "Fields and Background"-page, and the same new design as on profile page:

Changes to "Fields and background"-page

---

src/pages/basic_data/institution_admin/AddEmployeePage.tsx
src/pages/my_page/user_profile/MyProfile.tsx
src/translations/nbTranslations.json
src/utils/dataTestIds.ts

Link to Jira issue: [https://sikt.atlassian.net/browse/NP-47188](https://sikt.atlassian.net/browse/NP-47188)
Make user confirm that they have informed added user before adding:

Added popup to confirm that added user is aware they are being added

---

src/pages/project/project_wizard/NfrProjectSearch.tsx
src/translations/nbTranslations.json

Link to Jira issue: [https://sikt.atlassian.net/browse/NP-47892](https://sikt.atlassian.net/browse/NP-47892)
Changed two NFR-texts:
**Before**:
**After**:

New NFR-texts

---

src/api/hooks/useFetchRegistrationTickets.ts
src/pages/messages/components/NviCandidateActionPanel.tsx
src/pages/messages/components/NviCandidatePage.tsx
src/pages/public_registration/RegistrationLandingPage.tsx
src/utils/dataTestIds.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-47875
Vis logg på visning for NVI-kandidat.

NP-47875 Show log on NVI candidate

---

src/pages/registration/contributors_tab/components/AddContributorTableRow.tsx
src/pages/registration/contributors_tab/components/SelectAffiliationRadioButton.tsx
src/pages/registration/contributors_tab/components/SelectAffiliationsCheckbox.tsx
src/translations/nbTranslations.json

Link to Jira issue: [NP-47891](https://sikt.atlassian.net/browse/NP-47891)
In select contributor view: Possible to select person indirectly by clicking its affiliation.
Will apply to contributor view for both registration and project.
[NP-47891]: https://sikt.atlassian.net/browse/NP-47891?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Select person by selecting affiliation for checkboxes

---

src/pages/registration/RegistrationFormActions.tsx
src/translations/nbTranslations.json

Link to Jira issue: https://sikt.atlassian.net/browse/NP-47928
Disable lagreknapp når resultatet er publisert fra før og ikke validerer OK.

Np 47928 deny saving published result with validation error

---

src/components/Log/LogActionItem.tsx
src/components/Log/LogEntry.tsx
src/components/Log/LogHeader.tsx
src/pages/public_registration/action_accordions/DeletedRegistrationInformation.tsx
src/translations/nbTranslations.json
src/types/log.types.ts
src/types/registration.types.ts
src/utils/log/registrationEntryGenerator.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-47880
Her er det lagt til logginnslag for avpublisering og republisering. Kommer egen PR for logginnslag for sletting. Så kommer det en PR med mindre designendringer etter det. Kom også over en bug som jeg opprettet sak på, som jeg tar en gang oppi alt annet her.
Avpublisering og republisering vil nå vises sånn i loggen:

Np 47880 unpublished log item

---

src/types/importCandidate.types.ts
src/types/registration.types.ts
src/utils/formik-helpers/formik-helpers.ts

Legg til type for henting av alle felter på resource tab

Add type to PhD validation

---

src/translations/nbTranslations.json
src/types/publicationFieldNames.ts
src/utils/registration-helpers.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-47939
Legg til ny kategori `AcademicCommentary`. Denne skal være lik `AcademicMonograph`.

NP-47939 Add new category AcademicCommentary

---

src/pages/project/project_wizard/CreateNfrProject.tsx
src/pages/projects/AddProjectContributorForm.tsx
src/pages/projects/AddProjectManagerForm.tsx

Ferdigstilling av https://sikt.atlassian.net/browse/NP-47319
Fjern beta-tag fra uidentifisert prosjektdeltaker fra ønske fra PO.
Har en svakhet ved at en uidentifisert prosjektdeltaker vil se ut som en identifisert etter lagring, men dette vil snart ordne seg når backend er ferdig med https://sikt.atlassian.net/browse/NP-47681

Remove beta tag for unidentified project contributor

---

src/components/AreaOfResponsibiltySelector.tsx
src/pages/messages/components/ExcludeSubunitsCheckbox.tsx
src/pages/messages/components/NviCandidatesList.tsx
src/utils/dataTestIds.ts
src/utils/hooks/useNviCandidatesParams.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-47900
Legg til checkbox for å ekskludere underenheter på NVI-søk.

Np 47900 nvi search exclude subunits

---

src/api/searchApi.ts
src/pages/search/advanced_search/OrganizationFilters.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-47869
Bruke bare `unit` når man har både `topLevelOrganization` og `unit` i params

Np 47869 use unit param over toplevelorg

---

src/api/cristinApi.ts
src/api/hooks/useSearchForOrganizations.ts
src/components/institution/SelectInstitutionForm.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-47902
Søk bare på toppnivå som default når man søker etter org. 
Bruk `fullTree` i stedet for `version` i Accept header om vi vil ha hele treet til hvert treff.

Np 47902 optimize org search

---

src/pages/project/project_wizard/NfrProjectOption.tsx
src/pages/project/project_wizard/NfrProjectSearch.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-47978
Tillat å søke etter NFR-prosjekt med å skrive navn poå prosjektleder

Allow searching for NFR funding by project manager (lead)

---

src/components/DialoguesWithoutCuratorButton.tsx
src/layout/header/Header.tsx
src/translations/nbTranslations.json

Link to Jira issue: https://sikt.atlassian.net/browse/NP-47953
- Vis varselbjelle for innmeldte oppgaver
- Vis tootalt antall oppgaver i tootip ved hover

Np 47953 new task notification

---

src/components/ListSkeleton.tsx
src/utils/dataTestIds.ts

Legg til data-testid til Skeleton på bestilling fra Eirik

Add data-testid to Skeleton

---

src/pages/public_registration/action_accordions/PublishingAccordion.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48015
Løs feil når en pending publishgin ticket ikke er den nyeste, pga det er laget tickets fra flere ulike institusjoner.

Use pending ticket instead of last

---

src/components/RegistrationList.tsx
src/pages/registration/RegistrationFormActions.tsx
src/types/locationState.types.ts
src/utils/urlPaths.ts

bugfiks for https://github.com/BIBSYSDEV/NVA-Frontend/pull/6113
Send brukeren til landing page etter å ha endret noe på en post fra mine registreringer: http://localhost:3000/my-page/registrations/my-registrations

Handle updating result from my registrations

---

src/utils/log/publishingRequestGenerator.ts
src/utils/log/ticketEntryGenerator.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48018
Ta vare på logginnsalg for "Fil lastet opp" også etter filene har blitt godkjent/avvist. I tillegg til å håndtere mange ulike kombinasjoner av at filer kan bli slettet i etterkant osv.

Np 48018 show uploaded file log entries

---

src/components/RegistrationList.tsx
src/pages/messages/components/NviCandidateListItem.tsx
src/pages/registration/resource_type_tab/components/SearchContainerField.tsx
src/pages/registration/resource_type_tab/components/SearchRelatedResultField.tsx
src/pages/registration/resource_type_tab/sub_type_forms/research_data_types/DataManagementPlanForm.tsx
src/pages/registration/resource_type_tab/sub_type_forms/research_data_types/DatasetForm.tsx
src/types/nvi.types.ts
src/types/registration.types.ts

Fjern fallback for deprectated properties nå som de nye er tilgjengelig i alle miljø

Remove deprecated contributors properties

---

src/translations/nbTranslations.json
src/utils/validation/registration/contributorValidation.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48021
Textbook/Lærebok skal kreve enten forfatter eller redaktør, ikke bare forfatter som i dag

NP-48021 Require author or editor for Textbook

---

src/pages/registration/resource_type_tab/components/RelatedResultsField.tsx
src/pages/registration/resource_type_tab/sub_type_forms/research_data_types/RelatedResultItem.tsx
src/translations/nbTranslations.json

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48029
Some updates to texts in related results.

NP-48029 Updated texts for Related Results

---

src/translations/nbTranslations.json
src/utils/validation/registration/contributorValidation.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48021
Videreføring av https://github.com/BIBSYSDEV/NVA-Frontend/pull/6530
Krev enten forfatter eller redaktør for alle bok-kategorier.

NP-48021 Require author or editor for all books

---

src/api/apiPaths.ts
src/api/fileApi.ts
src/api/mock-interceptor.ts
src/pages/public_registration/public_files/FileRow.tsx
src/pages/registration/files_and_license_tab/DownloadFileButton.tsx
src/utils/testfiles/mockFiles.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-47872
Tillat nedlasting av fil via nytt endepunkt

NP-47872 Allow previewing and downloading registration files from new endpoint

---

src/pages/public_registration/action_accordions/PublishingAccordion.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48065
Løs feil hvor bruker ikke fikk se "Last på nytt"-knappen ved publisering av resultat og/eller filer.

Np 48065 handle mismatching published status

---

src/components/styled/Wrappers.tsx
src/pages/registration/resource_type_tab/sub_type_forms/research_data_types/RelatedResourceRow.tsx
src/pages/registration/resource_type_tab/sub_type_forms/research_data_types/RelatedResultItem.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-47309
Update the styling of related results for Phd resuts in wizard

NP-47309 update styling of related phd results

---

src/pages/messages/TasksPage.tsx
src/pages/messages/components/TicketList.tsx
src/pages/my_page/MyPagePage.tsx
src/translations/nbTranslations.json
src/utils/dataTestIds.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-47446
(re)moved "unread only" select button from the left side menu to filter select on top of results on main page.
Splitting the task into smaller PR's for easier QA.

NP-47446 Move "unread only" on MyPage

---

src/pages/messages/TasksPage.tsx
src/pages/messages/components/TicketList.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-47446
Remove unread only filter button on tasks page

NP-47446 Update "unread only" on tasks page

---

src/components/SideMenu.tsx
src/pages/basic_data/BasicDataPage.tsx
src/pages/messages/TasksPage.tsx
src/pages/my_page/MyPagePage.tsx
src/pages/public_registration/PublicRegistration.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48075
Add additional icon to the minimized menu button to better indicate that it returns the user to the previous page

NP-48075 Add icon to minimized menu button

---

src/pages/research_profile/PersonIconHeader.tsx
src/pages/research_profile/ResearchProfile.tsx
src/pages/search/person_search/PersonListItem.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48080
Legg til person-ikon for søketreff av personer
Før:
Etter:

Np 48080 add person icon

---

src/utils/formik-helpers/formik-helpers.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48117
Sikre at NPI-fagfelt viser feilmelding om man åpner et kapittel

NP-48117 Ensure chapter also validates the NPI field

---

src/components/CategorySelector.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-47791
Legg til skygge på kategori-chip, for å gi en ekstra indikasjon på at de er trykkbare

NP-47791 Add shadow to category chip

---

src/components/Log/LogAction.tsx
src/components/Log/LogActionActor.tsx
src/components/Log/LogActionItem.tsx
src/components/Log/LogDateItem.tsx
src/components/Log/LogEntry.tsx
src/components/Log/LogHeader.tsx
src/components/Log/RegistrationLog.tsx
src/pages/public_registration/LogPanel.tsx
src/translations/nbTranslations.json

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48045
Endring av design på logg elementer. Litt "triksing" av UI-elementer for å få ønsket design, så måten de fremstilles på er ikke nødvendigvis en god representasjon av hvordan komponentene faktisk er satt sammen.
Før:
Etter:

NP-48045 Updated design for log elements

---

src/pages/registration/files_and_license_tab/DownloadFileButton.tsx
src/pages/registration/files_and_license_tab/FilesTableRow.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48145
Løst noen feil som har kommet med ifbm nye begrensninger på filer. Har åpenbart vært slurvete verifisering av dette 😬 
Før:
Etter:

Np 48145 can change file without access

---

src/components/Log/LogEntry.tsx
src/components/Log/LogMessageAccordion.tsx
src/components/Log/RegistrationLog.tsx
src/pages/messages/components/MessageList.tsx
src/translations/nbTranslations.json
src/types/log.types.ts
src/types/publication_types/ticket.types.ts
src/utils/dataTestIds.ts
src/utils/log/doiRequestGenerator.ts
src/utils/log/publishingRequestGenerator.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48046
Create an accordion on LogEntries that finalizes a ticket (Files aublished/rejected) that shows the ticket messages.

NP-48046 Add messages to log entries

---

src/themes/mainTheme.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48155
Dropp portals for Menu (bl.a. i bruk for alle Select inputs) med pga a11y errors i axe. Kan ikke finne noen uheldige effekter av dette, men kan være jeg har oversett noe også..

NP-48155 Disable portals for Menu

---

src/pages/basic_data/app_admin/AdminCustomerInstitutions.tsx
src/pages/basic_data/app_admin/CustomerInstitutionList.tsx
src/pages/basic_data/app_admin/CustomerList.tsx
src/pages/basic_data/app_admin/InstitutionList.tsx
src/translations/nbTranslations.json
src/types/customerInstitution.types.ts
src/utils/dataTestIds.ts
src/utils/testfiles/mockCustomerInstitutions.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-47717
Lagt til støtte for å filtrere customers på navn og aktiv/ikke aktiv.

NP-47717 Add filtering on customers

---

src/components/Log/RegistrationLog.tsx
src/utils/log/logFactory.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48152

Np-48152 Reverse order of log entries

---

src/pages/messages/components/NviStatusTableRow.tsx
src/types/nvi.types.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48234
Oppdatert modell for institutsjonens NVI-status

NP-48234 Update NVI points model

---

src/api/apiPaths.ts
src/api/mock-interceptor.ts
src/api/publicationChannelApi.ts
src/pages/public_registration/PublicPublicationContext.tsx
src/pages/registration/resource_type_tab/components/JournalField.tsx
src/pages/registration/resource_type_tab/components/JournalFormDialog.tsx
src/pages/registration/resource_type_tab/components/NviValidation.tsx
src/pages/registration/resource_type_tab/components/PublicationChannelChipLabel.tsx
src/pages/registration/resource_type_tab/components/PublicationChannelOption.tsx
src/pages/registration/resource_type_tab/components/PublisherField.tsx
src/pages/registration/resource_type_tab/components/SearchContainerField.tsx
src/pages/registration/resource_type_tab/components/SeriesField.tsx
src/pages/search/advanced_search/JournalFilter.tsx
src/pages/search/advanced_search/SeriesFilter.tsx
src/pages/search/registration_search/RegistrationSearchBar.tsx
src/types/importCandidate.types.ts
src/types/registration.types.ts
src/utils/registration-helpers.ts
src/utils/testfiles/mockJournals.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48166
Erstatt `Journal` os `Series` med `SerialPublication`.

Np 48166 serial publication endpoint

---

src/pages/public_registration/ActionPanel.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48204
Tillat å publisere fra en support-ticket da det kan være at registrator ber om kuratorstøtte for publisering. Da må kurator kunne publisere selv på en enkel måte.

NP-48204 Allow publishing result from an support ticket

---

src/pages/registration/resource_type_tab/sub_type_forms/research_data_types/DatasetForm.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48207
Change text from "Related links" -> "External links" in wizard

NP-48207 Updated text for external links on dataset in wizard

---

src/pages/messages/components/TicketListItem.tsx
src/pages/public_registration/action_accordions/DoiRequestAccordion.tsx
src/pages/public_registration/action_accordions/PublishingAccordion.tsx
src/pages/public_registration/action_accordions/SupportAccordion.tsx
src/types/locationState.types.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48167
Vis valgt ticket som ekspandert som standard når man kommer fra Oppgaver/Dialoger. Vanlig landing apge oppfører seg fortsatt som før, ved at tickets/accordions som krever oppmerksomhet er fremhevet

Np 48167 open correct ticket accordion

---

src/pages/messages/components/NviYearSelector.tsx
src/pages/search/advanced_search/AdvancedSearchPage.tsx
src/pages/search/advanced_search/NviReportedYearFilter.tsx
src/translations/nbTranslations.json
src/utils/dataTestIds.ts
src/utils/nviHelpers.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48237
Legg til filter for NVI rapporteringsår

Np 48237 advanced search nvi reporting year

---

src/pages/my_page/MyPagePage.tsx
src/pages/my_page/user_profile/Terms.tsx
src/translations/nbTranslations.json
src/utils/dataTestIds.ts
src/utils/urlPaths.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-47184
Vis brukervilkår på min side

NP-47184 Show terms information on my page

---

src/pages/basic_data/institution_admin/person_register/PersonRegisterPage.tsx
src/pages/editor/PublishStrategySettings.tsx
src/pages/public_registration/public_files/FileRow.tsx
src/themes/mainTheme.ts

Løser noen lavthengende a11y errors som rapporteres av Axe.

Resolve a11y errors

---

src/pages/public_registration/PublicRegistrationContent.tsx
src/pages/registration/resource_type_tab/sub_type_forms/DegreeForm.tsx
src/pages/registration/resource_type_tab/sub_type_forms/degree_types/PhdForm.tsx
src/translations/nbTranslations.json
src/types/publicationFieldNames.ts
src/utils/registration-helpers.ts
src/utils/validation/registration/referenceValidation.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-47956
Støtte for ny kategori: Kunstnerisk doktorgradsresultat

Np 47956 artistic phd

---

src/layout/Footer.tsx
src/translations/nbTranslations.json

Link to Jira issue: https://sikt.atlassian.net/browse/NP-47187
Legg til "Henvendelser om opphavsrett" i footer.

Np 47187 copyright inquiries in footer

---

src/components/DialoguesWithoutCuratorButton.tsx
src/layout/header/Header.tsx
src/pages/messages/TasksPage.tsx
src/utils/searchHelpers.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48306
Sørg for at bare tickets man har tilganng til inkluderes i varslene som vises i header.

NP-48306 Ensure user only get aggregations for tickets they have access to

---

src/pages/public_registration/public_links/ShowRelatedDocuments.tsx
src/utils/formik-helpers/formik-helpers.ts

- Vis valideringsfeil for relatert-felt på kunstnerisk PhD
- Skjul tomme verdier for related på landing page

Handle related validation error

---

src/utils/searchHelpers.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48306
Fikser en glipp fra https://github.com/BIBSYSDEV/NVA-Frontend/pull/6769 som gjorde at søket for varsler ikke virket for support case

NP-48306 Fix wrong ticket type in notification search

---

cypress/e2e/menu.spec.ts
cypress/support/commands.ts
package-lock.json
package.json
src/AppRoutes.tsx
src/components/DialoguesWithoutCuratorButton.tsx
src/layout/Footer.tsx
src/layout/header/Header.tsx
src/pages/basic_data/BasicDataPage.tsx
src/pages/messages/TasksPage.tsx
src/pages/public_registration/action_accordions/PublishingAccordion.tsx
src/pages/public_registration/public_links/ShowRelatedDocuments.tsx
src/translations/enTranslations.json
src/translations/nbTranslations.json
src/translations/nnTranslations.json
src/utils/dataTestIds.ts
src/utils/formik-helpers/formik-helpers.ts
src/utils/searchHelpers.ts

:bug: Bugfiks :bug:
* Løst feil hvor man noen ganger ikke fikk lov til å publisere med arbeidsflyt 2 pga. feilaktige valideringsfeil ([PR](https://github.com/BIBSYSDEV/NVA-Frontend/pull/6770))
* Løst feil hvor tomme verdier for relaterte resultat ble forsøkt vist på landingssiden for PhD ([PR](https://github.com/BIBSYSDEV/NVA-Frontend/pull/6772))
* Løst feil hvor man noen ganger fikk feil antall varsler for Oppgaver i header ([Jira](https://sikt.atlassian.net/browse/NP-48306))
:art: Designendringer :art:
* Lagt til lenke for "Henvendelser om opphavsrett" i footer ([Jira](https://sikt.atlassian.net/browse/NP-47187))

Update staging 20.12.24

---

src/pages/registration/contributors_tab/components/AffiliationsCell.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-45718
Sikre at alle tilknytninger alltid får en unik ID. Tidligere skjedde det mye rart om man hadde samme institusjon lagt til flere ganger, og prøvde å fjerne den.

NP-45718 Ensure unique key for every affiliation

---

src/pages/messages/components/NviApprovals.tsx
src/pages/messages/components/NviCandidateActionPanel.tsx
src/themes/mainTheme.ts
src/translations/nbTranslations.json
src/types/nvi.types.ts

Link to Jira issue: [NP-48173](https://sikt.atlassian.net/browse/NP-48173)
Endrer på tabell for nvi-status og -poeng.
[NP-48173]: https://sikt.atlassian.net/browse/NP-48173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

NP-48173 Change NVI table in action panel

---

src/translations/nbTranslations.json

Link to Jira issue: [NP-48130](https://sikt.atlassian.net/browse/NP-48130)
Oppdaterer tekst over NVI meldingsboks.
[NP-48130]: https://sikt.atlassian.net/browse/NP-48130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

NP-48130 Update nvi message description

---

src/pages/public_registration/PublicPublicationContext.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48142
- Legg til ikon for å vise at lenken åpnes i ny fane og går til en ekstern side.
- Bruk samme komponent for link til både tidsskrift og utgiver
- Unngå at lenken strekker seg ut hele bredden (også utenfor teksten)

NP-48142 Add icon to channel register link

---

src/pages/messages/components/NviCandidateRejectionDialog.tsx
src/translations/nbTranslations.json

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48128

NP-48128 Update text for rejecting NVI candidate

---

src/layout/Footer.tsx
src/pages/messages/components/NviCandidateActions.tsx
src/pages/messages/components/NviCandidateRejectionDialog.tsx
src/pages/my_page/user_profile/UserOrcidHelperModal.tsx
src/pages/my_page/user_profile/UserRoleAndHelp.tsx
src/pages/public_registration/action_accordions/DoiRequestAccordion.tsx
src/translations/nbTranslations.json

Utspring fra fra https://github.com/BIBSYSDEV/NVA-Frontend/pull/6871#discussion_r1913263402

Update icon used for external links

---

src/pages/public_registration/action_accordions/AccordionStatusChip.tsx
src/pages/public_registration/action_accordions/DoiRequestAccordion.tsx
src/pages/public_registration/action_accordions/PublishingAccordion.tsx
src/pages/public_registration/action_accordions/SupportAccordion.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-47981
Før:
Etter:

Np 47981 update ticket status design

---

src/api/searchApi.ts
src/pages/basic_data/app_admin/central_import/CentralImportDuplicateSearch.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48365
The param `publicationYearShould` returned `400: Bad Request`. Updated to `publicationYear`

NP-48365 Update Central Import search param

---

src/pages/public_registration/action_accordions/UnpublishRegistration.tsx

Added multiline to comment-field to prevent accidental submit when hitting "enter"

Added multiline

---

src/pages/messages/components/NviCandidateActions.tsx
src/translations/nbTranslations.json

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48141
Første del av oppgaven som endrer heading til kommentar for avvist NVI-kandidat.

NP-48141 Update rejection note heading

---

src/components/StatusChip.tsx
src/pages/messages/components/NviCandidateActionPanel.tsx
src/pages/messages/components/NviCandidateListItem.tsx
src/pages/messages/components/NviDialoguePanel.tsx
src/pages/public_registration/action_accordions/AccordionStatusChip.tsx
src/pages/public_registration/action_accordions/DoiRequestAccordion.tsx
src/pages/public_registration/action_accordions/PublishingAccordion.tsx
src/pages/public_registration/action_accordions/SupportAccordion.tsx
src/translations/nbTranslations.json

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48133
- Legger til status-chip for NVI
- Refaktorerer status-chip fra tickets så den også støtter NVI (og andre ting) på en enklere måte
NVI-liste før:
NVI-liste etter:
Kandidat før:
Kandidat etter:

Np 48133 add status chip to nvi

---

src/pages/registration/RegistrationForm.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48369
Added a `useEffect` that sends the user to the top of the page when `tabNumber` changes (mostly to fix issued on handheld devices)

NP-48369 Fix wizard navigation

---

src/pages/public_registration/action_accordions/PublishingAccordion.tsx
src/pages/public_registration/action_accordions/PublishingAccordionLastTicketInfo.tsx
src/pages/public_registration/action_accordions/TicketAssignee.tsx
src/pages/registration/FilesAndLicensePanel.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48397
- Nekt brukter å laste opp fil om man ikke har `publishing-request-create`
- Skjul meldingsfelt for tickets som ikke er `Pending` eller `New`
- Ta vekk "Venter på kurator" om ticket mangler kurator men ikke er pending
Landing Page før:
Landing Page etter:

Np 48397 access right for file upload

---

src/pages/messages/components/NviApprovals.tsx
src/pages/messages/components/NviCandidateActions.tsx
src/pages/messages/components/NviDialoguePanel.tsx
src/translations/nbTranslations.json

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48134
Dette er gjort:
- Endret tekst for å godkjenne tidligere avvist kandidat
- Endre rekkefølgen på ting i NVI action panel
- Godkjenn/avvis-knapper vises til slutt om kandidaten allerede er godkjent eller avvist
Før:
Etter:

Np 48134 update nvi actions layout

---

src/pages/public_registration/ChapterPublisherInfo.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48414
Før:
Etter:

NP-48414 Hyphenate ISBN of chapter publishers

---

src/layout/Footer.tsx
src/translations/nbTranslations.json
src/utils/dataTestIds.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48370
Etter en del forskjellige tilbakemeldinger ble dette resultatet av endringer for footer for mobil (og desktop).

NP-48370 Add "to top" button

---

src/components/ListPagination.tsx
src/components/ListPaginationBottom.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48454
When a user navigates to a new page of a result, the user should be led back to the top of the search results. This PR implements an "anchor" at the top of the pagination component.

NP-48454 Update scroll behavior

---

src/utils/hooks/useAuthentication.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48445
Løs feil hvor man får en feil i konsollen om man prøver å logge inn etter å ha logget inn i et annet vindu. Last siden på nytt i det tilfellet, slik at man få hentet inn samme bruker som i det andre vinduet.

NP-48445 Handle error when user try to log in in different windows

---

src/pages/messages/TasksPage.tsx
src/pages/my_page/MyPagePage.tsx
src/utils/searchHelpers.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48467
Glemte å legge ved dette i første omgang.

NP-48467 added pagination reset for ticket type buttons

---

src/components/ContributorSearchField.tsx
src/components/ListPagination.tsx
src/components/ListPaginationBottom.tsx
src/pages/basic_data/app_admin/central_import/CentralImportDuplicateSearch.tsx
src/pages/basic_data/app_admin/central_import/CentralImportPage.tsx
src/pages/basic_data/institution_admin/person_register/PersonRegisterPage.tsx
src/pages/messages/components/NviCandidatesList.tsx
src/pages/messages/components/TicketList.tsx
src/pages/my_page/user_profile/MyProjectRegistrations.tsx
src/pages/my_page/user_profile/MyProjects.tsx
src/pages/my_page/user_profile/MyResults.tsx
src/pages/research_profile/ResearchProfile.tsx
src/pages/search/person_search/PersonSearch.tsx
src/pages/search/project_search/ProjectSearch.tsx
src/pages/search/registration_search/RegistrationSearch.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48454
Move conditional rendering inside `ListPagination` to allow the "anchor" to always be rendered on the page.

NP-48454 Move ListPagination out of conditional rendering

---

src/pages/basic_data/institution_admin/AddEmployeePage.tsx
src/pages/basic_data/institution_admin/edit_user/RolesFormSection.tsx
src/pages/basic_data/institution_admin/edit_user/TasksFormSection.tsx
src/pages/basic_data/institution_admin/edit_user/UserFormDialog.tsx
src/translations/nbTranslations.json

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48497
Flyttet studentfil- og embargokurator inn i checklista for roller, og fjernet avhengighet til publiseringskurator.

Np 48497 update thesis curator role

---

src/components/RegistrationList.tsx

Fix overextending TicketListItem

---

src/pages/messages/components/NviCandidateActionPanel.tsx
src/pages/messages/components/NviCandidateActions.tsx
src/types/nvi.types.ts
src/utils/testfiles/mockNviCandidate.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48169
Baser tilgangssjekker for NVI-operasjoner på `allowedOperations` fra backend 

NP-48169 Use allowed operations for NVI candidates

---

src/pages/basic_data/institution_admin/AddEmployeePage.tsx
src/pages/basic_data/institution_admin/edit_user/RolesFormSection.tsx
src/pages/basic_data/institution_admin/edit_user/UserFormDialog.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48497 (continued)
Ref. code review from   #6972 

NP-48497 use dependant checkboxes instead of disable

---

src/pages/reports/ClinicalTreatmentStudiesReports.tsx
src/pages/reports/InternationalCooperationReports.tsx
src/pages/reports/NviReports.tsx
src/pages/reports/ReportButton.tsx
src/pages/reports/ReportsPage.tsx
src/pages/search/SearchPage.tsx
src/pages/search/advanced_search/AdvancedSearchPage.tsx
src/translations/nbTranslations.json

Added hidden headings and page titles to HomePage for better a11y

NP-48525 Added hidden headings and page titles to HomePage

---

src/components/Modal.tsx
src/pages/registration/RegistrationFormActions.tsx
src/themes/mainTheme.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48533
For at dialog content skal leses i skjermlesere må vi sørge for at `<Dialog>` har en gyldig `aria-labelledby` og `aria-describedby`.

Np 48533 ensure dialog content are read in screen readers

---

src/pages/messages/components/NviCandidatesList.tsx

Added a fallback value for `nviCandidatesQuery.data?.hits`

Add fallback for NviCandidatesQuery

---

src/pages/editor/CategoriesWithFiles.tsx
src/pages/editor/CategoriesWithFilesOverview.tsx
src/pages/editor/EditorDoi.tsx
src/pages/editor/EditorInstitution.tsx
src/pages/editor/InstitutionSupport.tsx
src/pages/editor/PublishStrategySettings.tsx
src/pages/editor/PublishingStrategyOverview.tsx
src/pages/editor/VocabularyOverview.tsx
src/pages/editor/VocabularySettings.tsx
src/translations/nbTranslations.json

Updated headers and semantics for InstitutionPage(s)

Np 48525 add headings and titles institution page

---

src/api/hooks/useSerialPublicationSearch.ts
src/pages/search/registration_search/filters/RegistrationFacetsFilter.tsx
src/pages/search/registration_search/filters/SearchForSerialPublicationFacetItem.tsx
src/translations/nbTranslations.json
src/utils/dataTestIds.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48579
Legg til søkefelter for tidsskrift- og seriefasettene.
Bygger videre på samme løsning som for utgiver: https://github.com/BIBSYSDEV/NVA-Frontend/pull/7023

Np 48579 search for serial publication in facet

---

src/pages/my_page/user_profile/MyFieldAndBackground.tsx
src/pages/my_page/user_profile/MyProfile.tsx
src/pages/my_page/user_profile/MyProjectRegistrations.tsx
src/pages/my_page/user_profile/MyProjects.tsx
src/pages/my_page/user_profile/MyResults.tsx
src/pages/my_page/user_profile/UserRoleAndHelp.tsx
src/pages/my_page/user_profile/UserRoles.tsx
src/pages/my_registrations/MyRegistrations.tsx

NP-48525 Add headers for MyPage pages

---

src/pages/search/FacetItem.tsx
src/pages/search/FacetItemContentSkeleton.tsx
src/pages/search/registration_search/filters/RegistrationFacetsFilter.tsx
src/themes/mainTheme.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48581
Vis skeleton i stedet for å skjule alle fasett-bokser mens data laster.

Np 48581 facet loading indicator

---

src/utils/validation/registration/associatedArtifactValidation.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48592
Fikser feil introdusert i https://github.com/BIBSYSDEV/NVA-Frontend/pull/6922 (mer spesifikt [her](https://github.com/BIBSYSDEV/NVA-Frontend/pull/6922/files#diff-32da495bf5073e95106371cc2b6993b6bc49dbd1989d551f26b09a6b08b98a91))
Tillat å publisere et resultat uten filer, feks med `NullAssociatedArtifact`

NP-48592 Allow publishing result without file

---

src/pages/public_registration/action_accordions/PublishingAccordion.tsx

Løser feil hvor bruker får beskjed om å trykke på en knapp som ikke er der fordi hen ikke har tilgang til å gjøre det.
Eksempel: https://test.nva.sikt.no/tasks/dialogue/01948d084112-82944e6c-d857-4038-a593-bfcbe8afac69

Hide delete text when user cannot delete

---

src/components/StructuredSeoData.tsx
src/pages/public_registration/PublicRegistrationContent.tsx
src/utils/hooks/useJournalSeoData.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48607
Har lagt inn de mest sentrale tagsene som er nevnt her: https://scholar.google.com/intl/en/scholar/inclusion.html#indexing
Mye mer som kan (og burde) gjøres, men starter i det små med dette for å se om det har noen betydning for Google Scholar.

Np 48607 add higwire press meta tags

---

src/api/preferencesApi.ts
src/components/RegistrationList.tsx
src/layout/Logout.tsx
src/pages/editor/EditorInstitution.tsx
src/pages/my_page/user_profile/MyResults.tsx
src/pages/research_profile/ResearchProfile.tsx
src/utils/urlPaths.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48607
Endre path for bedre SEO
Før:
`/research-profile?id=https%3A%2F%2Fapi.dev.nva.aws.unit.no%2Fcristin%2Fperson%2F1421086 ` 
Etter:
`/research-profile/1421086` 

NP-48607 Use canonical URL for research profile

---

src/pages/search/SearchTextField.tsx
src/pages/search/SearchTypeField.tsx
src/pages/search/registration_search/RegistrationSearchBar.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48598
Ta vare på søketermen man har skrevet når man bytter hva man vil søke etter. F.eks. om man søker etter "kjetil" blandt resultater, men så vil endre til å søke etter personer med det navnet i stedet.

Np 48598 keep query when changing search type

---

src/components/NavigationListAccordion.tsx
src/components/PageWithSideMenu.tsx
src/components/SideMenu.tsx
src/pages/basic_data/BasicDataPage.tsx
src/pages/basic_data/app_admin/central_import/CentralImportDuplicationCheckPage.tsx
src/pages/dashboard/Dashboard.tsx
src/pages/messages/components/NviCandidateActions.tsx

Adjust headings of left- and right-side menus/components

NP-48525 Adjusted headers in peripheral components

---

src/layout/Footer.tsx
src/translations/nbTranslations.json

NP-48525 Add headers to footer

---

src/pages/registration/new_registration/LinkRegistration.tsx
src/pages/registration/new_registration/StartEmptyRegistration.tsx

NP-48525 Remove h2 from new result buttons

---

src/pages/projects/ProjectGeneralInfo.tsx
src/pages/public_registration/PublicDoi.tsx
src/pages/public_registration/PublicGeneralContent.tsx
src/pages/public_registration/PublicHandles.tsx
src/pages/public_registration/PublicPageInfoEntry.tsx
src/translations/nbTranslations.json

NP-48525 Adjust headings on Project Landing Page

---

src/translations/nbTranslations.json
src/utils/log/logFactory.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48650
Sørg for at den forenklede loggen stemmer overens med filene som ligger på posten, og at filer som har blitt fjernet etter at de ble behandlet i ticket ignoreres.
Har sett en liten bug, som vi tror er pga gammel søppeldata så lar det ligge. Har dokumentert det [her](https://sikt.atlassian.net/browse/NP-48650?focusedCommentId=112512).

Np 48650 ensure simplified log show correct data

---

src/pages/registration/new_registration/StartEmptyRegistration.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48671

NP-48671 adjust position of spinner

---

src/components/RegistrationList.tsx

Unngå at redaktør automatisk blir videresendt til duplikat om resultetet ble markert som duplikat ved avpublisering før det ble slettet.
Svar på backend-endring: https://github.com/BIBSYSDEV/nva-publication-api/pull/2077

Avoid redirect for deleted result with duplicate

---

src/pages/public_registration/ActionPanel.tsx
src/pages/public_registration/log/LogEntry.tsx
src/pages/public_registration/log/LogPanel.tsx
src/types/log.types.ts
src/utils/general-helpers.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48542
Vis meldinger fra tickets i den ny loggen der det er relevant.
Finner tilsvarende ticekt ved å se etter tickets som er ferdigstilit ca samtidig som log entry ble opprettet og hvor typene er kompatible. For filer må vi ha noen ekstra sjekker som sjekker at ticket og logg gjelder for samme filtype, i tilfelle man endrer filtype flere ganger.

Np 48542 show messages in log

---

src/components/SideMenu.tsx
src/pages/basic_data/BasicDataPage.tsx
src/pages/messages/TasksPage.tsx
src/pages/my_page/MyPagePage.tsx
src/pages/public_registration/PublicRegistration.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48538
Change the component of the "Go Back"-button.
ref: https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element

NP-48538 a11y violoation on "Go Back"-button

---

src/components/NavigationListAccordion.tsx
src/components/PageWithSideMenu.tsx
src/pages/basic_data/BasicDataPage.tsx
src/pages/dashboard/HomePage.tsx
src/pages/editor/InstitutionPage.tsx
src/pages/my_page/MyPagePage.tsx

Løser feil med at samme id gjentas flere ganger på samme side. Tror ikke dette skal introdusere noen nye problemer.
Introdusert her: https://github.com/BIBSYSDEV/NVA-Frontend/pull/7045

NP-48525 Avoid multiple headings with same id in side menu

---

src/pages/registration/FilesAndLicensePanel.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48709
- Oppdater link til kanalregister fra filer-fanen
- Bruk den nye komponenten for eksterne linker

NP-48709 Update link for channel register on files tab

---

src/pages/basic_data/app_admin/central_import/CentralImportPage.tsx
src/pages/search/selected_facets/SelectedImportCandidateFacetsList.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48700
Vis valgte fasetter for sentralimport.

NP-48700 Show selected facets for import candidates

---

src/pages/search/SearchPage.tsx
src/pages/search/registration_search/RegistrationSearchBar.tsx
src/pages/search/selected_facets/SelectedFacetsList.tsx
src/pages/search/selected_facets/SelectedImportCandidateFacetsList.tsx
src/pages/search/selected_facets/SelectedPersonFacetsList.tsx
src/pages/search/selected_facets/SelectedProjectFacetsList.tsx
src/pages/search/selected_facets/SelectedResultFacetsList.tsx
src/pages/search/selected_facets/button_content/SelectedCategoryFacetButton.tsx
src/pages/search/selected_facets/button_content/SelectedFundingFacetButton.tsx
src/pages/search/selected_facets/button_content/SelectedInstitutionFacetButton.tsx
src/pages/search/selected_facets/button_content/SelectedJournalFacetButton.tsx
src/pages/search/selected_facets/button_content/SelectedPersonFacetButton.tsx
src/pages/search/selected_facets/button_content/SelectedPublisherFacetButton.tsx
src/pages/search/selected_facets/button_content/SelectedSeriesFacetButton.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48700
- Vis fasetter for resultatsøk på samme måte som de andre søkene.
- Mange nye filer da komponenter som tidligere var samlet i samme fil er splitta ut, men ingen/minimalt med kodeendringer her
- Lagt til fasett-knapp for filter for årstall
- Justert margin for mobilskjerm for alle fasettopplistinger
Med oppryddingen som har vært nevnt i tidligere PRs ble naturlig å ta inn her, derfor ble det en nokså stor PR. Kunne sikkert delt opp denne mer også 

Np 48700 refacor results facet buttons

---

src/pages/public_registration/public_files/FilesLandingPageAccordion.tsx
src/pages/registration/FileList.tsx
src/pages/registration/files_and_license_tab/FilesTableRow.tsx
src/utils/registration-helpers.ts
src/utils/validation/registration/associatedArtifactValidation.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48733
Sørg for at bare aksepterte filer viser RRS-info.
Før:
Etter:

Np 48733 show rrs text only for accepted version

---

src/components/SearchForm.tsx
src/pages/basic_data/app_admin/central_import/CentralImportPage.tsx
src/pages/editor/PortfolioSearchPage.tsx
src/pages/messages/components/NviCandidatesList.tsx
src/pages/messages/components/TicketList.tsx
src/pages/search/SearchPage.tsx
src/pages/search/advanced_search/AdvancedSearchPage.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48739
Sørg for at paginering resettes når bruker gjør nytt søk. Dette virket ikke for NVI tidligere. Har derfor utvidet `SearchForm` til å ta inn param som skal fjernes som prop

NP-48739 Ensure search bar resets correct pagination param on change

---

src/pages/messages/components/MessageMenu.tsx
src/pages/messages/components/NviCandidateActions.tsx
src/pages/messages/components/NviNoteMenu.tsx
src/translations/nbTranslations.json

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48738
- Unngå at godkjenninger fra andre institusjoner får slett-knapp
- Tilpass slette-advarsen til om det er kommentar eller godkjenning man vil slette
- Utbedring av noen mindre UU-mangler

Np 48738 fix removal of nvi note deletion

---

src/pages/search/registration_search/filters/RegistrationFacetsFilter.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48741
Oppdater resultatsøk etter at denne ble endret pga andre krav i søk på sentralimport.
Feilen ble introdusert her: https://github.com/BIBSYSDEV/NVA-Frontend/pull/7137/files#diff-34b9a7e33509c9ecb26f8d03565605d49817d5f19ce25b91d06f4a545440384f

NP-48741 Allow selecting institution facet from search field for result search

---

src/pages/messages/components/NviCorrectionListNavigationAccordion.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48760
Løs feil hvor kategorier ikke var vist som valgt som standard når man gikk inn på retteliste. Gikk også over til å bruke den nye `useSearchParams`-hooken siden den forenkler ting

Np 48760 fix default params on correction list

---

src/pages/registration/RegistrationForm.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48767
Denne sneik seg nok med fra da vi gikk over til `react-router-v6`

Fixed navigate check when declining NVI-warning

---

src/pages/public_registration/log/LogEntryImportSourceInfo.tsx
src/pages/public_registration/log/LogEntryItem.tsx
src/types/log.types.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48542
Oppdater logg til å ta i bruk ny modell som bruker verdier (navn) fra Cristin. Minimalt med ny kode her, men modellendringene førte til noen enndringer rundt oppsett for å forenkle ting. Derfor har en del blitt flyttet litt.

Np 48542 update log model

---

src/App.tsx
src/api/authApi.ts
src/components/AcceptTermsDialog.tsx
src/components/CreateCristinPersonDialog.tsx
src/components/SelectCustomerInstitutionDialog.tsx
src/pages/basic_data/institution_admin/person_register/PersonRegisterPage.tsx
src/pages/my_page/user_profile/MyProfile.tsx
src/redux/userSlice.ts
src/translations/nbTranslations.json
src/types/user.types.ts
src/utils/aws-config.ts
src/utils/testfiles/mock_feide_user.ts
src/utils/validation/basic_data/addEmployeeValidation.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48727
Dette er gjort:
- Hent user attributes fra tokens i stedet for eget kall til Cognito
- Fjern alle referanser til NIN fra user attributes/tokens
Ting ser ut til å virke fint, men siden dette rører ved innloggingsflyt er det kanskje greit å vente med merge til pågående utrøvingsperiode er over.

Np 48727 get user attributes from tokens

---

src/pages/editor/curators/AddCuratorForm.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48775
Updated the handling of curator roles to reflect the same functionality as when a new person created. Also removed disabled checkboxes for better a11y.

NP-48775 Changed behavior of CuratorThesis on InstitutionPage

---

src/pages/public_registration/log/LogEntryItem.tsx
src/translations/nbTranslations.json
src/types/log.types.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48789
Vis logginnslag for filer som har fått oppdatert type

NP-48789 Show log entry for file type changed

---

src/translations/nbTranslations.json

Update translation for channel info

---

src/pages/registration/FileList.tsx
src/translations/nbTranslations.json
src/types/license.types.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48746
Add more helper text to the cc0 license.

NP-48746 Add additional text to cc0-license

---

src/pages/messages/components/NviDialoguePanel.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48820
Før:
Etter:

NP-48820 Show only approvals when user is not allowed to handle the NVI candidate

---

src/pages/messages/components/NviCandidateActionPanel.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48820
Unngå å hente tickets og vise logg om bruker ikke har tilgang til å endre på resultatet.

Np 48820 ignore tickets for nvi candidates with update permission

---

src/pages/public_registration/action_accordions/UnpublishRegistration.tsx
src/translations/nbTranslations.json

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48764
Oppdater hjelpetekst for avpublisering for brukere som ikke har tilgang til det.

NP-48764 Update helper text for missing unpublish access right

---

src/components/RegistrationList.tsx
src/pages/basic_data/institution_admin/person_register/PersonTableRow.tsx
src/pages/registration/FilesAndLicensePanel.tsx
src/pages/search/project_search/ProjectListItem.tsx
src/utils/dataTestIds.ts

Link to Jira issue:  https://sikt.atlassian.net/browse/NP-48898
Added some missing data-testids

NP-48898 Added missing dataTestIds

---

eslint.config.js
tsconfig.json

Løst noen config-feil rundt tsconfig og eslint
Feil i vite config:
Feil i tsconfig:

Fix eslint and tsconfig errors

---

src/pages/editor/InstitutionPage.tsx
src/pages/editor/PublisherOwnershipSettings.tsx
src/translations/nbTranslations.json
src/utils/dataTestIds.ts
src/utils/urlPaths.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48997
Legg til side for å adminstrere eierskap til utgivere under beta-flagg.
Innhold til denne siden kommer i senere PRer. Mye jobb gjentår før beta-tag kan fjernes her.

NP-48997 Add page for publisher ownership

---

src/api/customerInstitutionsApi.ts
src/pages/editor/AddChannelClaimDialog.tsx
src/pages/editor/PublisherOwnershipSettings.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-49040

NP-49040 Refetch channel claims when adding a new one

---

src/api/customerInstitutionsApi.ts
src/pages/editor/PublisherOwnershipSettings.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48505
Added supprt for using type-param to `fetchClaimedChannels`

NP-48505 Add channel claim param

---

src/utils/registration-helpers.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-49008
Vis redaktør som rolle for tidsskriftspubliseringer og kapittel

NP-49008 Show Editor role for journal and chapter results

---

src/translations/nbTranslations.json
src/utils/registration-helpers.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48498
Tillat alle brukere å registrere studentoppgaver. Tidligere var det bare studentkurator som hadde lov til dette. Filer på studentoppgaver må godkjennes av studentkurator.
Før:

NP-48498 Allow all users to register thesis

---

src/pages/editor/AddChannelClaimDialog.tsx

Use double quotes instead of curly braces + single quotes for i18n-keys

Fix unused channel claim keys

---

src/pages/editor/PublisherClaimsOverview.tsx
src/pages/editor/SerialPublicationClaimsOverview.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-49056
Added overvoew over channel ownership on institution page.

NP-49056 Add pages for channel claim overviews

---

src/components/AssigneeSelector.tsx
src/pages/messages/components/TicketListItem.tsx
src/pages/public_registration/action_accordions/DoiRequestAccordion.tsx
src/pages/public_registration/action_accordions/RefreshPublishingRequestButton.tsx
src/pages/public_registration/action_accordions/SupportAccordion.tsx
src/utils/searchHelpers.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-49036
Invalider notifikasjoner i header når man gjør endringer på en ticket som kan påvirke antall varsler. Noe treghet i når ticket-søk plukker opp endringer, så ikke garantert at man alltid får oppdatert antall varsler, men det er vurdert som OK i denne runden.

Np 49036 refresh notifications

---

src/pages/editor/InstitutionPage.tsx
src/translations/nbTranslations.json

Remove beta-tags from channel claims in institution

Remove beta-tag from channel claims

---

src/api/hooks/useFetchChannelClaim.ts
src/pages/messages/components/NviCandidateActionPanel.tsx
src/pages/public_registration/PublicDoi.tsx
src/pages/public_registration/PublicRegistrationContent.tsx
src/pages/public_registration/RegistrationLandingPage.tsx
src/pages/public_registration/public_files/FilesLandingPageAccordion.tsx
src/pages/registration/FilesAndLicensePanel.tsx
src/pages/registration/RegistrationForm.tsx
src/types/registration.types.ts
src/utils/hooks/useFetchChannelClaimsData.ts
src/utils/registration-helpers.ts
src/utils/testfiles/mockRegistration.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48513
Bruk allowedOperations i stedet for frontend-logikk til å bestemme om man har lov til å endre på felter pga kanaleierskap.

Np 48513 use allow operation for channel claims

---

src/pages/registration/RegistrationForm.tsx

Quick-fix for å unngå evig loading pga lasting av kanaleierskap

Update staging 15.05.25

---

src/pages/editor/ChannelClaimTableRow.tsx

Added a check for channel ownership in regards to deleting a claim

Added check for channel ownership

---

src/api/registrationApi.ts
src/pages/registration/RegistrationFormActions.tsx
src/types/registration.types.ts
src/utils/registration-helpers.ts

Link to Jira issue: [NP-49152](https://sikt.atlassian.net/browse/NP-49152)
Legger til `partialUpdateRegistration()` i registrationApi, som tar i bruk den nye typen `PartialUpdatePublicationRequest`. Om bruker kun har `partial-update` så skal denne brukes.
[NP-49152]: https://sikt.atlassian.net/browse/NP-49152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add partial-update request

---

src/pages/messages/TasksPage.tsx
src/pages/messages/components/ExcludeSubunitsCheckbox.tsx
src/pages/messages/components/NviCandidatesList.tsx
src/pages/messages/components/TicketList.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-49038
Legg til filtrering på å ekskludere underenheter på Oppgaver-siden.

NP-49038 Show exclude subunits filter for tasks

---

src/pages/messages/TasksPage.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-49189
Tillat alle kuratorer å åpne resultatregistreringer

NP-49189 Allow all curators to see result registrations

---

src/pages/registration/FileList.tsx
src/pages/registration/FilesAndLicensePanel.tsx
src/translations/nbTranslations.json

Some changes tot he structure of file helper texts. Ref #7393

Updated file helper text structure

---

src/pages/my_page/user_profile/UserRoles.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-49200
Legg til `thesis-curator`-roller på Min Side > Brukerroller og hjelp

NP-49200 update My Page role list

---

src/pages/registration/FileList.tsx
src/pages/registration/HelperTextModal.tsx
src/translations/nbTranslations.json

Link to Jira issue: https://sikt.atlassian.net/browse/NP-48389
Oppdatert hjelpe-modal for lisenser på `Fil, Lisens og Lenke`-fanen.

NP-48389 new license modal

---

src/pages/research_profile/ResearchProfile.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-49212
En minimalistisk løsning for å unngå evig loading-spinner om man prøver å hente en person som ikke kan hentes (401).

NP-49212 Show error message when person cannot be fetched

---

src/pages/registration/ChannelClaimInfoBox.tsx
src/translations/nbTranslations.json

Some minor changes to helper texts.

Files and license text updates

---

src/pages/public_registration/action_accordions/MoreActionsCollapse.tsx
src/types/publication_types/ticket.types.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-49258
TIllat flytting av ticket basert på allowedOperations

NP-49258 Use allowedOperations for moving ticket

---

package-lock.json
package.json
src/Layout.tsx
src/matomo/matomo.ts
src/pages/messages/components/TicketDateIntervalFilter.tsx
src/pages/search/PublicationYearIntervalFilter.tsx
src/themes/mainTheme.ts
src/translations/nbTranslations.json

Update staging 05.06.25

---

src/pages/registration/files_and_license_tab/FilesTableRow.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-49325
Tillat studentoppgavekurator å legge til skjulte filer på studentoppgaver

NP-49325 Allow thesis curator to add hidden files to thesis'

---

README.md
src/App.tsx
src/MaintenanceModeApp.tsx
src/layout/header/Header.tsx
src/pages/errorpages/MaintenanceMessagePage.tsx
src/pages/registration/files_and_license_tab/FilesTableRow.tsx
src/utils/status-message-helpers.ts

:rocket: Ny funksjonalitet :rocket:
* Lagt til ny lisens "Bruksvilkår etter åndsverkloven" ([NP-49268](https://sikt.atlassian.net/browse/NP-49268))
* Infoside for lisensen er tilgjengelig på https://nva.sikt.no/license/copyright-act/1.0 ([NP-49268](https://sikt.atlassian.net/browse/NP-49268))
* Støtte for å vise en statusside når NVA er under teknisk vedlikehold og tjenesten ikke er tilgjengelig for sluttbrukere ([NP-49225](https://sikt.atlassian.net/browse/NP-49225))
* Tillat studentoppgavekurator å legge til skjult fil på studentoppgaver ([NP-49325](https://sikt.atlassian.net/browse/NP-49325))
:bug: Bugfiks :bug:
* Løst diverse feil som har oppstått rundt flytting av tickets, inkl tilgangskontroll for hvem som kan flytte ([NP-49258](https://sikt.atlassian.net/browse/NP-49258))
* Løst …

Update staging 13.06.25

---

src/translations/nbTranslations.json

Link to Jira issue: https://sikt.atlassian.net/browse/NP-49319
Endrer "Publiseringskurator" -> "Filkurator" og diverse relatert til dette.

Np 49319 rename to file curator

---

src/pages/public_registration/PublicPublicationContext.tsx
src/types/publication_types/artisticRegistration.types.ts
src/utils/registration-helpers.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-49347
Oppdater typen for konsert, for å unngå noen landingsider for resultat som krasjer nå.
Eks: https://dev.nva.sikt.no/registration/01974bfed512-e468969c-c4a5-4069-9851-d77618d159da
Endring av innslagene som mangler kan mangle validering i wizard, men ser ingen god løsning på det nå. Dessuten jobbes det med endringer på hele designet der på siden nå, så sikkert grait å la det være uansett.

NP-49347 Allow opening concert without place and time

---

src/pages/registration/resource_type_tab/sub_type_forms/exhibition_types/ExhibitionProductionForm.tsx

Update Exhibition table to reflect changes of `<OutputRow />`

Update exhibition table

---

src/pages/errorpages/NotFound.tsx
src/translations/nbTranslations.json

Link to Jira issue: https://sikt.atlassian.net/browse/NP-49308
La ikke inn knappen, ref samtale i standup.

NP-49308 Updated design for 404 message

---

src/App.tsx
src/translations/nbTranslations.json
src/utils/hooks/useAuthErrorListener.ts

Vis feilmelding når innlogging feiler.

Show error message when login fails

---

src/pages/public_registration/ActionPanel.tsx
src/pages/public_registration/RegistrationLandingPage.tsx
src/pages/public_registration/log/DetailsPanel.tsx
src/translations/nbTranslations.json
src/utils/dataTestIds.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-49501
Lagt til ny tab i action-panel for "Detaljer". Inneholder for øyeblikket kun kontaktpunkt for sikt.

NP-49501 Details tab in action panel

---

src/utils/general-helpers.ts
src/utils/status-message-helpers.ts

Støtt "none" for env variables

Np 49481 handle fetching env variables

---

package-lock.json
package.json

`eslint-config-prettier` ble tatt vekk 9. juli og det har funka helt fint til nå https://github.com/BIBSYSDEV/NVA-Frontend/pull/7552
Men i dag har det dukket opp feil i konsollen pga at den pakken mangler når man prøver å starte/bygge appen. Har ingen anelse om hvorfor. Prioritere ikke å finne ut av dette akkurat nå, så legger bare inn pakken igjen, så får man senere ev. revurdere dette igjen.

Add eslint-config-prettier

---

src/components/DialoguesWithoutCuratorButton.tsx
src/components/PageWithSideMenu.tsx
src/components/SelectableButton.tsx
src/components/TicketTypeFilterButton.tsx
src/layout/header/Menu.tsx
src/pages/editor/PublisherClaimsSettings.tsx
src/pages/editor/SerialPublicationClaimsSettings.tsx
src/pages/errorpages/Forbidden.tsx
src/pages/messages/components/NviCandidatesList.tsx
src/pages/messages/components/TicketList.tsx
src/pages/public_registration/log/DetailsPanel.tsx
src/pages/registration/resource_type_tab/sub_type_forms/artistic_types/architecture/ArtisticArchitectureForm.tsx
src/pages/registration/resource_type_tab/sub_type_forms/artistic_types/design/ArtisticDesignForm.tsx
src/pages/registration/resource_type_tab/sub_type_forms/artistic_types/literary_art/ArtisticLiteraryArtForm.tsx
src/pages/registration/resource_type_tab/sub_type_forms/artistic_types/moving_picture/ArtisticMovingPictureForm.tsx
src/pages/registration/resource_type_tab/sub_type_forms/artistic_types/music_performance/ArtisticMusicPerformanceForm.tsx
src/pages/registration/resource_type_tab/sub_type_forms/artistic_types/music_performance/AudioVisualPublicationModal.tsx
src/pages/registration/resource_type_tab/sub_type_forms/artistic_types/music_performance/ConcertModal.tsx
src/pages/registration/resource_type_tab/sub_type_forms/artistic_types/music_performance/OtherPerformanceModal.tsx
src/pages/registration/resource_type_tab/sub_type_forms/artistic_types/performing_arts/ArtisticPerformingArtsForm.tsx
src/pages/registration/resource_type_tab/sub_type_forms/artistic_types/visual_arts/ArtisticVisualArtForm.tsx
src/pages/registration/resource_type_tab/sub_type_forms/exhibition_types/ExhibitionProductionForm.tsx
src/pages/reports/ReportButton.tsx
src/pages/search/selected_facets/SelectedFacetButton.tsx
src/themes/mainTheme.ts

Dropp default UPPERCASE for alle knapper
Før:
Etter:

Remove uppercase for buttons

---

src/components/NavigationListAccordion.tsx
src/components/PageWithSideMenu.tsx
src/components/SelectableButton.tsx
src/components/SideMenu.tsx
src/components/TicketTypeFilterButton.tsx
src/layout/Footer.tsx
src/layout/header/Header.tsx
src/layout/header/LanguageSelector.tsx
src/pages/messages/TasksPage.tsx
src/pages/messages/components/NviCandidatesNavigationAccordion.tsx
src/pages/my_page/MyPagePage.tsx
src/themes/mainTheme.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-49613
Blir fort en del filer som blir berørt av oppdateringer, så prøver å holde PR'ene så små som mulig.
Testene feiler pga a11y-warning på kontrast. Tenker det er noe som løser seg selv etter hvert, så det burde gå greit å merge inn til hovedbranchen til theme-endringer.
hovedendringer på theme:
#7633 

NP-49613 New Theme: Header, Footer and LSM

---

src/pages/basic_data/SearchForCristinPerson.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-49644
Add pagination when searching for new person to employ.
Skulle gjerne skrevet om fra `useFetch` til `useQuery` også, men ønske om å ha ut denne fort så tar ikke det nå

NP-49644 Add pagination for person search

---

src/pages/basic_data/SearchForCristinPerson.tsx

Link to Jira issue: [NP-49662](https://sikt.atlassian.net/browse/NP-49662)
Fixed person search on "Add employee", so that the result is ordered descending by best hit.
[NP-49662]: https://sikt.atlassian.net/browse/NP-49662?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Added sort parameter to person search

---

src/pages/public_registration/action_accordions/FindRegistration.tsx
src/pages/public_registration/action_accordions/FindSimilarRegistration.tsx
src/pages/public_registration/action_accordions/MoreActionsCollapse.tsx
src/pages/public_registration/action_accordions/UnpublishRegistration.tsx
src/pages/public_registration/action_accordions/merge_registrations/MergeRegistrations.tsx
src/translations/nbTranslations.json

Link to Jira issue: https://sikt.atlassian.net/browse/NP-49672
Oppdaterer sjekker, og generelle forenklinger.
Branchet ut fra, og skal inn i https://github.com/BIBSYSDEV/NVA-Frontend/pull/7685

Np 49672 update merge access rights

---

src/components/MessageForm.tsx
src/pages/messages/components/NviCandidateRejectionDialog.tsx
src/pages/public_registration/action_accordions/PendingPublishingTicketForCuratorSection.tsx
src/utils/constants.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-49699
Endre grensen for lengde på meldinger fra 160 tegn til 500 tegn.

Np 49699 update allowed text length on message

---

src/pages/basic_data/institution_admin/edit_user/UserFormDialog.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-49677
Før:
Etter:

NP-49677 Allow only persons with nin to have roles

---

src/components/merge_results/MergeResultsWizardActions.tsx
src/components/merge_results/MergeResultsWizardContent.tsx
src/components/merge_results/MergeResultsWizardFilesTab.tsx
src/components/merge_results/MergeResultsWizardStepper.tsx
src/components/merge_results/fields/CompareFiles.tsx
src/components/merge_results/fields/FileBox.tsx
src/translations/nbTranslations.json

Link to Jira issue: https://sikt.atlassian.net/browse/NP-49768
- Løses i https://github.com/BIBSYSDEV/NVA-Frontend/pull/7723

Np 49672 add files tab for results merging

---

src/translations/nbTranslations.json

Link to Jira issue: https://sikt.atlassian.net/browse/NP-49796
Bedre infomelding til bruker om man ikke får opp noen ansettelser.

NP-49796 Inform user about potential missing active customer

---

src/components/CategorySelector.tsx
src/components/DialoguesWithoutCuratorButton.tsx
src/components/RegistrationErrorActions.tsx
src/components/RegistrationIconHeader.tsx
src/components/TicketTypeFilterButton.tsx
src/pages/messages/components/NviStatusPage.tsx
src/pages/public_registration/DeletedPublicationInformation.tsx
src/pages/public_registration/PublicRegistrationContent.tsx
src/pages/public_registration/action_accordions/DeleteDraftRegistration.tsx
src/pages/public_registration/action_accordions/PublishingAccordion.tsx
src/pages/public_registration/action_accordions/UnpublishRegistration.tsx
src/pages/public_registration/details/DetailsPanel.tsx
src/pages/public_registration/public_files/FilesLandingPageAccordion.tsx
src/pages/registration/new_registration/RegistrationAccordion.tsx
src/pages/search/advanced_search/CategoryFilterDialog.tsx
src/themes/mainTheme.ts

design review theme

---

src/pages/public_registration/log/LogEntryItem.tsx
src/utils/log/logFactory.ts

Link to Jira issue: https://sikt.atlassian.net/browse/NP-49823
Nytt ikon for å vise at et resultat er avpublisert

NP-49823 Update icon for unpublished event

---

src/components/PageWithSideMenu.tsx
src/components/RegistrationList.tsx
src/components/SelectableButton.tsx
src/pages/basic_data/institution_admin/edit_user/ViewingScopeChip.tsx
src/pages/my_page/MyPagePage.tsx
src/pages/my_page/user_profile/MyFieldAndBackground.tsx
src/pages/my_page/user_profile/MyProfile.tsx
src/pages/my_page/user_profile/ProfilePictureUploader.tsx
src/pages/my_page/user_profile/UserRoleAndHelp.tsx
src/pages/my_page/user_profile/UserRoles.tsx
src/pages/my_page/user_profile/styles.ts
src/pages/my_registrations/MyRegistrations.tsx
src/pages/research_profile/ResearchProfile.tsx
src/themes/mainTheme.ts

theme: update MyPage

---

.github/pull_request_template.md

More details instructions when creating a pull request?

Enhance pull request template

---

src/components/AuthorName.tsx
src/components/OrganizationAccordion.tsx
src/components/SideMenu.tsx
src/components/merge_results/MergeResultsWizardActions.tsx
src/components/merge_results/fields/CompareFields.tsx
src/components/merge_results/fields/CompareFiles.tsx
src/pages/basic_data/app_admin/CustomerInstitutionAdminsForm.tsx
src/pages/basic_data/app_admin/CustomerInstitutionList.tsx
src/pages/basic_data/app_admin/CustomerInstitutionMetadataForm.tsx
src/pages/basic_data/app_admin/UpsertNviPeriodDialog.tsx
src/pages/basic_data/app_admin/central_import/CentralImportDuplicationCheckPage.tsx
src/pages/basic_data/app_admin/central_import/DuplicateSearchFilterForm.tsx
src/pages/basic_data/institution_admin/FindPersonPanel.tsx
src/pages/basic_data/institution_admin/edit_user/AffiliationFormSection.tsx
src/pages/basic_data/institution_admin/edit_user/AreaOfResponsibility.tsx
src/pages/basic_data/institution_admin/edit_user/UserFormDialog.tsx
src/pages/basic_data/institution_admin/person_register/PersonTableRow.tsx
src/pages/editor/AddChannelClaimDialog.tsx
src/pages/editor/ChannelClaimTable.tsx
src/pages/editor/ChannelClaimTableRow.tsx
src/pages/editor/PublisherClaimsSettings.tsx
src/pages/editor/SerialPublicationClaimsSettings.tsx
src/pages/project/project_wizard/styles.ts

[TODO: Describe what this PR solves - how it was before, why this is being changed, and how it is after the change. Add pictures to clarify if necessary.]
Affected part of the application: [Insert URL]
[TODO: Assume the code reviewer have never seen this part of NVA, and provide step-by-step instructions on how to access the changes (with URLs), what to look for and how to test them if it requires user action. Add pictures to clarify if necessary.]

NP-49784 theme basic data

---

src/pages/messages/components/TicketList.tsx
src/pages/public_registration/action_accordions/TicketAssignee.tsx

Link to Jira issue: https://sikt.atlassian.net/browse/NP-49870
Sørger for at bare studentoppgavekuratorer kan settes som ansvarlig for studentoppgaver, etc.
Affected part of the application: http://localhost:3000/tasks/dialogue
1. Sjekk at man kan velge studentoppgavekuratorer som "Kurator" om man har denne rollen selv
2. Sjekk at man kan velge studentoppgavekurator som ansvarlig for studentoppgave

Np 49870 tickets for thesis curator

---

src/components/styled/Wrappers.tsx
src/pages/frontpage/CategorySection.tsx
src/pages/frontpage/FrontPage.tsx
src/pages/frontpage/FrontPageHeading.tsx
src/pages/frontpage/NvaDescriptionSection.tsx
src/pages/frontpage/SearchSection.tsx
src/pages/frontpage/TypeCard.tsx
src/pages/frontpage/styles.ts

Link to Jira issue: [NP-49871](https://sikt.atlassian.net/browse/NP-49871)
Affected part of the application: [Front page](http://localhost:3000/new-front-page)
Improved the responsiveness of the front page with Maylis new mobile designs as guide.
[NP-49871]: https://sikt.atlassian.net/browse/NP-49871?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Improve mobile view

---

src/components/RegistrationList.tsx
src/components/StatusChip.tsx
src/components/TicketTypeFilterButton.tsx
src/components/institution/UnconfirmedOrganizationBox.tsx
src/pages/messages/components/DeleteIconButton.tsx
src/pages/messages/components/DoiRequestMessagesColumn.tsx
src/pages/messages/components/NviCandidateActions.tsx
src/pages/messages/components/NviCandidateRejectionDialog.tsx
src/pages/messages/components/PublishingRequestMessagesColumn.tsx
src/pages/messages/components/SupportMessagesColumn.tsx
src/pages/messages/components/TicketListItem.tsx
src/pages/public_registration/DeletedPublicationInformation.tsx
src/pages/public_registration/PublicRegistrationContent.tsx
src/pages/public_registration/action_accordions/DoiRequestAccordion.tsx
src/pages/public_registration/action_accordions/PendingPublishingTicketForCuratorSection.tsx
src/pages/public_registration/action_accordions/UnpublishRegistration.tsx
src/pages/public_registration/public_files/FilesLandingPageAccordion.tsx
src/pages/public_registration/public_files/PendingFilesInfo.tsx
src/pages/registration/contributors_tab/components/ContributorRow.tsx
src/themes/mainTheme.ts

Link to Jira issue: https://miro.com/app/board/uXjVJMc5b0Y=/?moveToWidget=3458764642366947675&cot=14
Fix intruding colors
Affected part of the application: [Insert URL]
Check the following pages as seen in the miro board:
- Registration Landing Page
- Tasks Page
- Contributors Panel in registration Wizard

change popping colors
