BIBSYSDEV/NVA-Frontend

.gitignore
Vet ikke hvorfor denne ble fjernet, men env.local skal ignoreres
=> ignore env.local

src/translations/en/formikValues.json, src/translations/nb/formikValues.json
både publicationType og publicationSubtype heter bare `type`, så jeg oversetter de manuelt, slik at brukeren forstår (mer om) hvilken type det er
=> use same translation keys as tabs

src/pages/publication/references_tab/components/PublisherField.tsx
Seperate Backend-tasks for å fikse mangel av title og level som enum-verdi.
Denne tillater bare å nullstille valg av publisher
=> NP-746 Allow removing selected publisher

src/pages/publication/SubmissionPanel.tsx, src/types/publicationFieldNames.ts
Siden denne sjekken kun avgjør om faneoverskriftene skal ha rødfarge eller ikke, så tenker jeg at det holder å sjekke på kun de feltene som er required. og ikke loope igjennom alle felt.
=> check only required field names when navigating to submission tab

src/pages/publication/contributors_tab/components/AffiliationsCell.tsx, src/translations/en/publication.json, src/translations/nb/publication.json
Vi har ikke labels på affiliations som kommer forhåndsutfylt basert på authority, så forekler bare meldingen heller enn å trikse til med å gjøre enda ett kall per affiliation for en filleting
=> NP-903 Fix bug where modal text was incomplete

CODEOWNERS
https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners#about-code-owners
"Code owners are automatically requested for review when someone opens a pull request(...)"
=> Set codeowners to set default reviewers

src/pages/publication/PublicationForm.tsx
RouteLeavingGuard caused this bug. And it's not right that the user should be interrupted if a publication is not valid (since it is permitted to save changes with missing fields)
=> Np 1613  bugfix wrong navigation

src/pages/publication/PublicationForm.tsx, src/pages/publication/PublicationFormContent.tsx, src/pages/publication/SubmissionPanel.tsx, src/utils/validation/publication/fileValidation.ts
Feltene ble ikke satt riktig til touched om man hadde en link som gikk direkte til Summary tab (fra DoiRequest, feks).
Oppdaterte også validering, slik at `embargoDate` ikke gir feilmelding for at den må være i fremtiden hvis publikasjonene allerede er publisert
=> Np 1607 validate tabs

src/pages/worklist/DoiRequestAccordion.tsx, src/types/registration.types.ts
Fikser bug hvor man ikke kunne åpne Mine Meldinger om man har en DoiRequest uten noen meldinger.
Dukket opp  pga  /publication/{identifier} og /doi-request ikke returnerer det samme. F.eks. identifier: c2dc2e63-0331-493a-840d-6cd2e3a86baa gir dette:
/publication  -> doiRequest.messages: undefined
/doi-request -> doiRequest.messages: []
Har nevnt dette til @axthosarouris , og at vi foretrekker `[]` i sånne tilfeller
=> Handle undefined messages

src/pages/registration/ReferencesPanel.tsx, src/utils/registration-helpers.ts
Bug hvor man ikke kunne lagre type som ikke har `peerReviewed` om den tidligere var satt til true for en annen type
=> NP-2145 Allow saving type without peer review field after setting it to true

src/pages/registration/DescriptionPanel.tsx, src/pages/registration/description_tab/DatePickerField.tsx, src/pages/registration/description_tab/projects_field/ProjectsField.tsx
MUI trenger visst `id` for å kunne koble id til felt opp mot `id` til label.
Date-picker manglet litt mer i tillegg.
Firefox hevder Autocomplete for prosjekt og nøkkelord fortsatt mangler label, men ser riktig ut i DOMen for meg, så lar det ligge...
=> Np 2395 description labels

src/components/LinkTab.tsx, src/pages/registration/RegistrationFormTabs.tsx
Syns Tabs var mye bedre enn Stepper på mobil i tillegg til at det ser litt ryddigere ut generelt, så tror vi kan fortsette med Tabs litt til. 
Kode for Stepper:
```
<Stepper activeStep={tabNumber} nonLinear alternativeLabel>
<Step>
<StepButton title={t('heading.description')} onClick={() => setTabNumber(RegistrationTab.Description)}>
<StepLabel error={tabErrors[RegistrationTab.Description].length > 0}>{t('heading.description')}</StepLabel>
</StepButton>
</Step>
<Step>
<StepButton title={t('heading.resource_type')} onClick={() => setTabNumber(RegistrationTab.ResourceType)}>
<StepLabel error={tabErrors[RegistrationTab.ResourceType].length > 0}>
{t('heading.resource_type')}
</StepLabel>
</StepButton>
</Step>
<Step>
<StepButton title={t('heading.contributors')} onClick={() => …
```
=> NP-2396 Add accessible title to error icon

src/types/registration.types.ts
Tidligere endring førte til ugyldige verdier for level, som ga 500-error ved lagring
=> Revert renaming of level values

src/App.tsx, src/api/authorityApi.ts, src/pages/user/UserAffiliations.tsx, src/pages/user/UserOrcid.tsx, src/pages/user/authority/ConnectAuthority.tsx, src/pages/user/institution/InstitutionCard.tsx
Unngå å oppdatere FeideID hvis bruker allerede har det. Dette skjedde i tilfeller hvor bruker hadde 2 matchende brukere i ARP
=> NP-3120 Avoid redundant POST when user already has feide id

cypress/integration/search.spec.js, src/pages/search/SearchBar.tsx, src/pages/search/filters/AdvancedSearchRow.tsx, src/translations/en/search.json, src/translations/nb/search.json, src/utils/searchHelpers.ts
Bruk `"` for search term.
Sikre at riktig søketerm blir brukt som fritekstsøk.
Bruk placeholder i stedet for helperText.
++
=> Np 3466 allow parentheses in search

src/components/ErrorBoundary.tsx, src/translations/en/common.json, src/translations/nb/common.json
Håndter feil for brukere som har appen oppe mens det rulles ut en ny versjon. Tving brukere som får feilmelding pga lazy loading av komponeneter til å laste siden på nytt.
=> NP-3525 Handle error due to new deploys

src/components/PageWithSideMenu.tsx, src/components/RegistrationList.tsx, src/components/landing_page/LandingPageAccordion.tsx, src/components/styled/Wrappers.tsx, src/pages/dashboard/Dashboard.tsx, src/pages/my_page/user_profile/ResearchProfilePanel.tsx, src/pages/public_registration/public_files/FilesLandingPageAccordion.tsx, src/pages/registration/RegistrationForm.tsx, src/pages/registration/new_registration/RegistrationAccordion.tsx, src/pages/search/person_search/PersonListItem.tsx, src/pages/search/project_search/ProjectListItem.tsx, src/themes/mainTheme.ts
Tidligere secondary.light ligger ikke i figma og var bare noe vi har lagt inn selv, så forskjyver secondary colors ett hakk, og forholder med til verdier i figma
=> Np 29038 update search item border

src/components/ConfirmDialog.tsx
Denne vil dog alltid være aktiv på alle sider som bruker `Confirm Dialog`-komponenten, som er noe uheldig.
=> NP-34958 added event listener to Confirm Dialog

src/pages/search/SearchPage.tsx, src/pages/search/registration_search/filters/RegistrationFacetsFilter.tsx
Sørg for at lange typenavn ikke går utenfor boksen, og bruk row-flexbox på mobil for typer
=> Minor layout changes for search page

src/pages/my_page/user_profile/UserOrcid.tsx
Hele `UserOrcid` og flyten her er subotimal i utgangspunktet, men tror dette vil gjøre det greit nok. For brukeren vil det være forvirrende om lagring av orcid-data feiler, siden det skjer _etter_ at koblingen til Orcid har lyktes. Da blir det på en måte missvisende at man får en feilmelding, men syns dette er greit nok for nå.
=> Np 44640 store orcid credentials simplifications

src/pages/messages/MessageList.tsx
Forrige visning ble veldig rar når to personer med ulik lengde på navnet snakket sammen, så flytter nå navnet til en egen rad. Ingen scrollbar atm, så siden blir uendelig lang når det er uendelig antall medlinger.
=> Np 42253 update messages view

cypress.config.ts
Ser ut som det noen ganger feiler pga av noe treghet med `cy.setUserRolesInRedux([])`. Klarer ikke se noen grunn til hvorfor, og den metoden var uansett bare en enkel workaround for basic testing av tilgangskontroll, så legger inn retries i stedet for å knote i timesvis med det
=> Retry cypress test 3 times on fail

cypress/support/commands.ts
Forrige forsøk (https://github.com/BIBSYSDEV/NVA-Frontend/pull/4079) ser ut til å løse problemet for akkurat den, men da er det noen andre tester som sklir ut igjen... Prøver på ny. Om dette virker kan vi vurdere om vi ønsker å revertere det forrige forsøket
=> Wait after cypress updates redux due to flaky tests

src/pages/basic_data/BasicDataPage.tsx, src/pages/basic_data/app_admin/central_import/CentralImportDuplicateSearch.tsx, src/pages/basic_data/app_admin/central_import/CentralImportDuplicationCheckPage.tsx, src/pages/basic_data/app_admin/central_import/CentralImportPage.tsx, src/pages/basic_data/app_admin/central_import/CentralImportResultItem.tsx, src/pages/basic_data/app_admin/central_import/DuplicateSearchFilterForm.tsx, src/themes/mainTheme.ts, src/translations/enTranslations.json, src/translations/nbTranslations.json, src/translations/nnTranslations.json, src/types/importCandidate.types.ts, src/utils/testfiles/mockImportCandidate.ts
Finpuss av resultatvisning etc for sentralimport. Faktisk importflyt kommer i senere PRs
Dette kunne nok med fordel vært delt opp i flere PRs..
=> NP-45023 Update design of central import search hit

src/pages/search/registration_search/RegistrationSearchBar.tsx, src/pages/search/registration_search/filters/RegistrationFacetsFilter.tsx, src/types/registration.types.ts
Aggregeringene har en tendens til å forsvinne og bytte navn, så setter alt til optional slik at frontend ikke krasjer når det skjer
Fortsettelse av hotfix: https://github.com/BIBSYSDEV/NVA-Frontend/pull/4537
=> Handle missing aggregation values

src/pages/research_profile/ResearchProfile.tsx, src/utils/hooks/useSearchRegistrations.ts
Unngå at overskriften `Resultat (undefined)` flasher, og gå over til `react-query`.
=> Fetch registrations with react-query

src/pages/messages/components/NviCandidatePage.tsx, src/translations/nbTranslations.json
Backend mangler støtte for avvisningsnotat for nå
=> NP-45290 Reject NVI candidate

src/pages/search/SearchPage.tsx, src/pages/search/registration_search/RegistrationSearchBar.tsx
Før:
Etter:
Usikker på om vi ønsker innrykk på alt, men dette er en veldig rask løsning for å fikse bugen i hvert fall, så kan vi fikse designet i etterkant
=> Np 45532 advanced filters layout

src/pages/public_registration/public_files/FileRow.tsx
Safari på iOS krever at man åpner eksterne domener på main thread, så dette er en workaround for at det skal virke på alle enheter.
=> Open files in iOS Safari

src/App.tsx, src/components/EnvironmentBanner.tsx, src/translations/nbTranslations.json, src/utils/constants.ts
Normal:
Mimimert:
Kan også fjernes ved å sette `environmentBanner: none` i localstorage.
Kan lure seg rundt dette ved å trikse med `hosts`-fila e.l. for å manipulere URL, men hva har man å tjene på det 🤷‍♂️
=> Np 45655 test env banner

src/pages/public_registration/public_files/FileRow.tsx
=> Wrap long file names

src/pages/messages/components/NviCandidateListItem.tsx, src/pages/messages/components/NviCandidatePage.tsx, src/pages/messages/components/NviCandidatesList.tsx, src/types/nvi.types.ts
Her bruker vi `offset=0` for den første kandidaten, og har dermed samme offset/terminologi som søke-API
=> Use same offset as search API for NVI candidates

src/pages/registration/new_registration/LinkRegistration.tsx
Url parameters are case sensitive, which means that toLowerCase() will return 404 whenever provided url contains upper case letters.
=> NP-45938 Remove toLowerCase() from doi url start

package-lock.json, package.json, src/pages/public_registration/PublicPublicationContext.tsx, src/pages/public_registration/PublicPublicationInstance.tsx, src/utils/validation/registration/referenceValidation.ts
Erstatt https://www.npmjs.com/package/isbn-utils med https://www.npmjs.com/package/isbn3, da førstnevte er gammel og viser seg og å ikke håndtere alle ISBNer
=> NP-46004 Fix ISBN parsing bug

CODEOWNERS
Misforsto presedensen i `CODEOWNERS`, da det viser seg at den siste tar presedens (ikke første som jeg trodde). Da håper jeg dette gjør at alle ikke settes til assignee for PRs fra dependabot
=> Limit who is set as assignee to version bumps

.lintstagedrc
Unngå error på prettier fra pre-commit hook når vi committer filer som ikke har noen prettier formatter, som feks `CODEOWNERS`, `.svg`, etc
=> NP-46943 Ignore special files on pre-commit prettier hook

src/pages/basic_data/app_admin/central_import/CentralImportResultItem.tsx, src/types/importCandidate.types.ts
Håndter `UnconfirmedOrganization` på importkandidat. Egen task på backend å ekspandere `organization` i søket, slik at også bekreftede orgs vil vises som forventet.
=> Handle UnconfirmedOrganization on import candidate

src/pages/public_registration/public_files/preview_file/PreviewFile.tsx, src/types/associatedArtifact.types.ts
Unngå at importerte filer uten mime-type krasjer. eks: https://dev.nva.sikt.no/registration/018d365a3dea-a241879e-89d4-40cb-bd43-1313596752f8
=> Handle empty mime type

src/QueryProvider.tsx, src/pages/public_registration/RegistrationLandingPage.tsx
Misliker løsningen sterkt, men beste jeg kommer opp med sånn flyten er nå (i nøden spiser fanden fluer). I praksis blir det en workaround for å erstatte `onError` som er deprecated, og fjernet i v5.
Jeg mener at dette ikke skal påvirke noe annet enn de ytterst få tilfellene som faktisk vil returnere `410 Gone` med dette
=> NP-45607 Handle error based on response

src/components/ListPagination.tsx, src/components/ListPaginationCounter.tsx, src/components/ListPaginationTop.tsx, src/pages/search/CristinSearchPagination.tsx, src/pages/search/person_search/PersonSearch.tsx, src/pages/search/project_search/ProjectSearch.tsx, src/pages/search/registration_search/RegistrationSearch.tsx
This is a temporary fix until the entire `<ListPagination />` component is altered to wrap lists instead of being appended to lists.
Project and Person search utilizes a `<CristinSearchPagination />` component as a middle man in between the search page and the `<ListPagination />` component. Therefore, the shared code for this component and the newly created `<ListPaginationTop />` component had to be pulled up a layer.
=> NP-46072 Add list item counter above search lists

src/pages/registration/FilesAndLicensePanel.tsx, src/translations/nbTranslations.json, src/types/license.types.ts
- Only show version 4 licenses, CC0 and RightsReserved in helper modal for licenses.
- Adding helper text at the top of the modal
- Adding a paragraph to RightsReserved description
=> Np 45740 show relevant licenses

src/components/ListPagination.tsx, src/components/ListPaginationBottom.tsx, src/components/ListPaginationCounter.tsx, src/components/ListPaginationTop.tsx, src/pages/basic_data/app_admin/UserList.tsx, src/pages/basic_data/app_admin/central_import/CentralImportDuplicateSearch.tsx, src/pages/basic_data/app_admin/central_import/CentralImportPage.tsx, src/pages/basic_data/institution_admin/person_register/PersonRegisterPage.tsx, src/pages/editor/EditorCurators.tsx, src/pages/messages/components/NviCandidatesList.tsx, src/pages/messages/components/TicketList.tsx, src/pages/my_page/user_profile/MyProjectRegistrations.tsx, src/pages/my_page/user_profile/MyProjects.tsx, src/pages/my_page/user_profile/MyResults.tsx, src/pages/my_registrations/MyRegistrationsList.tsx, src/pages/projects/ProjectResultsAccordion.tsx, src/pages/projects/RelatedProjects.tsx, src/pages/registration/contributors_tab/Contributors.tsx, src/pages/registration/contributors_tab/components/AddContributorForm.tsx, src/pages/research_profile/ResearchProfile.tsx, src/pages/search/CristinSearchPagination.tsx, src/pages/search/person_search/PersonSearch.tsx, src/pages/search/project_search/ProjectSearch.tsx, src/pages/search/registration_search/RegistrationSearch.tsx
- Rewrite the `<ListPagination /> `to be a wrapper for lists instead of an appendable component. Reason being that this gives better control for when pagination controls are wanted above the lists as well.
-> As a result, the contents of `<ListPagination />` is moved to the newly created component `<ListPaginationBottom />`
- Remove the `sx` prop as it was used only twice, and instead styled those two lists themselves instead.
- Remove `aria-live="polite"` from pagination counter as pointed out in another PR.
=> NP-46072 Refactor ListPagination component to wrap lists

src/pages/editor/CuratorRow.tsx, src/pages/editor/EditorCurators.tsx
Hent kuratorer på nytt når man lukker dialogen, for å sikre at vi ikke viser utdatert data. Dette var spesielt synlig når man endret ansvarsområde, siden man fikk se gammel data når dialogen ble lukket.
=> NP-45912 Refetch curator search after updates

.husky/pre-commit, package.json
Migrer til v9 av husky, for å unngå deprecation-warnings i konsollen når man kjører `npm i` o.l.
Basert på migration guide her: https://github.com/typicode/husky/releases/tag/v9.0.1
=> Migrate to husky v9

src/pages/basic_data/institution_admin/AddEmployeePage.tsx
Ketil rapporterte feil der formen ble "låst" om brukeren trykte ENTER mens man ventet på søketreff fra personsøk
=> Disable create employment button when form data is not valid

src/pages/basic_data/institution_admin/edit_user/PersonFormSection.tsx, src/pages/basic_data/institution_admin/edit_user/UserFormDialog.tsx, src/pages/basic_data/institution_admin/person_register/PersonRegisterPage.tsx, src/pages/basic_data/institution_admin/person_register/PersonTableRow.tsx
Tillat administrator å endre på brukere som har en ugyldig ansettelse på en annen institusjon. Dette er en feil som ble introdusert ifbm endringer for ansvarsområde.
Fortsatt er det en liten bug hvor bruker ikke får se oppdatert data om man endrer i cristin-data da søket ikke er indeksert opp med riktig data raskt nok etter endring. Løser ikke dette problemet i denne saken, da problemet når er at mange ikke får til å endre på person/bruker i det hele tatt
=> Np 46195 allow edit person with external employments

src/pages/basic_data/institution_admin/edit_user/UserFormDialog.tsx
Unngå bug hvor det ikke er mulig å fjerne alle kurator-roller for en bruker.
Skulle helst vært håndtert av API IMO, men gjør dette som en funksjonell quick-fix.
=> NP-46221 Allow removing all curator roles

src/pages/search/CristinSearchPagination.tsx, src/pages/search/person_search/PersonSearch.tsx, src/pages/search/project_search/ProjectSearch.tsx, src/translations/nbTranslations.json
Sorteringskomponenten for listevisning personsøk og prosjektsøk var felles, så måtte flytte den opp et nivå for å kunne å ha forskjellig navn på sortBy uten å vikle inn logikk.
=> Rename sort by key for person search

src/pages/registration/files_and_license_tab/FilesTableRow.tsx, src/translations/nbTranslations.json, src/types/associatedArtifact.types.ts, src/types/publicationFieldNames.ts
Håndter RRS for institusjoner som har innstilling `NullRightsRetentionStrategy`. Andre innstillinger kommer som egne PRs.
- Når fil er markert som "Akseptert", tillat å marker at fil skal følge RRS til finansiør
- Velg CC-BY-lisens og disable lisensfeltet, når bruker velger RRS
=> Np 45760 null rrs

src/api/searchApi.ts, src/pages/dashboard/HomePage.tsx, src/pages/search/advanced_search/AdvancedSearchPage.tsx, src/pages/search/registration_search/RegistrationSearch.tsx, src/types/publicationFieldNames.ts
Sorter på oppgitt publiseringsår (publicationDate) i steted for når det faktisk ble publisert i NVA.
Per nå virker det bare sortinger per år, så er det en backendoppgave å fikse filtrering internt per år og noen andre mindre detaljer
=> NP-46357 Sort results on publicationDate instead of publishedDate

src/pages/messages/TasksPage.tsx
Link to Jira issue: https://unit.atlassian.net/browse/NP-46271
=> NP-46271 Default viewingscope to users deafult viewingscope when none selected

src/pages/registration/resource_type_tab/components/JournalField.tsx, src/pages/registration/resource_type_tab/components/PublisherField.tsx, src/pages/registration/resource_type_tab/components/SeriesField.tsx, src/pages/search/advanced_search/JournalFilter.tsx, src/pages/search/advanced_search/PublisherFilter.tsx, src/pages/search/advanced_search/SeriesFilter.tsx, src/translations/nbTranslations.json
Updated the placeholder tex for jounral, series and publisher search fields.
Link to Jira issue:
https://unit.atlassian.net/browse/NP-46384
=> NP-46384 Update search for series, journal and publisher placeholders

src/api/searchApi.ts, src/translations/nbTranslations.json
Link to Jira issue: https://unit.atlassian.net/browse/NP-46415
Begrens hvor mange felter som søkes på når man søker på resultat med fritekstsøk. Dette pga en feil som oppstår i APIet om vi søker på alt.
=> NP-46415 Search for distinct parameters when using query

src/components/OrganizationRenderOption.tsx, src/components/institution/SelectInstitutionForm.tsx
Removed key from li element.
Link to Jira issue:
N/A
=> Fix key for OrganizationRenderOption

src/components/NavigationListAccordion.tsx
Link to Jira issue: https://unit.atlassian.net/browse/NP-46442
Prøvde på en løsning som bare scroller til `<main>`, men syns ikke det ble helt bra heller da den noen ganger ville scrolle nedover, så da går jeg heller for en dum løsning som bare scroller til topps hver gang. Untatt på mobil, der vi har en annen visning.
=> NP-46442 Send user to top when clicking navigation accordion

src/components/NfrProjectSearch.tsx, src/pages/registration/description_tab/RegistrationFunding.tsx
Link to Jira issue: https://unit.atlassian.net/browse/NP-46437
Vis feilmelding når har et NFR-prosjekt som mangler navn.
Tok også med en forsøk på en fiks for å unngå at felter ikke blir på linje. Finner ikke noen god løsning på det, men har lagt inn forsøk på bøting i hvert fall, som bare setter inn ekstra `margin-top` for felter som har en feilmelding :/
Før:
Etter:
=> NP-46437 Fix validation of funding

.gitignore, .vscode/settings.json
Foreslår at vi tester dette som utgangspunkt. Om det er noe her noen ikke vil ha som default kan vi ta det vekk. Om man ikke ønsker i18n inline er det feks bare å ikke innstallere plugin.
1. Vis oversettelser og tillat endring inline i vscode om man har extension `i18n-ally`.
2. Organiser imports (sorter og fjern ubrukte) automatisk ved lagring.
=> Add i18n ally settings in git

src/components/AreaOfResponsibiltySelector.tsx
Link to Jira issue: https://unit.atlassian.net/browse/NP-46467
=> NP-46467 Disable area of responsibility dropdown when only one option

src/components/ListPagination.tsx, src/components/ListPaginationBottom.tsx
Link to Jira issue: https://unit.atlassian.net/browse/NP-46466
Blokker paginering over 10k treff for resultatsøk, da APIet ikke støtter dette for øyeblikket.
Forenklet props-definering litt også, for å unngå duplisering.
=> NP-46466 Handle max hits limit

src/api/cristinApi.ts, src/components/institution/SelectInstitutionForm.tsx, src/pages/basic_data/app_admin/OrganizationSearchField.tsx, src/pages/registration/description_tab/projects_field/ProjectContributorRow.tsx, src/utils/institutions-helpers.ts
Link to Jira issue: https://unit.atlassian.net/browse/NP-46448
Legg til param for om org-søk skal inkludere underenheter eller ikke. Som default vil ikke underenheter (`hasPart`) nå inkluderes i responsen
=> Np 46448 updated org api

src/components/institution/SelectInstitutionForm.tsx, src/pages/basic_data/institution_admin/edit_user/AreaOfResponsibility.tsx, src/pages/search/advanced_search/OrganizationFilters.tsx
Use `<OrganizationRenderOption />` on several Autocompletes. As of now, searh does not return the country of the organization, but BE has been notified.
Link to Jira issue: https://unit.atlassian.net/browse/NP-46483
=> NP-46483 Use OrganizationRendrOption

src/pages/search/PublicationDateIntervalFilter.tsx
Link to Jira issue: https://unit.atlassian.net/browse/NP-46487
Nullstill paginering når man endrer årstall i søk
=> Reset pagination when updating year filter

src/pages/basic_data/institution_admin/edit_user/UserFormDialog.tsx
Link to Jira issue: https://unit.atlassian.net/browse/NP-46404
Pga caching ble det noen ganger vist frem person-respons til kall uten token, som gjorde at brukere kunne fjerne alle sine ansettelser med et uhell.
=> NP-46404 Avoid missing employments due to caching

src/components/NavigationListAccordion.tsx
Link to Jira issue: https://unit.atlassian.net/browse/NP-46442
Fiks bug hvor bruker ble scrollet til toppen når man trykket på noe inni en accordion. Man skal bare sendes til toppen når man trykker på toppen av accordion
Introdusert i https://github.com/BIBSYSDEV/NVA-Frontend/pull/5381
=> Avoid excessive scrolling for accordion clicks

src/pages/editor/OrganizationOverview.tsx
Link to Jira issue: https://unit.atlassian.net/browse/NP-46389
Forbedre ytelsen av org-hierarki. Dette for å unngå treghet for brukere på store institusjoner. Forbedringene er baser på https://github.com/BIBSYSDEV/NVA-Frontend/pull/5414.
Kort sagt dropper vi rendring av alle enheter som ikke skal vises uansett, da de har en parent accordion som ikke er ekspandert.
=> NP-46389 Performance improvements for organization overview

src/redux/userSlice.ts
Link to Jira issue: https://unit.atlassian.net/browse/NP-46472
I dag kommer `custom:roles` tilknyttet en customer id, som dette: `<ROLE>@<CUSTOMER>`. For noen brukere blir dette en veldig lang streng, så vi ønsker å ta vekk `@<CUSTOMER>`, da man bare skal få rollene for den kunden man har valgt uansett. Denne PRen vil gjøre at frontend støtter begge formatene: `<ROLE1>@<CUSTOMER>,<ROLE2>@<CUSTOMER>` og `<ROLE1>,<ROLE2>`
=> NP-46472 Handle roles without attached customer

src/api/searchApi.ts, src/pages/search/advanced_search/AdvancedSearchPage.tsx
=> Exclude topLevelOrg from search when subUnnit is selected

src/pages/editor/OrganizationOverview.tsx, src/pages/search/advanced_search/OrganizationHierarchyFilter.tsx
Link to Jira issue: https://unit.atlassian.net/browse/NP-46387
Løser 3 småfeil:
- Løs bug hvor valgt enhet ikke ble vist som valgt om man åpnet dialogen på nytt. Pass samtidig på at valgt verdi blir nullstilt om bruker ikke lagrer sitt valg.
- Gi alle enhetsnivåer samme indenteringsstørrelse, i stedet for at innrykket blir større for hvert nivå
- La bruker velge en enhet med tastatur (tab og enter)
=> NP-46387 Reset unit selection only when needed

package.json
Update scripts to so we don't have to set USE_MACK_DATA manually, depending on whoch OS you are running.
=> Add sperate mock-scripts for windows and unix

src/pages/editor/EditorInstitution.tsx, src/translations/nbTranslations.json
Link to Jira issue: https://unit.atlassian.net/browse/NP-46508
Update design for read-only Institution Profile. The layout has been changed by adding a grid. Also, the following fields has been added:
- institution sector
- institution unique Feide id
- institution support link
=> Np 46508 update institution profile design

src/pages/search/advanced_search/OrganizationFilters.tsx
Link to Jira issue: [NP-46388](https://unit.atlassian.net/browse/NP-46388)
I avansert søk, legger inn brukers institusjon som default dropdown-opsjon før man gjør et spesifikt søk. Dette fordi bruker i de fleste tilfeller ønsker å filterer på sin institusjon.
NB: Hvis man har søkt og valgt en annen institusjon, så vil brukers institusjon fortsatt vises som opsjon i dropdown. Litt usikker på om dette er ønsket eller ikke, så tenker å la PO teste selv.
[NP-46388]: https://unit.atlassian.net/browse/NP-46388?atlOrigin=eyJpIjoiNWRkNTl …
=> NP-46388 Prefill users institution in dropdown on advanced search

src/types/customerInstitution.types.ts, src/utils/testfiles/mockCustomerInstitutions.ts
Avhenger av https://github.com/BIBSYSDEV/nva-identity-service/pull/360
Disse endringene virker som før inntil APIet støtter dette via create. Så om det legges til i frontend først slipper vi å samkjøre noe utrulling. Foreløpig skal alle ha støtte for support requests som default, så vil det komme muligheter for å justere dette senere for admin.
=> Set generalSupportEnabled for customers

src/pages/public_registration/LogPanel.tsx, src/translations/nbTranslations.json, src/types/publication_types/ticket.types.ts
Link to Jira issue: [NP-46187](https://unit.atlassian.net/browse/NP-46187)
Legger til filnavn i logginnslag for publiserte filer. Dersom filen er slettet vil teksten "slettet" stå istedenfor. Når filnavn er for lange kortes de med "..." (ellipsis). Legger på tooltip på filnavn, slik at man ser hele navnet dersom det er for langt (med mindre filen er slettet, da er det ingen tooltip-tekst).
Har også sneket inn tooltip med klokkelsett på dato for logginnslag. 
[NP-46187]: …
=> NP-46187 Add file names to log entries

src/api/apiPaths.ts, src/api/mock-interceptor.ts, src/components/RegistrationList.tsx, src/components/styled/Wrappers.tsx, src/pages/basic_data/app_admin/InstitutionList.tsx, src/pages/search/project_search/ProjectListItem.tsx, src/utils/dataTestIds.ts, src/utils/institutions-helpers.ts, src/utils/testfiles/mock_feide_user.ts
Blander 3 småting i denne PRen:
1. Fjern gammel, ubrukt, API-path for ticket søk
2. Liten fiks for å håndtere at customer mangler navn, som ikke skal skje, men som har skjedd i sandbox. Mest for å ikke blokkere andre.
3. Fiks farge på søketreff, da det ble rart på forskerprofilen når resultat og projsjekt fikk ulik bakgrunnsfarge.
Før:
Etter:
=> Ensure all search hits has same color

src/pages/public_registration/LogPanel.tsx, src/translations/nbTranslations.json
Link to Jira issue: [NP-46613](https://unit.atlassian.net/browse/NP-46613)
Legger til et logginnslag i toppen av logglisten som viser totalt antall arkiverte filer på registreringen. Dersom det ikke er noen arkiverte filer så vises ikke logginnslaget.
[NP-46613]: https://unit.atlassian.net/browse/NP-46613?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> NP-46613 Add log entry for archived files

src/pages/registration/description_tab/RegistrationFunding.tsx
Link to Jira issue: https://unit.atlassian.net/browse/NP-46609
Fixed problem where the click area for the remove-button for funding was too big.
=> NP-46609: Fixed too large click area on remove funding-icon

src/types/registration.types.ts, src/utils/registration-helpers.ts
Link to Jira issue: https://unit.atlassian.net/browse/NP-45742
Importkandidat har ikke `allowedOperations`, så setter det til optional for å unngå at det krasjer i wizard for importkandidat
=> NP-45742 Handle missing allowedOperations for import candidates

src/pages/public_registration/action_accordions/DeletePublication.tsx, src/pages/public_registration/action_accordions/PublishingAccordion.tsx, src/translations/nbTranslations.json
Link to Jira issue: [NP-46254](https://unit.atlassian.net/browse/NP-46254)
Egentlig var det kritiske med denne oppgaven å ta i bruk AllowedOperations for å bestemme om man skal vise avpubliseringsknappen eller ikke. Men det viser seg at vi allerede bruker den, og da må det være en backen issue at denne knappen vises selv om det finnes publiserte filer på registreringen.
Har ellers lagt til hjelpetekst over avpubliseringsknappen, og hjelpetekst dersom bruker ikke har tilgang til å avpublisere.
Har også gjort om de tre prikkene til `<ExpandMore />` og  `<ExpandLess />` ikoner fra mui, og gjort hele feltet toggle-bart, da dette også var i skissene. Gjorde toggle-ikonene ganske små for at det skulle passe designet i skissene, men si ifra om trykkflaten har blitt altfor liten.
Ensure that the …
=> Np 46254 Show helper text for unpublishing registration

src/pages/messages/TasksPage.tsx, src/pages/my_page/MyPagePage.tsx
Inkluder aggregeringer når man søker på tickets. Tidligere var dette enabled by default, men det er nå endret til at du aktivt må si at de skal inkluderes.
=> Include aggregations on tasks

src/pages/registration/FilesAndLicensePanel.tsx, src/pages/registration/files_and_license_tab/FilesTableRow.tsx, src/translations/nbTranslations.json
Link to Jira issue: [NP-46252](https://unit.atlassian.net/browse/NP-46252)
Disable editering av fil i wizard når filen er publisert, så lenge man ikke kan avpublisere hele registreringen (dvs. er publishing-curator).
[NP-46252]: https://unit.atlassian.net/browse/NP-46252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> NP-46252 Disable file edit when published

src/pages/public_registration/PublicGeneralContent.tsx, src/types/registration.types.ts, src/utils/registration-helpers.ts
Link to Jira issue: https://unit.atlassian.net/browse/NP-46689
Display the parent domain of the NPI Subject on certain registration types.
=> NP-46689 show field and subject

src/pages/registration/FilesAndLicensePanel.tsx
Link to Jira issue: [NP-46748](https://unit.atlassian.net/browse/NP-46748)
Etter nedlåsning av publiserte filer, viser det seg at også importkanditater bruker samme filkomponent. Ettersom importkanditater ikke har allowedOperations, feilet hele rettighetssjekken. Gjør nå heller en sjekk på om man er import-curator dersom det er en importkandidat man holder på med.
[NP-46748]: https://unit.atlassian.net/browse/NP-46748?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> NP-46748 Unlock file edit for import candidates

src/pages/registration/resource_type_tab/components/NpiDisciplineField.tsx, src/pages/registration/resource_type_tab/sub_type_forms/BookForm.tsx, src/pages/registration/resource_type_tab/sub_type_forms/ChapterForm.tsx, src/utils/validation/registration/registrationValidation.ts
Link to Jira issue: [NP-46758](https://unit.atlassian.net/browse/NP-46758)
Gjør NPI fagfelt obligatorisk kun for NVI-kategorier. Dette betyr at det kun er obligatorisk for "Vitenskapelig monografi" og "Vitenskapelig kapittel".
[NP-46758]: https://unit.atlassian.net/browse/NP-46758?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> NP-46758 Gjør NPI fagfelt obligatorisk kun for NVI-kategorier

src/pages/my_page/user_profile/MyProfile.tsx, src/pages/registration/DescriptionPanel.tsx, src/pages/search/advanced_search/LanguageFilter.tsx, src/utils/registration-helpers.ts
Unngå at bruker må laste ned noen overflødige chunk. I dette tilfellet fjernes behovet for `DescriptionPanel` når man åpner fremsiden. Vi har nok fortsatt mange plasser hvor vi kan bedre oss her, uten at jeg har oversikt over hvor stort omfanget er. Mulig vi burde vurdere å ha lazy-loading av alle sider per underside også (Min side, Oppgaver, Grunndata) for å minimere enda mer hvor mange chunks som må lastes ned. Men mulig vinninga går opp i spinninga om vi drar det for langt også 🤷
=> Optimize chunking

src/pages/my_page/user_profile/MyFieldAndBackground.tsx, src/pages/research_profile/ResearchProfile.tsx, src/types/keywords.types.ts, src/types/user.types.ts
After implementing the new changes to `Keywords`, there was a mismatch between the types used in the registry for keywords and the model of `CristinPerson`. This has been adressed by mapping the values that are returned from `person` to the new type.
=> map returned keywords from person to new model

src/pages/basic_data/app_admin/central_import/CentralImportResultItem.tsx, src/pages/basic_data/app_admin/central_import/ImportCandidateChannelName.tsx, src/translations/nbTranslations.json, src/types/importCandidate.types.ts
Link to Jira issue: https://unit.atlassian.net/browse/NP-46672
Vis tidsskrift og kanal for hvor en importkandidat er publisert. Avhenger av en oppdatering i backend for at alle kanaler skal ha navn, men har foreløpig lagt inn `id` som en fallback, så vi ser at det virker. Skal automatisk bli rett når APIet returnerer riktig data.
EDIT: Dette førte til problemer med mobilvisning igjen, så jeg dropper det istedet, og viser `Tidsskrift/Utgiver mangler` når APIet ikke oppgir noe navn. Da vil mange av kandidatene si at de mangler kanal inntil dette løses i backend, men tenker det er bedre.
_Note: some of these criterias may not …
=> Np 46672 show import candidates channel

src/pages/registration/contributors_tab/Contributors.tsx, src/pages/registration/contributors_tab/components/ContributorRow.tsx, src/translations/nbTranslations.json
Link to Jira issue: [Remove "Identification"-column](https://unit.atlassian.net/browse/NP-46793)
In contributor-view, I removed the identification-column, and moved the circular indicator into the name-column.
=> Removed identification column and moved indicator

src/components/NpiLevelTypography.tsx, src/pages/public_registration/PublicPublicationContext.tsx
Link to Jira issue: https://unit.atlassian.net/browse/NP-46650
Added a new prop to `NpiLevelTypography` which takes in the id of the publisher, and then extracts the year of which the NPI-value derives from. The year is only displayed on the Registration Landing Page, and not in the selector on the wizard.
=> NP-46650 Added year to NPI-value on LandingPage

src/pages/messages/components/TicketDateIntervalFilter.tsx
Link to Jira issue: https://unit.atlassian.net/browse/NP-46839
Previously, when entering a date manually in the Date Range filter on TasksPage, the query triggered straight away. Fixed the issue by adding a regex to check if the year in the date has 4 digits before triggering.
=> NP-46839 Fix date-picker on tasks page

src/pages/registration/description_tab/DatePickerField.tsx, src/utils/date-helpers.ts
Link to Jira issue: https://unit.atlassian.net/browse/NP-46884
Håndter veldig gamle datoer (feks år 0). Som regel en feil av registrator, men vi må håndtere det. Klarte å reprodusere bugen som er i prod ved å skrive "2024" uten å velge "Kun årstall" i wizarden. Selv syns jeg faktisk koden ble mer lesbar selv om vi nå gjør mer manuelt. Flyten endres litt, men ser ut til å virke som det skal der jeg har sjekket.
Bakgrunn:
`new Date(4, 1, 1)` blir til `01.02.1904`, mens vi ønsker at det skal bli `01.02.0004`. Beste måten jeg har funnet på å løse dette er å lage date basert på ISO streng (som vi da først må lage :( ). Dette er veldig corner case som jeg ikke har lyst til å legge inn overalt, men har lagt det inn på fremvising av dato og i wizard nå, sånn at folk ser at dette er feil, og kan …
=> NP-46884 Handle very old dates

src/components/NpiLevelTypography.tsx
Oppdaget at det hadde sneket seg med et mellomrom etter NPI årstall i forrige PR.
=> Remove trailing space after NPI year

src/redux/userSlice.ts
Fjern håndtering av gammelt format for rollestrengen man får etter innlogging. Backend oppdaterte dette i alle miljø for noen måneder siden.
Bakgrunn: https://github.com/BIBSYSDEV/NVA-Frontend/pull/5428
=> Remove support for old role string

.eslintrc.cjs
Gi warning i stedet for error for ubrukte variabler. Dette for å unngå at lokal kjøring stoppes når kode er i utvikling. Bygg vil fortsatt feile ved ubrukte variabler.
=> Update eslint rules

src/pages/public_registration/LogPanel.tsx, src/translations/nbTranslations.json, src/types/associatedArtifact.types.ts, src/types/publication_types/ticket.types.ts
Link to Jira issue: [NP-46764](https://unit.atlassian.net/browse/NP-46764)
Legger til logginnsalg for å vise hvem som har lastet opp hvilke filer til godkjenning. Dvs., `PublishingRequest` med status `New` eller `Pending` er lagt til.
En liten bug  dersom man laster opp filer til godkjenning i flere omganger. Da vil det ikke opprettes ticket/logginnslag for de nye filene. Må se om det er en frontend eller backend feature/bug.
Denne loggfilen har veldige voksesmerter, men gjør heller en refaktorering av hele greia når det nye designet skal implementeres.
_Note: some of these criterias may not always be relevant, and can simply …
=> NP-46764 Add log entry for file(s) uploaded by

src/api/hooks/useSearchForOrganizations.ts, src/components/OrganizationAccordion.tsx, src/components/institution/SelectInstitutionForm.tsx, src/pages/registration/contributors_tab/components/AddAffiliationModal.tsx, src/pages/registration/contributors_tab/components/AffiliationsCell.tsx, src/pages/search/advanced_search/OrganizationHierarchyFilter.tsx, src/translations/nbTranslations.json
Link to Jira issue: [New flow for "Add affiliation"](https://unit.atlassian.net/browse/NP-46798)
**New flow for "Add affiliation"**
When in the contributor view of a registration, this is the modal that pops up when you click the "Legg til tilknytning"-button:
**Old design:**
New design:
You can either search for a faculty / institute and select the search result:
Or you can select it from the list of choices:
**Implementation**
Search for institution in "Avansert søk" should be tested as well, since it is now sharing a component with this code.
Note:
When searching for insitution for the first time we get an error in the console. This was there before this PR as well, but we should have a look at it in a later issue / bug:
Ensure that the changes are aligned with the expectations of …
=> New flow for "Add affiliation"

src/components/TicketListDefaultValuesWrapper.tsx, src/pages/messages/TasksPage.tsx
Link to Jira issue: https://unit.atlassian.net/browse/NP-47021
En enkel fiks for at noen med ansvar for UiO skal kunne søke opp tickets igjen. Skulle helst gjort samme jobben her som har blitt gjort for UiO ved å bruke egen hook `useTicketSearchParams()` e.l., men prioriterer ikke den jobben akkurat nå
=> Np 47021 avoid prefilling viewing scope

src/pages/public_registration/LogPanel.tsx, src/translations/nbTranslations.json, src/types/registration.types.ts
Link to Jira issue: [NP-46760](https://unit.atlassian.net/browse/NP-46760)
Legger til importdetaljer dersom det er en importert registreting. En registrering kan importeres flere ganger fra flere kilder. 
NB: importdetaljer er ikke ferdigstilt i backend, så dersom noen ønsker å teste lokalt må man fylle ut denne listen selv (ligger i rota på registreringsobjektet).
[NP-46760]: https://unit.atlassian.net/browse/NP-46760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> NP-46760 Add import details to registration log

src/components/institution/SelectInstitutionForm.tsx
Link to Jira: [Search for english subunits name](https://unit.atlassian.net/browse/NP-47014)
Earlier when searching for subunits in the affiliations view, you would get no hits if you searched for english words while having selected norwegian as your language:
But now you do:
I added a hardcoded check for english labels as well as the already existing check for the selected language (see commit 1), but then I found out this was already done in advanced search, so I copied that solution because it was better (it included search for all languages, not just english).
_Note: some of these criterias may not always be relevant, and …
=> Subunit search now searches in english as well

src/pages/basic_data/BasicDataPage.tsx, src/pages/basic_data/app_admin/central_import/CentralImportDuplicationCheckPage.tsx, src/pages/basic_data/app_admin/central_import/CentralImportResultItem.tsx, src/pages/messages/TasksPage.tsx, src/pages/messages/components/NviMenuContent.tsx, src/pages/messages/components/TicketListItem.tsx, src/types/locationState.types.ts
Link to Jira issue: https://unit.atlassian.net/browse/NP-46935
Dette er del 1 av oppgaven. Nå vil søket husket når man går rett inn og rett ut på en kandidat.
I del 2 skal vi også huske søket etter man har fullført en import eller merget en kandidat. Ser at det blir mer komplekst så må tenke litt mer på tilnærming der, siden det invloverer flere navigeringer i ulike retninger 🤔. Resten kommer derfor som egen PR.
=> Np 46935 go back to import candidate search

src/pages/public_registration/PublicPublicationInstance.tsx
Link to Jira issue: https://unit.atlassian.net/browse/NP-46918
Vis navnet brukeren skriver inn når man velger "Annet" på valg av undertype for Kunstnerisk resultat. Tidligere virket dette bare for Design-typen.
Før:
Etter (Når bruker velger "annet" og oppgiv en verdi):
=> NP-46918 show custom artistic subtype

src/pages/registration/resource_type_tab/sub_type_forms/ChapterForm.tsx
Link to Jira issue: https://unit.atlassian.net/browse/NP-46702
Åpne for flere parent-typer når man registrerer kapittel. Dette kommer som krav da importen har mange poster som peker til andre typer enn vi har støtte for i dag. Dette vil kanskje føre til en renaming av typen "Innledning i antologi" til bare "Introduksjon" e.l., men det gjøres ikke i denne omgang da det ikke er avklart enda.
=> NP-46702 Allow all book and report types for general chapters

src/pages/registration/DescriptionPanel.tsx, src/themes/mainTheme.ts
Dukket opp en liten oppgave om å fikse småting på bidragsyter-fanen. Hovedproblemet er at det er knotete å rette sammendrag når man må scrolle mye. Også en liten sak hvor tags fikk unaturlig mye gap i noen tilfeller. Fant ikke noen veldig god løsning på sistnevnte, men mener det ble litt bedre.
Før:
Etter:
=> Update description tab styling

src/pages/messages/components/NviMenuContent.tsx
Link to Jira issue: https://unit.atlassian.net/browse/NP-46983
Løs feil hvor man mister valgt år når man trykker på et status-filter fra statussiden til NVI. Gjenbruker samme task som feilen ble introdusert.
=> Keep selected NVI year when nnavigating between candidates and status page

src/api/apiPaths.ts, src/api/hooks/useFetchNviStatus.ts, src/api/scientificIndexApi.ts, src/pages/messages/components/NviStatusPage.tsx, src/pages/messages/components/NviStatusTableRow.tsx, src/translations/nbTranslations.json, src/types/nvi.types.ts
Link to Jira issue: https://unit.atlassian.net/browse/NP-47020 (gjenbruker backend-oppgaven for dette)
Bruk nytt endepunkt for å hente NVI-status for gjeldende institusjon. Dette må gjøres for å forberede til at søket vi bruker i dag skal avgrense treff til hva brukeren har tilgang til, som ikke skal skje her. Alt skal ellers virke akkurat som før.
=> Update endpoint for fethcing NVI status

src/pages/registration/RegistrationForm.tsx
Link to Jira issue: https://unit.atlassian.net/browse/NP-47064
Dropp advarsel når man åpner wizard for et resultat med en historisk NVI-kandidate som _ikke_ har en åpen periode.
=> Show warning only for NVI candidates with open period

src/pages/public_registration/public_files/FilesLandingPageAccordion.tsx, src/translations/nbTranslations.json
Link to Jira issue: https://unit.atlassian.net/browse/NP-47000
Fikser en glipp hvor "Legg til fil"-snarvei ikke ble vist om resultatet bare bar upubliserbare filer.
=> Np 47000 show link to upload files when no files can be published

.eslintrc.cjs, src/components/ErrorBoundary.tsx, src/pages/messages/TasksPage.tsx
Link to Jira issue: https://unit.atlassian.net/browse/NP-47074
Håndter at ny versjon av appen deployes mens man bruker den. Bruker blir nå bedt om å laste inn siden på nytt, i stedet for at siden bare krasjer. Årsaken til endring er at `ract-scripts` og `vite` har ulike feilmeldinger for dette som vi må sjekke mot.
Ser at Vite har et eksempel for å håndtere dette i sin [dokumentasjon](https://vitejs.dev/guide/build#load-error-handling), men forslår at vi fortsetter med løsningen vi har i dag til det eventuelt blir et problem.
=> Np 47074 handle new deployment without crashing

src/pages/registration/resource_type_tab/SelectRegistrationTypeField.tsx
Link to Jira issue: [NP-47082](https://unit.atlassian.net/browse/NP-47082)
Earlier, if we filled out the fields for category on a new registration and then changed the category, the values in the field would disappear:
Now, if we do the same, the fields are persisted if we change within certain groups that have the same fields.
This goes for the following groups:
If we change between groups the fields will not be remembered when we return to a previous group.
If the category is "Kronikk" or "Leseinnlegg" we are now preserving the "tidsskrift"-field as well as the other fields that were also preserved earlier.
_Note: some of …
=> Category fields are persisted between choice of category if they are the same fields

src/pages/registration/DescriptionPanel.tsx, src/pages/registration/SameNameWarning.tsx, src/utils/dataTestIds.ts
Link to Jira issue: [NP-47135](https://unit.atlassian.net/browse/NP-47135)
When we get a warning that there already exists a registration with the same name and we click the link, we are now taken to the registration page instead of the search.
[NP-47135]: https://unit.atlassian.net/browse/NP-47135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Same name warning now links to registration with same name instead of search result

src/pages/public_registration/action_accordions/DoiRequestAccordion.tsx, src/pages/public_registration/action_accordions/PublishingAccordion.tsx
Link to Jira issue: [NP-46998](https://sikt.atlassian.net/browse/NP-46998)
When a publishing ticket or DOI request is rejected, the accordion on the registration landing page should be expanded:
[NP-46998]: https://sikt.atlassian.net/browse/NP-46998?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Default expanded after rejection

src/pages/public_registration/action_accordions/PublishingAccordion.tsx, src/translations/nbTranslations.json, src/utils/dataTestIds.ts
Link to Jira issue: [NP-46996](https://sikt.atlassian.net/browse/NP-46996)
For a curator we now have a new button in the task panel will take them directly to the file, license and link tab (the last).
[NP-46996]: https://sikt.atlassian.net/browse/NP-46996?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> New button in publish view leads to file panel

src/pages/public_registration/PublicPublicationContext.tsx, src/pages/registration/resource_type_tab/components/PublicationChannelOption.tsx, src/pages/search/advanced_search/JournalFilter.tsx, src/pages/search/advanced_search/PublisherFilter.tsx, src/pages/search/advanced_search/SeriesFilter.tsx, src/translations/nbTranslations.json, src/types/registration.types.ts, src/utils/registration-helpers.ts
Link to Jira issue: https://sikt.atlassian.net/browse/NP-47192 & https://sikt.atlassian.net/browse/NP-46921
- Vis kanalsøketreff i avansert søk på samme måte som i wizard (bare uten NPI-nivå)
- Vis årstall for når en kanal eventuelt ble nedlagt 
=> Np 47192 update option view for channel search

src/pages/registration/FileList.tsx, src/pages/registration/files_and_license_tab/FilesTableRow.tsx
Disse endringene retter trolig noe av det samme som i https://github.com/BIBSYSDEV/NVA-Frontend/pull/5845
Blir en nokså stor diff pga endringer med innrykk, men det som er gjort er egentlig bare:
- Slår sammen det som tidligere var flere gjentatte sjekker på om gjeldende fil var arkivert
- Gjenbruk `archived` prop, i stedet for å definere den enda en gang i child component
- Fikser på alignment på mange av elementene i fil-tabellene (se bilder)
Før:
Etter:
=> Simplify file logic and fix alignment

src/components/TicketListDefaultValuesWrapper.tsx, src/components/TicketStatusFilter.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-47223
- Oppdater default status filter for tickets til å bruke `New,Pending` for kurator.
- Fjern automatisk checking av alle checkboxer når man fjerner den siste
Avhenger av backendfiks før det kan merges: [PR](https://github.com/BIBSYSDEV/nva-search-api/pull/536) ([Jira](https://sikt.atlassian.net/browse/NP-47222))
=> NP-47223 Set New and Pending as default status filter

.eslintrc.cjs
https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/react-in-jsx-scope.md#when-not-to-use-it
> If you are using the [new JSX transform from React 17](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#removing-unused-react-imports), you should disable this rule by extending [react/jsx-runtime](https://github.com/jsx-eslint/eslint-plugin-react/blob/8cf47a8ac2242ee00ea36eac4b6ae51956ba4411/index.js#L165-L179) in your eslint config (add "plugin:react/jsx-runtime" to "extends").
=> Extend official eslint plugins instead of overwriting custom stuff

src/pages/public_registration/PublicGeneralContent.tsx, src/types/registration.types.ts
Link to Jira issue: https://sikt.atlassian.net/browse/NP-47251
Ved flere cristin-id på samme publikasjon, skal den vise frem Cristin-id'en som kommer fra Cristin og ikke den som evt. kommer fra Brage.
Eks. post med problem: https://dev.nva.sikt.no/registration/019054bb5bfb-7f200da9-40b8-4bc3-95db-646bc860d9f1
Her vises  id'en fra brage (som forøvrig er feil).
Til senere: vurdér om vi ønsker å vise frem cristin-id fra Brage i det hele tatt.
=> NP-47251-prioritise-cristin-id-from-cristin

src/pages/public_registration/action_accordions/DoiRequestAccordion.tsx, src/translations/nbTranslations.json
Link to Jira issue: [NP-47105](https://sikt.atlassian.net/browse/NP-47105)
Legger til en confirm dialog når man prøver å tildele doi på en registrering som mangler publisert fil.
[NP-47105]: https://sikt.atlassian.net/browse/NP-47105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> NP-47105 Add confirm dialog when assigning doi without files

src/utils/general-helpers.ts, src/utils/log/registrationEntryGenerator.ts
Fjerner unødvendig sjekk på om importDate er fra samme sekund som createdDate da det viste seg at buggen var basert på gammel data. Det er samme timestamp som brukes for createdDate og importDate.
=> NP-47137 Remove unnecessary check to the second when looking for regi stration created by import

src/pages/projects/ProjectContributors.tsx, src/pages/projects/form/ProjectFormPanel1.tsx, src/pages/registration/description_tab/projects_field/ProjectContributorRow.tsx, src/pages/registration/description_tab/projects_field/projectHelpers.ts, src/types/project.types.ts, src/utils/testfiles/mockProjects.ts, src/utils/validation/project/BasicProjectValidation.ts
Link to Jira issue: [https://sikt.atlassian.net/browse/NP-47147](https://sikt.atlassian.net/browse/NP-47147)
Earlier each contributor to a project would have the following attributes:
**type**: such as project manager or project contributor
**identity**: Information about the person, such as first- and last name
**affiliation**: Organization the person belongs to, such as Sikt
Now each contributor keeps the **identity**, but has a list of **roles** that contain the information of type and affiliation. 
Thus each contributor can have several roles in the project, and each role can be tied to a different organization.
**### Example**:
**Earlier**:
Each user is listed several times with different roles and / or affiliations. They were also counted several times.
**Now**:
Each user is counted …
=> Use new project contributor API-model in frontend

src/pages/registration/FileList.tsx, src/types/registration.types.ts, src/utils/registration-helpers.ts
Ta i buk ny `allowedOperation` for å bestemme om bruker har lov til å endre på publiserte filer, som ble implementert her: https://github.com/BIBSYSDEV/nva-publication-api/pull/1770
=> Use new allowed operation for editing published files

src/pages/registration/resource_type_tab/components/NviValidation.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-47274
Skjul NVI banner når bruker ikke har valgt noen kanal enda.
Før:
Etter:
=> NP-47274 Hide NVI banner when user has not yet selected channel

src/utils/log/publishingRequestGenerator.ts
Link to Jira issue: https://sikt.atlassian.net/browse/NP-47286
Unngå at dato til "Filer lastet opp" oppdateres for alle endringer på ticket. Tidligere ble den bl.a. oppdatert om kurator satte seg som assignee. Nå vil den heller gjenspeile når ticket ble opprettet, som ser ut til å samsvare med den siste opplastede fila.
Før:
Etter:
=> NP-47286 Update date for pending publishing ticket in log

src/pages/registration/FilesAndLicensePanel.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-47293
Unngå feilmelding fordi bruker legger til fil eller lenke etter å ha valgt at resultatet ikke har noen av delene. Stor diff pga ny indentering, men i realiteten er det bare lagt til en ny sjekk på `isNullAssociatedArtifact`
=> NP-47293 Block adding file after selecting NullArtifact

src/components/AssigneeSelector.tsx
Kunstig stor diff pga endring av innrykk. I praksis er bare `<Box sx={{ mb: '0.5rem' }}>` flyttet til toppen sånn at det alltid gjelder.
Før:
Etter:
=> Ensure that the assignee selector field always has a margin

src/components/Log/LogActionItem.tsx
Fiks feil for layout i loggen introdusert her: https://github.com/BIBSYSDEV/NVA-Frontend/pull/6033
I stedet for å legge inn `<div>`-en som ble fjernet, gir jeg elementet hele raden med `gridColumn: date ? undefined : 'span 2'` om det ikke skal vises noen dato bak. Da vil filnavnet få mer plass om det trengs også.
Før:
Etter:
=> Fix layout of files in log

src/pages/public_registration/PublicGeneralContent.tsx, src/pages/public_registration/PublicHandles.tsx, src/types/registration.types.ts
Link to Jira issue: https://sikt.atlassian.net/browse/NP-47328
Vis alle handles på landing page. I dag brukes `sourceName: "handle"` men det skal endres til `type: "HandleIdentifier"` i nær fremtid, gjør derfor dette future-proof ved å sjekke for begge.
=> Show all handles on landing page

src/utils/registration-helpers.ts
Link to Jira issue: https://sikt.atlassian.net/browse/NP-47333
Tillat lagring av periode uten å oppgi sluttdato. Fortsatt problemer om man bare oppgir sluttdato, men tenker det er OK for nå, siden startdato er obligatorisk. Ikke optimalt, men OK.
=> NP-47333 Allow saving Period without end date

src/pages/public_registration/PublicProjectsContent.tsx
Håndter tilfelle hvor det er noen prosjekter vi ikke får til å hente
Før:
Etter (prosjektet som ikke kunne hentes vises ikke):
=> Handle error for project lookup on landing page

src/pages/public_registration/action_accordions/DoiRequestAccordion.tsx, src/translations/nbTranslations.json
Link to Jira issue: https://sikt.atlassian.net/browse/NP-47303
Legger til hjelpetekster for å reservere DOI. Første av mange PR-er for bedring av DOI-flyt.
=> NP-47303 Add helper texts to DOI panel

src/api/hooks/useDuplicateRegistrationSearch.ts, src/pages/public_registration/action_accordions/PublishingAccordion.tsx, src/pages/registration/DescriptionPanel.tsx, src/pages/registration/ResourceTypePanel.tsx, src/translations/nbTranslations.json, src/utils/registration-helpers.ts
Link to Jira issue: [https://sikt.atlassian.net/browse/NP-47316](https://sikt.atlassian.net/browse/NP-47316)
When user creates a new registration and writes a title, we do a search to see if the same title is already registered in NVA. If it is, we display a warning message under the input field.
In this task, we are adding a similar warning field under the category field, if the registration has both the same title (and potentially the same publication date) AND the same category as another registration.
Change:
When the date is also the same, we add that into the warning:
_Note: some of these criterias may not always be …
=> Added warning message on category

src/utils/validation/registration/fundingValidation.ts
Link to Jira issue: https://sikt.atlassian.net/browse/NP-47346
Ta vekk overdreven validering av fundings.
Før:
Etter:
=> Np 47346 simplify funding validation

cypress/e2e/registration_validation.spec.ts, src/components/RegistrationList.tsx, src/pages/registration/contributors_tab/components/AddContributorForm.tsx, src/pages/registration/contributors_tab/components/AddContributorTableRow.tsx, src/translations/nbTranslations.json, src/utils/dataTestIds.ts
Link to Jira issue: [NP-47276](https://sikt.atlassian.net/browse/NP-47276)
Removed select-all-column, and changed so check on name now includes all organizations:
[NP-47276]: https://sikt.atlassian.net/browse/NP-47276?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Removed select-all-column, and changed so check on name now includes all organizations

src/utils/date-helpers.ts
Link to Jira issue: [NP-47344](https://sikt.atlassian.net/browse/NP-47344)
Fix for issue where a change on date on registration to only a year would appear to reset the date-field when navigating away from the tab and back.
The problem was that in the `getRegistrationDate` helper, we used Nullish Coalescing operator (??) to see if the month or day field was empty: `date?.month ?? '1'`. This will return '1' **only** if date?.month is null or undefined.  Thus it returned an empty string instead of 1, which made the date invalid. 
Fix was to change to Conditional (Ternary) operator: `date?.month ? date.month : '1'`. Here it returns 1 if date.month is any falsy value.
Also …
=> Fixed date handler

src/pages/projects/form/ProjectContributors.tsx
Link to Jira issue: [NP-47383](https://sikt.atlassian.net/browse/NP-47383)
Fixed bug where when we add several contributors on a project without identifying them (selecting name), the form acts buggy and the dropdown refuses to close, by disabling the add-button if there ar unidentified contributers in the form.
[NP-47383]: https://sikt.atlassian.net/browse/NP-47383?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fixed bug in project form

src/components/RegistrationErrorActions.tsx, src/pages/public_registration/action_accordions/PublishingAccordion.tsx, src/pages/public_registration/action_accordions/SupportAccordion.tsx, src/translations/nbTranslations.json
Link to Jira issue: https://sikt.atlassian.net/browse/NP-47345
Vis tilpasset streng når resultat med valideringsfeil allerede er publisert.
Før:
Etter:
=> Np 47345 validate published result text

src/components/institution/UnconfirmedOrganizationBox.tsx, src/pages/registration/contributors_tab/Contributors.tsx, src/pages/registration/contributors_tab/components/AffiliationsCell.tsx, src/pages/registration/contributors_tab/components/ContributorRow.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-47200
Disable actions for bidragsytere/tilknytninger som kan påvirke NVI om resultatet er godkjent av alle institusjoner, og det er i en åpen NVI-periode.
Før:
Etter:
Ett problem med denne: "Ensure the contrast between foreground and background colors meets WCAG 2 AA minimum contrast ratio thresholds". Men ser ikke noen enkel løsning uten å bloate ting ved å style denne annerledes enn alt annet 🤔 
=> NP-47200 Disable all NVI relevant contributor actions if it is NVI reported

src/components/styled/Wrappers.tsx, src/context/NviCandidateContext.ts, src/pages/registration/ContributorsPanel.tsx, src/pages/registration/DuplicateWarning.tsx, src/pages/registration/LockedNviFieldDescription.tsx, src/pages/registration/RegistrationForm.tsx, src/pages/registration/description_tab/DatePickerField.tsx, src/pages/registration/resource_type_tab/SelectRegistrationTypeField.tsx, src/pages/registration/resource_type_tab/components/JournalField.tsx, src/pages/registration/resource_type_tab/components/PublisherField.tsx, src/pages/registration/resource_type_tab/components/SearchContainerField.tsx, src/pages/registration/resource_type_tab/components/SeriesField.tsx, src/pages/registration/resource_type_tab/sub_type_forms/ChapterForm.tsx, src/translations/nbTranslations.json
Link to Jira issue: https://sikt.atlassian.net/browse/NP-47401
Vis grunnen til hvorfor et felt som påvirker NVI låses når alle institusjoner har godkjent en kandidat, og den fortsatt er i en åpen kandidat. Feltene vil fortsatt være enabled for NVI-kurator, men disabled for alle andre.
Eksempelpost for testing: http://localhost:3000/registration/01905dc6a204-93833649-22c7-4fbd-95ad-b54d0d618761/edit
=> Np 47401 inform about disabled nvi fields

src/pages/project/project_wizard/ProjectContributorsForm.tsx, src/pages/project/project_wizard/ProjectForm.tsx, src/pages/project/project_wizard/ProjectFormStepper.tsx, src/pages/projects/form/ProjectContributors.tsx, src/pages/projects/form/ProjectFormPanel1.tsx, src/pages/projects/form/ProjectFunding.tsx, src/utils/formik-helpers/project-form-helpers.ts, src/utils/projectFormikFieldNames.ts
Link to Jira issue: [NP-47305](https://sikt.atlassian.net/browse/NP-47305)
**⚠This is only visible when you have beta toggled to true in local storage ⚠**
You get to this view my going to Min Side --> "Prosjektregistreringer" in the left panel -> Choose a project -> Click the edit-button and go to the third tab: Contributors
This is a part of the effort to create a new create project-wizard [(NP-47281)](https://sikt.atlassian.net/browse/NP-47281), and there is a subtask for each of the 4 steps, plus subtasks for some new functionality to add.
In this task we have to create the third tab, using already the new contributor view I have made in earlier tasks.
**What should work after this PR:**
In projects view, it should now be possible to click the edit button and get into the new edit …
=> Create the third tab "Project participants" of the "Create Project" view

src/types/publication_types/degreeRegistration.types.ts, src/utils/registration-helpers.ts
Link to Jira issue: https://sikt.atlassian.net/browse/NP-47415
Løst feil hvor bruker noen ganger ikke fikk lov til å endre på emnekode fordi `type` ikke var angitt. Når en studentoppgave nå skal lagres, går vi gjennom objektet og passer på at det er en gyldig verdi for `course`.
=> NP-47415 Ensure user can edit course code

src/translations/nbTranslations.json, src/utils/validation/registration/referenceValidation.ts
Link to Jira issue: https://sikt.atlassian.net/browse/NP-47417
Oppdater tekst for valideringsfeil pga mangel på bekreftet kanal.
=> NP-47417 Update error message for unconfirmed channel

src/api/publicationChannelApi.ts
Vi har tidliger lagt inn mulighet for å hente flere treff for kanalsøket. Etter testing er tilbakemeldingnen at de ikke gidder trykke "Vis flere" så mange ganger som nå, hvor de bare får 5 nye treff for hver gang. Etter samtale med PO setter vi opp denne til 50. Dette er for å bøte på problemet inntil det blir løst i eksternt API, men ingen løsning i sikte der per i dag.
=> Raise channel search default size to 50

src/pages/public_registration/PublicRegistrationContributors.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-47433
- Vis rollenavn for alle bidragsytere som er noe annet enn forfatter
- Fjern "Bidragsytere" heading fra visning over andre/secondary bidragsytere
Diffen får det til å virke som en større endring enn det i realiteten er, pg fjerning av unødvendig `<div>` som fjerner ett innrykk
=> Np 47433 adjust contributors display

src/pages/public_registration/public_files/FileRow.tsx, src/pages/registration/FileList.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-47394
Tillat `CuratorThesis` å endre på filer for studentoppgaver med embargo i fremtiden, så lenge fila ikke enda er publisert.
Inkluderer også en liten fiks for visning av embargo.
Før:
Etter:
=> NP-47394 Allow thesis curator to edit embargoed files that are not published yet

src/components/institution/AffiliationHierarchy.tsx, src/pages/projects/ProjectContributors.tsx, src/translations/nbTranslations.json
Link to Jira issue: [https://sikt.atlassian.net/browse/NP-47077](https://sikt.atlassian.net/browse/NP-47077)
In Project view, if the contributor belongs to a sub-institution below an organization, we are currently only showing the sub-institution in the Project Landing page. In Cristin, they are also stating where the sub-institution belongs. So in this PR I added that. No change where the affiliation is the top level:
Also, this solves a potential other problem that could arise, where the roles-object on a ProjectContributor could have no labels. No we fetch the organization text from the organization object.
_Note: some of …
=> Now showing institution for contributors

src/pages/registration/FilesAndLicensePanel.tsx, src/utils/registration-helpers.ts
Reverts BIBSYSDEV/NVA-Frontend#6154
Denne "fiksen" viste seg å være en feil, som ble oppdaget når den skulle retestes. Derfor tar vi den bort igjen, som egentlig bare er bra for kodens del også, for syns som nevnt i den PRen at dette var litt rotete
=> Revert "NP-47395 Give publishing curators access to bypass file restrictions of other users"

src/components/ContributorSearchField.tsx, src/pages/registration/contributors_tab/components/AddContributorTableRow.tsx, src/pages/registration/contributors_tab/components/SelectAffiliationRadioButton.tsx, src/pages/registration/contributors_tab/components/SelectAffiliationsCheckbox.tsx
Link to Jira issue: [https://sikt.atlassian.net/browse/NP-47481](https://sikt.atlassian.net/browse/NP-47481)
In this PR we are adding a parameter to `AddContributorTableRow` so that we can choose between radio boxes for single select or check boxes for multiple select:
=> Added parameter to choose between multi- or singleSelect

src/pages/projects/AddProjectContributorForm.tsx, src/pages/projects/ProjectAddAffiliationModal.tsx, src/pages/projects/ProjectContributors.tsx, src/pages/projects/ProjectEditAffiliationModal.tsx, src/pages/projects/form/ContributorRow.tsx, src/pages/projects/form/ProjectFormDialog.tsx, src/pages/projects/form/ProjectFormPanel1.tsx, src/translations/nbTranslations.json, src/types/project.types.ts
Link to Jira issue: [https://sikt.atlassian.net/browse/NP-47475](https://sikt.atlassian.net/browse/NP-47475)
When we added a new contributor without selecting affiliation, the view would be buggy, because it couldn't handle not having affiliations:
Now I changed the type definition so that affiliations can be empty. I also fixed some smaller bugs to handle edge cases.
=> Fixed bug when we added contributor without adding affiliation

src/pages/project/project_wizard/CreateNfrProject.tsx, src/pages/project/project_wizard/CreateProject.tsx, src/pages/project/project_wizard/ProjectForm.tsx, src/pages/project/project_wizard/ProjectManager.tsx, src/pages/projects/AddProjectContributorModal.tsx, src/pages/projects/AddProjectManagerForm.tsx
Link to Jira issue: [https://sikt.atlassian.net/browse/NP-47448](https://sikt.atlassian.net/browse/NP-47448)
This is just reinstating functionality from the old project-form: When a new project is created from NFR-project a lot of  fields will come pre-filled in the form. One of these should be project manager, but since that it difficult to add when many people can have the same name, will will just display the name in the select-box:
=> Show suggested project manager when NFR-project

src/pages/project/project_wizard/ProjectFormActions.tsx
Link to Jira issue: [https://sikt.atlassian.net/browse/NP-47421](https://sikt.atlassian.net/browse/NP-47421)
Now, when clicking cancel in new project view, you get a confirm-dialog to ensure you know you will lose your unsaved data:
=> Added warning on cancel-button i new project view

src/components/DialoguesWithoutCuratorButton.tsx, src/components/TicketStatusFilter.tsx, src/pages/messages/components/TicketList.tsx, src/translations/nbTranslations.json
Link to Jira issue: https://sikt.atlassian.net/browse/NP-47555
Ta vekk "Innmeldt" som status fra Oppgaver-visning til kurator, og legg til egen knapp som styrer bare om nye oppgaver uten kurator også skal inkluderes i søket. Den skal være enabled by default. Det er ønske om litt justering på plasseringen til disse søkefeltene også, men ser det vil bli en del knoting med mange `<Grid>` items og sånt styr for både Oppgaver og Min Side, så lar det ligge inntil videre. Ser for meg det kan være fornuftig å ta etter at vi har flyttet "Ulest"-knappen også, da det også vil påvirke visningen her
Før:
Etter:
_Note: some of these …
=> Np 47555 move new status filter

src/pages/messages/components/NviStatusPage.tsx
Fjern beta-tag for NVI-eksport
Funksjonalitet ble implementert her: https://github.com/BIBSYSDEV/NVA-Frontend/pull/6188
=> NP-46984 Remove beta tag from NVI status export

src/pages/public_registration/PublicRegistrationContent.tsx, src/translations/nbTranslations.json
Link to Jira issue: https://sikt.atlassian.net/browse/NP-47587
Bruk "Kapitler" i stedet for "Andre relaterte registreringer" for bøker og rapporter, siden det stort sett er kapitler som vil være her. Merk at dette også kan føre til noen merkelige treff ved at ting som ikke er kapittel også vises her, men som diskutert i Jira-oppgaven går vi for dette i denne omgang.
=> Use chapters heading for things that usually has chapters

src/components/CategorySearchFilter.tsx, src/pages/messages/components/NviCorrectionList.tsx, src/pages/messages/components/NviCorrectionListNavigationAccordion.tsx, src/pages/search/advanced_search/AdvancedSearchPage.tsx, src/pages/search/advanced_search/JournalFilter.tsx, src/pages/search/advanced_search/OrganizationFilters.tsx, src/pages/search/advanced_search/PublisherFilter.tsx, src/pages/search/advanced_search/SeriesFilter.tsx, src/utils/dataTestIds.ts
Link to Jira issue: https://sikt.atlassian.net/browse/NP-47571
Vis andre filter man kan bruke i tillegg til satte filter for NVI-kooreksjonsliste. Har også flyttet tittel til feltene inn til samme komponent som feltet, for å unngå å måtte oppgi det på nytt hver gang.
Lagt til følgende filter:
- Institusjon og enhet
- Kategori
- Kanal (tidsskrift, utgiver og serie)
Har i tillegg lagt til støtte for å disable søkefelter som kan/vil være i konflikt med bestemte rettelister.
> Sleit med å få til en god løsning for mobilløsning av dette, så endte opp med noe litt hallveis der. Sleit med at det ser ut som feltene er knyttet til …
=> Np 47571 add filters to nvi correction list

src/pages/public_registration/action_accordions/DoiRequestAccordion.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-47600
Sørg for at man kan vise bekreftelsesdialog også for resultat uten filer.
Dette er en glipp fra https://github.com/BIBSYSDEV/NVA-Frontend/pull/6162.
=> NP-47600 Show assign doi popup for rejected DOI request on result without file

src/api/hooks/useFetchRegistration.ts, src/pages/basic_data/app_admin/central_import/CentralImportCandidateMerge.tsx, src/pages/basic_data/app_admin/central_import/CentralImportDuplicationCheckPage.tsx, src/pages/messages/components/NviCandidatePage.tsx, src/pages/public_registration/ChapterPublisherInfo.tsx, src/pages/public_registration/DeletedPublicationInformation.tsx, src/pages/public_registration/PublicPublicationContext.tsx, src/pages/public_registration/RegistrationLandingPage.tsx, src/pages/public_registration/RegistrationSummary.tsx, src/pages/public_registration/action_accordions/DeletedRegistrationInformation.tsx, src/pages/registration/RegistrationForm.tsx, src/pages/registration/resource_type_tab/sub_type_forms/artistic_types/OutputRow.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-47593
Håndter henting av resultat som har blitt avpublisert, da vi i de tilfellene vil vise ene propertyen i responsen som data, og ignorere at det gir en `410 Gone` klient error.
Eksempel: https://dev.nva.sikt.no/registration/0191ea9a2606-aaa0bc79-e5a1-49e1-8f8d-a9036838c789/edit
=> Np 47593 handle fetching unpublished results

src/components/ContributorSearchField.tsx, src/components/institution/OrganizationBox.tsx, src/components/messages/SimpleWarning.tsx, src/pages/project/project_wizard/ProjectManager.tsx, src/pages/projects/AddProjectManagerForm.tsx, src/pages/projects/ProjectOrganizationBox.tsx, src/pages/registration/contributors_tab/components/AddContributorTableRow.tsx, src/pages/registration/contributors_tab/components/ContributorRow.tsx, src/pages/registration/contributors_tab/components/SelectAffiliationRadioButton.tsx, src/utils/dataTestIds.ts
* Changed affiliations select in AddContributorTableRow from boolean to multiple choice and added NO_SELECT as option. 
* Also fixed some testIds after findings from Eirik.
* Extracted warning from registration contributor view for later reuse:
=> Some small cleanups

src/pages/search/person_search/PersonSearch.tsx, src/pages/search/project_search/ProjectSearch.tsx, src/pages/search/registration_search/RegistrationSearch.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-47652
Flere har rapportert/meldt om feil for de tror søket ikke virker pga manglende loading-indikator. Med dette legger jeg inn loading hver gang søket endres,så bruker får tydelig beskjed om at "noe skjer". Fasetter vil fortsatt vises som før, for å unngå at innholdet hopper rundt på skjermen.
=> Np 47652 show loading indicator when searching

buildspecs/cypress_tests.yml
Følger cypress docs: https://docs.cypress.io/guides/getting-started/installing-cypress#Amazon-Linux-2023
Har byttet fra `Amazon Linux 2 x86_64 standard:4.0` til `Amazon Linux 2023 x86_64 standard:5.0` for å gå over til nyere versjon av node når vi bygger til PR: https://docs.aws.amazon.com/codebuild/latest/userguide/available-runtimes.html.
Til nå har vi vært på node v16 som "døde" [i fjor](https://nodejs.org/en/about/previous-releases) i codebuild. Denne gamle versjonen førte til at noen andre pakker ikke lot seg bumpe, f.eks. https://github.com/BIBSYSDEV/NVA-Frontend/pull/6302.
=> Fix tests for new version of Amazon Linux

src/components/CategorySearchFilter.tsx, src/components/styled/Wrappers.tsx, src/pages/search/advanced_search/AdvancedSearchPage.tsx, src/pages/search/advanced_search/JournalFilter.tsx, src/pages/search/advanced_search/OrganizationFilters.tsx, src/pages/search/advanced_search/PublisherFilter.tsx, src/pages/search/advanced_search/SeriesFilter.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-47241
Fjern sirkulære avhengigheter relatert til felt-headings i søk som kommer som advarsel når vi bygger appen. Gjenstår fortsatt noen warnings jeg lar være i denne omgang.
Før (`npm run build`):
Etter:
=> NP-47241 Remove a few circular dependencies

index.html, src/utils/mathJaxHelpers.ts, src/utils/testfiles/mockRegistration.ts
Link to Jira issue: https://sikt.atlassian.net/browse/NP-47679
Bedre støtte for MathJax ved å fjerne noe config vi kanskje aldri skulle lagt inn. Husker ikke helt hvorfor det ble lagt inn, men tror det var for å kreve dobbel `$$` for å aktivere MathJax, men det virker ikke bra når vi importerer fra andre systemer. Merk at disse endringen _kan_ føre til at noe annet ikke virker som før, men tror vi er tjent med å bevege oss over til default config uansett.
For å teste kan man feks søk på en eller annen variant av `sqrt`.
Før:
Etter:
_Note: some of these criterias may not always be relevant, and can simply be marked as …
=> NP-47679 Improve support for MathJax

src/api/hooks/useDuplicateRegistrationSearch.ts, src/api/searchApi.ts, src/pages/public_registration/action_accordions/PublishingAccordion.tsx, src/pages/registration/DescriptionPanel.tsx, src/pages/registration/ResourceTypePanel.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-47677
Unngå å søke etter duplikater når posten allerede er publisert. Dette trigget en feil for [denne](https://sikt.atlassian.net/browse/NP-47675) posten i test, da søket feiler. Dette vil ikke trigge et søk nå lenger, som kan ses [her](http://localhost:3000/registration/0191e03bdc60-721d4cbd-1f0e-4db5-a553-25c4e05c2eee/) (localhost) for en post med tegn i tittelen som fører til feil i søket. Merk at man må ha redigeringstilgang på posten for at dette skal skje.
=> Np 47677 avoid searching for duplicate after publishing

src/pages/messages/components/NviCorrectionList.tsx, src/pages/messages/components/NviCorrectionListNavigationAccordion.tsx, src/translations/nbTranslations.json
Link to Jira issue: https://sikt.atlassian.net/browse/NP-47382
Ta vekk gammel NVI-retteliste fra DUCT nå som vi har våre egne.
=> NP-47382 Remove old correction lists from DUCT

src/pages/messages/components/NviStatusTableRow.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-47687 (Egentlig ikke direkte koblet til denne tasken)
Vis lasteindikator i stedet for å defaulte til 0 mens man venter på data. 
=> Show loading indicator for pending NVI status numbers

src/pages/search/PublicationYearIntervalFilter.tsx, src/pages/search/registration_search/RegistrationSearch.tsx, src/pages/search/registration_search/RegistrationSearchBar.tsx, src/pages/search/registration_search/filters/AdvancedSearchRow.tsx, src/pages/search/registration_search/filters/RegistrationFacetsFilter.tsx, src/utils/searchHelpers.ts
Link to Jira issue: https://sikt.atlassian.net/browse/NP-47390
Dagens søk har problemer med å håndtere felter som har endrede verdier, men som ikke er submitta. 
Eksempel:
1. Gå til https://dev.nva.sikt.no/
2. Skriv "natur" i søkefeltet
3. Velg en fasett/aggreging i venstremenyen
4. Det gjøres nå et nytt søk, men selv om det står "natur" i søkefeltet er ikke det inkludert i søket, siden verdien ikke har blitt submitted på noe vis. Dette oppstår i alle tilfeller hvor man gjør endringer i et fritekstfelt uten å aktivt submitte.
Har et forslag på løsning som virker slik:
- Alle fritekstfelter får et HTML-attributt `data-searchfield` (se docs for `data-*`-attributter [her](https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes))
- Når et nytt søk gjennomføres, vil vi …
=> Np 47390 ensure latest query value is used for search

src/api/hooks/useFetchNviReportExport.ts, src/pages/messages/components/ExportNviStatusButton.tsx, src/pages/messages/components/NviStatusTableRow.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-47687
Introdusert her: https://github.com/BIBSYSDEV/NVA-Frontend/pull/6188
Unngå at eksport trigges automatisk om man laster ned en eksport, velger annet år, og bytter år tilbake igjen. Løsningne var egentlig mye enklere enn jeg/vi trodde med første iterasjon av dette. Nok et påminnelse om at code-smell ofte er et tegn på at man gjør noe feil, ikke at problemet er vanskelig
=> NP-47687 Avoid new exports being created on every mount

src/components/SearchForm.tsx, src/pages/search/advanced_search/AdvancedSearchPage.tsx, src/pages/search/advanced_search/CategoryFilterDialog.tsx, src/pages/search/advanced_search/FileStatusSelect.tsx, src/pages/search/advanced_search/FundingSourceFilter.tsx, src/pages/search/advanced_search/JournalFilter.tsx, src/pages/search/advanced_search/LanguageFilter.tsx, src/pages/search/advanced_search/OrganizationFilters.tsx, src/pages/search/advanced_search/PublisherFilter.tsx, src/pages/search/advanced_search/ScientificValueFilter.tsx, src/pages/search/advanced_search/SeriesFilter.tsx, src/pages/search/advanced_search/VocabularSearchField.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-47390
Sørg for at siste verdi av søkefelter alltid brukes når bruker trigger nytt søk på avansert søk. Har også lagt til nullstilling av paginering når man endrer søket, som vi manglet ganske mange plasser.
Basert på https://github.com/BIBSYSDEV/NVA-Frontend/pull/6307. Kommer flere PRer som løser det samme flere andre plasser
=> NP-47390 Sync params for all fields on advanced search

src/components/ListPagination.tsx, src/components/ListPaginationBottom.tsx, src/pages/my_page/user_profile/MyResults.tsx, src/pages/research_profile/ResearchProfile.tsx, src/pages/search/registration_search/RegistrationSearch.tsx, src/translations/nbTranslations.json
Fiks UU-problem for resultatsøk på forskerprofil, da to `<Pagination>`-elementer i dag får samme `aria-label` og blir umilig å skille fra hverandre.
=> Set aria label for result search pagination

src/pages/project/helpers/projectContributorHelpers.ts
Link to Jira issue: [https://sikt.atlassian.net/browse/NP-47800](https://sikt.atlassian.net/browse/NP-47800)
Fixed bug that came because of an error in how we identified the index of a contributor without an id:
=> Fixed bug in project contributors view

src/pages/editor/PortfolioSearchPage.tsx
Litt cowboyhatt her🤠, men hear me out:
Vi har nå aktivert Matomo Crash Analytics, men etter noen dager har vi fortsatt ikke fått noen feil i konsollen der.
Legger derfor inn noen hardkodete Errors i beta-tag nå, sånn at vi kan trigge dette selv, og vite om loggingen av errors faktisk virker.
Tenker å ta dette rett inn i `staging` (test), så revertere commiten med en gang jeg har fått verifisert at det virker. Så er dette borte for godt igjen.
=> Trigger errors to test Crash Analytics

src/matomo/matomo.ts
PR for å verifisere at errors logges til matomo viste seg at det ikke virker helt som ønsket: https://github.com/BIBSYSDEV/NVA-Frontend/pull/6367 (NB! den PRen må/bør reverteres før vi ruller ut videre til prod)
Legger ved forsøk på å konfigurere eksplisitt logging her
=> Configure logging of console errors

src/pages/projects/form/ProjectParticipants.tsx, src/utils/dataTestIds.ts
Link to Jira issue: [https://sikt.atlassian.net/browse/NP-47842](https://sikt.atlassian.net/browse/NP-47842)
Add LocalProjectManager and Add ProjectParticipant had the same data-testid. Fixed now.
=> Added test id

src/components/ErrorBoundary.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-47462
Etter mange runder frem og tilbake fant jeg endelig ut hvorfor mange opplever at appen krasjer når vi deployer ny versjon. Grunnen er at ulike nettlesere gir ulike feilmeldinger når den ikke får til å laste chunk fordi appen er oppdatert med nye chunk-navn. Dette har derfor bare virket på Firefox som jeg selv har.
Har verifisert at denne nte løsningen virker på Firefox, Chrome, Edge, og Safari (via browserstack.com)
=> Handle failed loading of chunks on more browsers

src/api/searchApi.ts, src/pages/search/registration_search/RegistrationSearchBar.tsx, src/pages/search/registration_search/filters/RegistrationFacetsFilter.tsx, src/utils/hooks/useRegistrationSearchParams.ts, src/utils/searchHelpers.ts
Link to Jira issue: https://sikt.atlassian.net/browse/NP-47794
Problem: When setting the params for NVI-period using the facets filters, the params `scientificReportPeriodSince` and `scientificReportPeriodBefore` were combined to `scientificIndex`. This created a mismatch between the url-param and the actual GET-request used for exporting results.
Fix: set both params in the url.
=> NP-47794 Fix result export params

src/pages/project/ProjectModal.tsx, src/pages/project/project_wizard/CreateProject.tsx, src/pages/project/project_wizard/ProjectForm.tsx, src/pages/project/project_wizard/ProjectFormActions.tsx, src/pages/registration/description_tab/projects_field/ProjectsField.tsx, src/translations/nbTranslations.json, src/utils/dataTestIds.ts
Link to Jira issue: [https://sikt.atlassian.net/browse/NP-47743](https://sikt.atlassian.net/browse/NP-47743)
When making a new registration it should be possible to make a new project without having to leave the registration view (i.e. in a popup). This was possible earlier, so we are re-fetching old functionality in a new layout.
Once the project is created it is automatically added to the registration as well:
=> Open project wizard in modal from registration

src/pages/project/helpers/projectContributorHelpers.ts, src/pages/project/project_wizard/CreateNfrProject.tsx
Link to Jira issue: [https://sikt.atlassian.net/browse/NP-47848](https://sikt.atlassian.net/browse/NP-47848)
If we choose to create a new project from a NFR-project, the contributors tab will now have a suggested project manager:
They still have to be identified using the "identifiser prosjektleder"-button, but the search will already be filled in to decrease the number of steps.
Since unidentified contributors are in beta tag awaiting a backend change to stop giving unidentified users an id, an possibly some testing, this code is also beta-tagged.
_Note: some of these criterias may not always be relevant, and can simply be …
=> Automatically adding (unidentified) project manager on NFR projects (beta-tagged)

src/components/OrganizationAccordion.tsx, src/components/institution/SelectInstitutionForm.tsx, src/pages/registration/contributors_tab/components/EditAffiliationModal.tsx, src/pages/search/advanced_search/OrganizationHierarchyFilter.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-47871
Løs feil hvor bruker ikke kunne endre tilknytning, som ser ut til å stamme fra denne: https://github.com/BIBSYSDEV/NVA-Frontend/pull/5758
Endringen jeg har gjort er at all data som skal submittes er flyttet inn i form values, da noe av dette tidligere ble lagret i `useState` utenfor formen. Dette førte tidligere til at verdiene som ble submitted ikke alltid var i sync med det som ble vist i skjermbildet.
En del logikk rundt omkring her, så vanskelig å slå fast at det ikke er introdusert noen ny bug, men har ikke oppdaget noe selv. 
_Note: some of these criterias …
=> Np 47871 handle updating affiliation bug

src/pages/project/project_wizard/EmptyProjectForm.tsx, src/pages/project/project_wizard/ProjectDescriptionForm.tsx, src/pages/registration/DuplicateWarning.tsx, src/translations/nbTranslations.json
Link to Jira issue: [https://sikt.atlassian.net/browse/NP-47890](https://sikt.atlassian.net/browse/NP-47890)
In the project wizard, when the title exists on other project, changed the title of the list from "result" to "search result" (two places). Also found and fixed small bug where both result and "no results found" would show at the same time.
=> Changed "Result" to "Searchresult" and fixed small bug I found

src/components/RouteLeavingGuard.tsx, src/pages/registration/RegistrationFormActions.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-47920
Unngå at bruker får varsel om at formen har ulagrede endringer etter å ha lagret. Skulle gjerne hatt en bedre løsning enn å legge inn en wait, men har ikke funnet noe bedre enda hvertfall..
NB! Denne burde nok testes noen dager i dev før vi ruller ut til test og prod
Feilen ble introdusert, og forsøkt mitigert, her: https://github.com/BIBSYSDEV/NVA-Frontend/pull/5728
=> NP-47920 Add a fixed wait to ensure formik has correct form state

src/pages/public_registration/ActionPanel.tsx, src/pages/public_registration/ActionPanelContent.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-47874
Vis loggen som default når bruker ikke har tilgang til å gjøre noe i oppgave-taben. Dette gjelder f.eks. om man bare er NVI-kurator. Tidligere fikk man alltid se en fane for oppgvaver som kunne være helt tom om man ikke hadde lov til å gjøre noe.
Det som er gjort er i praksis å flytte tilgangssjekken en komponent opp, og så vise bare logg-fanen om det er det eneste man har lov til.
=> Np 47874 show log when user cannot do anything on tasks

src/pages/basic_data/institution_admin/AddEmployeePage.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-47917
Løst feil hvor man ikke fikk til å opprette NVA-User etter å ha opprettet Cristin-Person, da vi ikke brukte CristinIdentifier fra forrige steg.
=> NP-47917 Allow creating person and user in one try

src/pages/public_registration/ActionPanel.tsx, src/pages/public_registration/ActionPanelContent.tsx, src/pages/public_registration/action_accordions/DeleteDraftRegistration.tsx, src/pages/public_registration/action_accordions/MoreActionsCollapse.tsx, src/translations/nbTranslations.json, src/utils/dataTestIds.ts
Link to Jira issue: https://sikt.atlassian.net/browse/NP-47442
Flytt slett-knappen for kladder fra å være nederst i høyremeny til å bli nederst i publiseringsboksen.
Før:
Etter:
=> Np 47442 move delete draft button

src/translations/nbTranslations.json, src/types/publication_types/ticket.types.ts, src/utils/log/logFactory.ts, src/utils/log/publishingRequestGenerator.ts, src/utils/registration-helpers.ts
Link to Jira issue: https://sikt.atlassian.net/browse/NP-48063
Tilpasser modellendringer som innføres her: https://github.com/BIBSYSDEV/nva-publication-api/pull/1922
Bruk ny modell for filer på tickets, hvor hele fil-objektet inkuderes i `filesForApproval` og `approvedFiles`, i stedet for bare identifier som tidligere.
Hikker litt ved godkjenning av intern fil, men det vil løses av https://github.com/BIBSYSDEV/NVA-Frontend/pull/6504
=> Np 48063 update ticket files model

src/pages/registration/RegistrationForm.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-48078
Legger til resultat-ikon i registreringswizard. Bygger videre på https://github.com/BIBSYSDEV/NVA-Frontend/pull/6603
Rota til historikken i [forrige PR](https://github.com/BIBSYSDEV/NVA-Frontend/pull/6604), derfor oppretter jeg denne på nytt
Før:
Etter:
=> NP-48078 Add result icon to wizard header

src/components/CategorySelector.tsx, src/components/atoms/DoesNotSupportFileIcon.tsx, src/components/atoms/NviApplicableIcon.tsx, src/pages/editor/CategoriesWithFiles.tsx, src/pages/editor/CategoriesWithFilesOverview.tsx, src/pages/registration/resource_type_tab/SelectRegistrationTypeField.tsx, src/translations/nbTranslations.json
Link to Jira issue: https://sikt.atlassian.net/browse/NP-47791
Vis oversikt over hvilke kategorier som ikke støtter filopplasting ved å legge til ikon der det er relevant. Dette skal bare vises hvor det er relevant, som er i wizard og i institusjonens oversikt over kategorier uten fil.
=> Np 47791 show no files icon

src/components/CategorySelector.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-47791
Vis "+"-ikon når en chip ikke er valgt.
=> Show add icon when chip is not selected

src/components/Log/LogActionItem.tsx, src/pages/registration/files_and_license_tab/FilesTableRow.tsx
Link to Jira: https://sikt.atlassian.net/browse/NP-47791?focusedCommentId=109808
Oppdater ikon for intern fil, nå som det ikonet brukes for å vise at en kategori ikke støtter filopplasting
=> NP-47791 Update internal file icon

src/pages/my_page/user_profile/MyFieldAndBackground.tsx, src/translations/nbTranslations.json
Link to Jira issue: https://sikt.atlassian.net/browse/NP-48076
Diverse utbedringer av søk etter nøkkelord på Min Side -> Forskerprofil -> Fagfelt og bakgrunn
- Oppdatert tekster
- Tillat bruker å hente flere søketreff
- Vis initielle treff før bruker har gjort et søk
- Ta vare på forrige søk når man velger feltet igjen
=> Np 48076 search for keywords

src/pages/public_registration/action_accordions/SupportAccordion.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-48165
Fixed an unwanted side-effect where a support-curator would autimatically approve their own ticket of they sent two consecutive messages.
=> NP-48165 Change support ticket autocomplete

src/pages/messages/components/NviCandidatesNavigationAccordion.tsx, src/translations/nbTranslations.json
Link to Jira issue: https://sikt.atlassian.net/browse/NP-48139 & https://sikt.atlassian.net/browse/NP-48131
Oppdater tiitel for NVI på Oppgaver-siden. 
Min subjektive mening er at det blir litt mye tekst sammenlignet med resten:
=> NP-48139 update nvi accordion title

src/api/authApi.ts, src/components/AcceptTermsDialog.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-47183
Tester ny flyt hvor vi refresher session før user attributes hentes etter at brukervilkår godkjennes. Vi har et håp om at dette skal gjøre at roller også oppdateres i user attributes. Merger dette til sandbox, til verifisering der, før det ev. går til develop om det virker som håpet.
=> Refresh session before refetching user attributes

src/api/authApi.ts, src/components/AcceptTermsDialog.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-47183
Basert på [denne](https://github.com/BIBSYSDEV/NVA-Frontend/pull/6743) som verifiserte at dette virker i sandbox.
Her refreshes token sånn at user attributes blir riktig etter at man har godkjent brukervilkår.
=> NP-47183 Refresh session before refetching user attributes

src/pages/public_registration/public_files/FilesLandingPageAccordion.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-47979
Dette er gjort:
- Løst liten feil hvor Filer-accordion noen ganger ikke ble vist ved en feil
- Forenkle sjekken for når Filer-accordion skal vises
Vanskelig å være helt sikker på at dette ikke introduserer en ny liten bug i noen tilfeller, men om det dukker opp burde det gå ganske raskt å rette opp.
=> Np 47979 simplify file null checking

src/pages/registration/FileList.tsx, src/pages/registration/files_and_license_tab/FilesTableRow.tsx
Løs feil for offset i filtabell om man laster opp fil uten å ha valgt kategori.
La også til en skjult heading i kolonne lengst til venstre, for å fjerne en a11y error.
Før:
Etter:
=> Avoid file table offset bug

src/pages/public_registration/action_accordions/PublishingAccordion.tsx
Løst en feil hvor man noen ganger ikke fikk lov til å publisere et resultat pga valideringsfeil siden kategorien ikke ble sendt med som en context-variabel til valideringen. Dette førte til problemer for enkelte kategorier.
Ett eksempel er [denne](https://dev.nva.sikt.no/registration/0193d98b7dd7-4e8e0206-8ef7-4efb-8c39-56643e1ca6ab) posten, hvor man ikke fikk lov til å publisere om bidragsyter hadde rollen "Redaktør", men fikk lov med "Forfatter".
=> Fix publishing bug for workflow 2

src/components/DialoguesWithoutCuratorButton.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-46405
Bruk bare ikon i stedet for ikon wrappet i Badge for filterknapp.
Før:
Etter:
=> NP-46405 Use icon instead of Badge in new tasks filter button

src/api/apiPaths.ts, src/api/hooks/useFetchNviReportedStatus.ts, src/api/scientificIndexApi.ts, src/pages/public_registration/PublicGeneralContent.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-48263
Bruk nytt endepunkt for å vise året et resultat ble NVI-rapportert. 
Vi ønsker sikkert å bruke samme endepunkt i wizard også, men det avhenger av: https://github.com/BIBSYSDEV/nva-nvi/pull/416 så det blir også egen PR for frontend
=> NP-48263 Use new endpoint for fetching NVI reported year

src/pages/registration/description_tab/projects_field/ProjectsField.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-48317
La bruker hente 10 flere treff for prosjektsøk
=> NP-48317 Allow fetching more projects when searching

src/pages/registration/resource_type_tab/components/SearchContainerField.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-48316
Legg til støtte for å sæke med ISBN når man skal ha parant til et kapittel. Formaterer ISBN til å være uten bindestreker når API-kallet gjøres.
Åpner nå opp for å søke etter enda flere ting også, ved å bruke query param i stedet for title.
=> NP-48316 Search for parent by query instead of title

src/pages/registration/description_tab/projects_field/ProjectsField.tsx
Link to Jira issue: [NP-48329](https://sikt.atlassian.net/browse/NP-48329)
Fjerner tøm-knapp for input-felt prosjekttilknytning, da denne fjerner valgte prosjekttilknytninger i listen under. Ettersom input-feltet er en modifisert `<Autocomplete multiple ...`> som ikke viser valgte elementer i input-feltet, så er det forvirrende med en tøm-knapp som manipulerer listen under.
[NP-48329]: https://sikt.atlassian.net/browse/NP-48329?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> NP-48329 Fjerner tøm-knapp for input-felt prosjekttilknytning

src/pages/registration/description_tab/vocabularies/VocabularyAutocomplete.tsx, src/pages/registration/description_tab/vocabularies/VocabularyFields.tsx
Link to Jira [NP-48331:](https://sikt.atlassian.net/browse/NP-48331)
Få input-felt HRCS-aktiviteter på linje med resten av input
=> NP-48331 Align HRCS input

src/api/searchApi.ts
Per i dag fungerer ikke søket om man med `status=PUBLISHED`, men om man legger med `query` får man treff. Tenker vi bare kan pushe til FE da det "fikser" litt av problemet.
=> Add version for new search model for search/customer

src/pages/dashboard/Dashboard.tsx
Suggestion for centering the banner-content on start-page.
Before:
After:
=> Adjust tagline and description

src/pages/messages/components/DoiRequestMessagesColumn.tsx, src/pages/messages/components/PublishingRequestMessagesColumn.tsx, src/pages/messages/components/SupportMessagesColumn.tsx, src/pages/messages/components/TicketListItem.tsx, src/pages/public_registration/PublishingLogPreview.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-47983
- Synliggjør hva som er gjort/skal gjøres før eventuelle meldinger vises
- Legg til ikon for å vise status tydeligere
- Ikke vis meldinger på tickets som er `Completed`
Før:
Etter:
=> Np 47983 update ticket status boxes

src/pages/public_registration/action_accordions/TicketAssignee.tsx, src/translations/nbTranslations.json
Link to Jira issue: [NP-47984](https://sikt.atlassian.net/browse/NP-47984)
Fjerner dropdown for kuratorvelger når man er på "min side", da man uansett ikke kan endre kurator derifra.
Før:
Etter:
[NP-47984]: https://sikt.atlassian.net/browse/NP-47984?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> NP-47984 Show text instead of input field for curator selector when on myPage

src/pages/messages/components/NavigationIconButton.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-48126
Setter en fast plassering på navigasjonsknapper for å unngå at de hopper ned etter eventuelle filer lastes. Det kunne også føre til at pilene kom utenfor skjermen, sånn at man måtte scrolle for å se dem.
=> NP-48126 Set fixed top margin for NVI navigation buttons

src/pages/public_registration/public_files/FilesLandingPageAccordion.tsx, src/types/registration.types.ts
Link to Jira issue: https://sikt.atlassian.net/browse/NP-48307
Backend vil snart filtrere bort pending open files for brukere som ikke har tilgang til det, så da må vi bruke den nye `pendingOpenFileCount` for å vise alle brukere hvor mange filer som venter på godkjenning
=> Use new property for pending open files

src/pages/messages/components/MessageItemOrganization.tsx, src/pages/messages/components/MessageList.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-48141
Vis bare institusjon (ikke dato) for NVI-merknader.
Før:
Etter:
=> NP-48141 Show only institution instead of date for NVI comments

src/pages/public_registration/PublicPublicationContext.tsx, src/pages/registration/resource_type_tab/sub_type_forms/PresentationForm.tsx, src/utils/countryHelpers.ts
Link to Jira issue: https://sikt.atlassian.net/browse/NP-48413
- Flytt henting av landliste til egen funksjon
- Vis navn på landet i stedet for bare landkode
- Fiks feil hvor man ikke får se valgt land om man har valgt nynorsk som språk
Før:
Etter:
=> NP-48413 Move country logic to own file

src/pages/messages/components/NviApprovals.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-48134
Tydeliggjør status fra hver institusjon ved å sette bakrunnsfarge i approvals-tabellen.
Rosa: Godkjent
Grå: Avvist
Hvit: Venter 
Før:
Etter:
=> Np 48134 set approval color

src/components/RegistrationList.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-48418
Fix an issue where the user was redirected to te duplicate result when trying to navigate to an unpublished result from the TasksRegistration Page.
=> NP-48418 Fix redirect

src/AppRoutes.tsx
Bygget gir en warning pga en komponent som lastes både dynamisk (lazy) og vanlig på ulike plasser. Fiksen er å gjøre det på en måte. Selv om Vite håndtere dette automatisk er det fint å få bort denne meldingen fra bygget.
=> Resolve warning in build step

src/pages/research_profile/ResearchProfile.tsx
Unngå å rendre `0` om en person mangler resultater eller prosjekt.
Feilen ble trolig introdusert her: https://github.com/BIBSYSDEV/NVA-Frontend/pull/6899
Før:
Etter:
=> Avoid showing zeros on research profile

src/pages/registration/FilesAndLicensePanel.tsx, src/pages/registration/files_and_license_tab/FilesTableRow.tsx, src/pages/registration/helpers/fileHelpers.test.ts, src/pages/registration/helpers/fileHelpers.ts, src/translations/nbTranslations.json, src/types/associatedArtifact.types.ts, src/utils/formik-helpers/formik-helpers.ts, src/utils/validation/registration/associatedArtifactValidation.ts
Bygger videre på https://github.com/BIBSYSDEV/NVA-Frontend/pull/6922
- Bruker må nå eksplisitt velge tilgjengelighet etter at fila er lastet opp (tidligere ble den automatisk satt til å være åpen fil)
- Vis feilmelding om filtypen ikke er satt til noe gyldig
Litt uheldig at vi har "Velg tilgjengelighet" her mens vi har en vanlig label i lisens. Årsaken er at label der er ulik i motsetning til tilgjengelighet, så det gir mer mening å ha egen label. Kunne ev. hatt label i stedet for denne placeholderen til Tilgjengelighet også om det er bedre.
=> Np 48439 handle uploaded file

src/pages/registration/DescriptionPanel.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-48568
Unngå å søke etter duplikat for hver input når tittelen er tom fra før. Se før/etter bilder for hva som skjer om jeg holder skriver "aaaaaa" fort.
Før:
Etter:
=> NP-48568 Avoid searching for duplicate on each key stroke

src/pages/registration/files_and_license_tab/FilesTableRow.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-48494
Sørg for at filter-tabellen alltid viser riktig antall celler. Ellers blir det synlige mangler i borders, og enda synligere når bruker ikke kan gjøre endringer på filer fordi de er disabled.
Det er en del logikk og sjekking her som gjør alt ganske tunglest, men ser ikke noen enklere løsning som ikke er å skrive om alt. Gjør det også vanskelig å se om det introduserer et nytt problem :( 
Kunstig stor diff pga indenteringsendring, men det som er gjort er i praksis bare å flytte sjekken for `showFileVersion` ett hakk opp. Enklere å reviewe sånne ting i "split" view enn "unified" jeg bruker til vanlig IMO.
Før:
Etter:
Ensure that the changes are aligned with the expectations of PO/designer before marking the PR as ready for …
=> NP-48494 Ensure correct number of cells in files table

src/api/hooks/useFetchOrganizationByIdentifier.ts, src/pages/basic_data/app_admin/central_import/ImportCandidatesMenuFilters.tsx, src/pages/search/FacetItem.tsx, src/pages/search/FacetListItem.tsx, src/pages/search/person_search/PersonFacetsFilter.tsx, src/pages/search/project_search/ProjectFacetsFilter.tsx, src/pages/search/registration_search/RegistrationSearchBar.tsx, src/pages/search/registration_search/filters/RegistrationFacetsFilter.tsx, src/pages/search/registration_search/filters/SearchForInstitutionFacetItem.tsx, src/pages/search/registration_search/filters/SearchForInstitutionFacetListItem.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-48578
Legg til støtte for å søke etter institusjon i fasettvisningen.
Har også gått over til å sette bare organziation identifier i URL search param, i stedet for hele URI
=> Np 48578 search for institution facet

src/pages/messages/TasksPage.tsx, src/pages/messages/components/NviCandidatesList.tsx, src/pages/messages/components/TicketList.tsx
Ikke så mange endringer her. Ser vi har synlige headers på sider med resultatsøk i toppen (Rettelister). Usikker på om vi burde beholde det slik, eller legge til `visuallyHidden` her. [Ref denne kommentaren](https://github.com/BIBSYSDEV/NVA-Frontend/pull/7014#discussion_r1948545585)
=> NP-48525 Add new headers and updated titles for TasksPage

package-lock.json, package.json, src/components/StatusChip.tsx, src/components/styled/Wrappers.tsx, src/pages/public_registration/PublicProjectsContent.tsx, src/pages/registration/new_registration/RegistrationAccordion.tsx, src/pages/registration/resource_type_tab/components/SearchRelatedResultField.tsx, src/pages/search/advanced_search/AdvancedSearchPage.tsx, src/utils/log/logFactory.ts
Fjerner "Unlisted dependencies" issues som rapporteres av `knip`.
Litt motvillig å dra inn en ny pakke  `@mui/utils` da det vil gi enda mer PRs fra dependabot, men tenker å lage egen PR som gjør at dependabot grupperer Uppy- og MUI-pakker i samlede PRs
=> Cleanup mui usage

src/api/hooks/useSearchForPerson.ts, src/pages/dashboard/HomePage.tsx, src/pages/search/person_search/PersonFacetsFilter.tsx, src/pages/search/project_search/ProjectFacetsFilter.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-48581
- Fikser loading på fastetter for prosjekt og person, på samme måte som for resultat https://github.com/BIBSYSDEV/NVA-Frontend/pull/7027
- Fjerner noe gammel kode som bare ser ut til å gi feil, feks at personsøk defaulter til "." som søketerm, da det tidligere var påkrevd av APIet men ikke ser ut til å være det lenger
- Sørg for at både prosjekt- og personsøk bruker siste versjon av søketerm, med `syncParamsWithSearchFields`
Vanskelig å si helt sikkert at dette ikke påvirker noe annet negativt, men det gir mening for meg iaf 🤔 
I ettertid ser jeg at dette gjerne kunne vært delt opp i 2-3 PRs 😬 men skal gi mening å ta QA commit for commit også
Ensure that the changes are aligned with the expectations of PO/designer before …
=> Np 48581 show loading facets

src/api/fileApi.ts
Løs feil hvor feil ved filopplasting fortsatt legger til en "tom" fil. Dette skjer fordi den gamle `authenticatedApiRequest` eksplisitt svelger alle errors [her](https://github.com/BIBSYSDEV/NVA-Frontend/blob/develop/src/api/apiRequest.ts#L28)
Før:
https://github.com/user-attachments/assets/ee2bef8f-0213-4531-b574-99cac4ccd9b1
Etter:
https://github.com/user-attachments/assets/ce449762-cb48-4d1e-8bac-365074cdf9b3
=> Avoid swallowing file upload error

src/components/ContributorSearchField.tsx, src/pages/search/registration_search/filters/SearchForContributorFacetItem.tsx
Løser feil som ble introdusert [her](https://github.com/BIBSYSDEV/NVA-Frontend/pull/7043), hvor søket blir gjort selv om søketermen er tom. Burde trolig rulle ut til prod når dette er klart, siden det er en såpass ny bug som også ble rullet ut dit.
Før:
Etter:
=> Hide person pagination when no search

src/pages/basic_data/app_admin/AddAdminDialog.tsx, src/pages/basic_data/app_admin/CustomerInstitutionAdminsForm.tsx, src/pages/basic_data/app_admin/UserList.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-48634
Unngå feil i oversikten av en kundeinstitusjon for app-admin, hvor det ikke var mulig å fjerne mer enn en administrator om gangen. Når man fjernet en havned dialogen i en evig loading state, sånn at man måtte laste siden på nytt for å kunne fjerne en annen administrator.
Skrev om til å bruke `useMutation`, da det som var her var veldig gammelt. Ser også ut som dette var en generell komponent før, mens den nå bare brukes for adminstratorer på kunde, så fikk ryddet opp i litt gammel moro
_Note: some of these criterias may not always be relevant, and can simply be …
=> Np 48634 allow removing multiple roles

src/pages/public_registration/action_accordions/PublishingAccordion.tsx, src/translations/nbTranslations.json
Link to Jira issue: https://sikt.atlassian.net/browse/NP-48639
Vis oppdatert info når publiseringskurator avviser fil(er) da ticket og resultat som regel ikke er i synk med en gang. Viser nå i stedete en "Last på nytt"-knapp som vi har for godkjenning fra før
=> NP-48639 Show refresh option for rejected files

src/pages/public_registration/log/LogEntry.tsx, src/types/log.types.ts
Link to Jira issue: https://sikt.atlassian.net/browse/NP-48654
Vis institusjonens kortnavn. Lager en PR med dette for å få bort feilen med at bare ikoner for person og institusjon vises uten noen tekst i noen tilfeller.
La også inn visning av kortnavn i samme slengen, selv jeg egentlig ikke tror det er noen vits i det ref [denne kommentaren](https://sikt.atlassian.net/browse/NP-48654?focusedCommentId=112526)
=> NP-48654 Hide name and institution of log entry when empty

src/pages/projects/ProjectGeneralInfo.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-48640
Vis hele treet for koordinerende institusjon, ikke bare løvnode om man har valgt en bestemt enhet.
Før:
Etter:
=> NP-48640 Show full organization for coordinating unit

src/pages/public_registration/action_accordions/PublishingAccordion.tsx, src/pages/public_registration/action_accordions/RefreshPublishingRequestButton.tsx, src/translations/nbTranslations.json
Link to Jira issue: https://sikt.atlassian.net/browse/NP-48656
Added a refresh button to `PublishingAccordion` when there is a mismatch between publication status and number of `associatedArtifacts`
=> NP-48656 add refresh button for files after deletion

src/utils/validation/registration/associatedArtifactValidation.ts
Krev at bruker oppgir filtype før man kan publisere.
Dette fordi det gir noen problemer for backend ellers, bl.a. siden HiddenFile ikke krever godkjenning.
=> Require file type before publishing

src/pages/public_registration/action_accordions/DoiRequestAccordion.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-48668
Åpne DOI-panelet automatisk om man publiserer et resultat som har en reservert DOI fra før, siden den da også vil ha en DOI-forespørsel.
Jobber videre med å justere suksessmelding ved publisering til å inkludere at DOI-forespørsel også er sendt til godkjenning.
=> NP-48668 Open DOI accordion if a new DOI request is created

src/pages/messages/components/NviCandidateActionPanel.tsx, src/pages/public_registration/ActionPanel.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-48542
Vis den nye loggen i stedet for den gamle også når man ikke har satt `beta=true`.
Fjerner logikk knyttet til gammel logg.
=> NP-48542 Use new log by default

src/pages/basic_data/institution_admin/edit_user/AreaOfResponsibility.tsx, src/pages/basic_data/institution_admin/edit_user/ViewingScopeChip.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-48693
Forenkle prosessen med å endre ansvarsområde ved å ta vekk eksisterende enheter som ikke gir mening å ha samtidig som den nylig valgte:
- Fjern eventuelle eksisterende underenheter til nylig valgte ansvarsområde
- Fjern eventuelle eksisterende forelder-enheter til nylig valgte ansvarsområde
=> Np 48693 ensure consistent area of responsibility

src/pages/basic_data/institution_admin/edit_user/AreaOfResponsibility.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-48693
Legger til en lasteindikator når man velger ansvarsområde. Uten dette ble det noen gang stående som et input-felt man fortsatt kunne endre
Utbedring av glipp fra https://github.com/BIBSYSDEV/NVA-Frontend/pull/7129.
=> NP-48693 Handle loading of selected area of responsibility

src/components/AutocompleteTextField.tsx
Løst en feil med `AutocompleteTextField` hvor label tidligere kunnne bli minimert selv om den ikke hadde noen innhold, fordi `<></>` tolkes som innhold.
Før:
Etter:
=> Ensure AutocompleteTextField handles label shrink correctly

src/pages/basic_data/app_admin/central_import/ImportCandidatesMenuFilters.tsx, src/pages/search/FacetListItem.tsx, src/pages/search/person_search/PersonFacetsFilter.tsx, src/pages/search/project_search/ProjectFacetsFilter.tsx, src/pages/search/registration_search/filters/RegistrationFacetsFilter.tsx
Bruk samme loading prop i sentralimport som for andre søk for å vise lasting i fasettene. Fjerner også den gamle måten med å disable verdier når man laster den, siden den nå er erstattet av denne nye.
=> Np 47365 show loading state for central import facets

src/layout/header/Header.tsx, src/layout/header/Logo.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-48526
In this PR:
- Made the `Header` component use `flex` instead of using `grid`. This is to ensure support for increasing text-size in the broser up to 200%. Previously, the content of the header would extend horizontally, without wrapping. Now, it allows elements to wrap with increased text-size, while still maintaining the correct layout in "default-mode".
Before:
After:
The screenshots above are taken with 200% text-zoom.
This is the first step in the process of adding support for text-zoom. There is still some horizontall scrolling due to `minWidth` being set on different componens.
Also ensure that the …
=> NP-48526 Update header responsiveness

src/pages/basic_data/app_admin/central_import/CentralImportCandidateMerge.tsx, src/pages/public_registration/PublicGeneralContent.tsx, src/pages/public_registration/PublicRegistrationContent.tsx, src/pages/registration/RegistrationForm.tsx, src/pages/registration/resource_type_tab/components/NviValidation.tsx, src/types/registration.types.ts, src/utils/formik-helpers/formik-helpers.ts, src/utils/hooks/useJournalSeoData.ts, src/utils/nviHelpers.ts, src/utils/registration-helpers.ts
Link to Jira issue: https://sikt.atlassian.net/browse/NP-48720
Håndter åpning av resultat som mangler `publicationInstance` om man starter registrering med enkelte lenker.
Har oppdatert typene, sånn at de gjenspeiler virkeligheten litt bedre med at både `publicationInstance` og `publicationContext` kan mangle og at dette faktisk håndteres.
=> Np 48720 handle missing publication instance

src/pages/public_registration/PublicPublicationContext.tsx
Link to Jira issue: Delvis utspring fra https://sikt.atlassian.net/browse/NP-48754
Før:
Etter:
=> Show unknown when artistic output has no values to show

src/pages/public_registration/PublicRegistrationContributors.tsx, src/translations/nbTranslations.json, src/utils/registration-helpers.ts
Link to Jira issue: https://sikt.atlassian.net/browse/NP-48754
Vis bidragsytere med roller som ikke er kompatible med valgt kategori på landing page. Tidligere ble disse skjult.
Se eksempel under for bilde med et resultat hvor Isar har en rolle som egentlig ikke er kompatibel med kategorien.
Før:
Etter:
=> Np 48754 show contributor with invalid role on landing page

src/utils/nviHelpers.ts
Link to Jira issue: https://sikt.atlassian.net/browse/NP-48758
Håndter ubekreftede bidragsytere for advarsel om NVI-nullstillinger. Mistenker vi kunne gjort flere andre forenklinger i flyten her, som er kommentert i Jira: https://sikt.atlassian.net/browse/NP-48758?focusedCommentId=113435
Jobber videre med ny PR som legger inn testing av dette rundt når NVI-advarsler skal vises.
=> Np 48758 avoid wrong warning about nvi reset

src/pages/public_registration/PublicRegistration.tsx, src/pages/public_registration/RegistrationLandingPage.tsx, src/pages/public_registration/RegistrationSummary.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-48798
Dette skal løse problemet med at tilbake-knappen forsvinner når man navigerer videre inni ett søketreff, feks at man åpner ett av kapitlene etter man har åpnet en bok fra søketreff. 
En ulempe med dette er at tilbake-knappen nå bare blir en `<button>` i stedet for `<a>`, men tror likevel dette er den beste løsningen.
=> Np 48798 back button

src/pages/public_registration/log/LogPanel.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-48542 (egentlig en standalone sak, men lenker til denne som er relatert)
Etter importkjøring har det dukket opp noen logg entries som ikke er sortert i kronologisk rekkefølge fra APIet, så vi må sørge for at de er riktig sortert i frontend også.
Eks: https://nva.sikt.no/registration/46205384-9f16-4995-9cf6-6f83a7e0d2a5
=> Ensure log entries are sorted chronologically

src/pages/messages/components/NviApprovals.tsx, src/pages/messages/components/NviCandidateActionPanel.tsx, src/pages/messages/components/NviDialoguePanel.tsx, src/pages/messages/components/TicketListItem.tsx, src/pages/public_registration/PublicRegistration.tsx, src/pages/public_registration/RegistrationLandingPage.tsx, src/pages/public_registration/RegistrationSummary.tsx, src/pages/public_registration/log/LogPanel.tsx, src/pages/registration/FileList.tsx, src/pages/registration/new_registration/EditRegistration.tsx, src/pages/registration/new_registration/UploadFileRegistration.tsx, src/translations/enTranslations.json, src/translations/nbTranslations.json, src/translations/nnTranslations.json, src/types/license.types.ts, src/utils/dataTestIds.ts
:rocket: Ny funksjonalitet :rocket:
* Legg til støtte for å starte registrering med filopplasting ([NP-48761](https://sikt.atlassian.net/browse/NP-48761))
* NB! Vi har har hatt støtte for dette tidligere også, men det ble midlertidig tatt vekk i starten av februar pga tekniske endringer
* Tillat åpning av en NVI-kandidat man ikke har lov til å godkjenne, men skjul knapper og felter som da ikke er relevante ([NP-48820](https://sikt.atlassian.net/browse/NP-48820))
:bug: Bugfiks :bug:
* Løst feil hvor tilbake-knappen noen ganger forsvant om man navigerte videre til andre resultater fra et søketreff ([NP-48798](https://sikt.atlassian.net/browse/NP-48798))
* Løst feil hvor det ikke var mulig for kurator å åpne en ticket knyttet til et resultat som var avpublisert med en duplikat, da man …
=> Update staging 28.03.25

.github/dependabot.yml
Samle alle React-oppdatering i samme PR fra dependabot.
I dag er disse delt i to grupper:
- `react`: https://github.com/BIBSYSDEV/NVA-Frontend/pull/7238
- `react-dom`: https://github.com/BIBSYSDEV/NVA-Frontend/pull/7235
=> Add react group to dependabot

src/pages/registration/files_and_license_tab/FilesTableRow.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-48810
When a user has already selected a license, but not a file version, the license field was reset when "published version" was selected. Now, the selected license remains unless the previously selected version was "Accepted"
=> NP-48810 Keep license when version is selected

src/pages/registration/description_tab/RegistrationFunding.tsx, src/utils/validation/registration/fundingValidation.ts
Link to Jira issue: https://sikt.atlassian.net/browse/NP-48863
Finansiering uten prosjekt krever nå _enten_ navn eller identifier for hver finansiering. Om begge mangler viser navn-feltet valideringsfeil for begge feltene, mens begge boksene er markert som error.
=> Np 48863 validate funding

src/api/searchApi.ts, src/pages/messages/components/NviCorrectionList.tsx, src/utils/hooks/useRegistrationSearchParams.ts
Link to Jira issue: https://sikt.atlassian.net/browse/NP-48882
Replace `scientificValue`-param with `allScientificValue`-param for the `  ApplicableCategoriesWithNonApplicableChannel` correction list.
=> NP-48882 Ajust param for correction list

src/pages/public_registration/public_files/FileUploaderInfo.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-48879
Fiks slurv ved visning av hvor en importert fil kommer fra.
Feilen ble introdusert her: https://github.com/BIBSYSDEV/NVA-Frontend/issues/7228
Før:
Etter:
=> NP-48879 Fix wrong parameter for imported file uploader

src/api/registrationApi.ts, src/api/searchApi.ts, src/pages/registration/new_registration/LinkRegistration.tsx, src/utils/general-helpers.ts
Link to Jira issue: https://sikt.atlassian.net/browse/NP-48883
Sørg for at bruker får advarsel om at DOIen allerede finnes i NVA uansett om den er oppgitt som `<DOI>`, `https://doi.org/<DOI>`, `https://dx.doi.org/<DOI>`, etc. Nå vil vi ikke lenger automatisk omformatere en DOI til en DOI-URL.
=> NP-48883 Fix duplicate search when starting registration with DOI

src/pages/public_registration/PublicSummaryContent.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-48984
Vis alle sammendrag uansett hvilket språk de er angitt på. Prøver også å slå opp navnet på språket med å finne matchende ISO-kode. For `und` (undefined) viser vi ingenting.
Når language er satt til `und`:
Men norsk språk i appen (liten forbokstav på språk):
Men engelsk språk i appen (stor forbokstav på språk):
=> Np 48984 show all alternative abstracts

src/pages/basic_data/fields/StartDateField.tsx, src/pages/basic_data/institution_admin/AddAffiliationSection.tsx, src/pages/basic_data/institution_admin/edit_user/AffiliationFormSection.tsx, src/pages/messages/components/TicketDateIntervalFilter.tsx, src/pages/registration/resource_type_tab/components/PeriodFields.tsx, src/pages/registration/resource_type_tab/sub_type_forms/artistic_types/architecture/CompetitionModal.tsx, src/pages/registration/resource_type_tab/sub_type_forms/artistic_types/architecture/PublicationMentionModal.tsx, src/pages/registration/resource_type_tab/sub_type_forms/artistic_types/literary_art/LiteraryArtsPerformanceModal.tsx, src/themes/mainTheme.ts
Løser bug som ble oppdaget i e2e av  @Eiriknil, med at bruker noen ganger ikke får lov til å velge måned når man skal velge dato.
Legger inn at vi som default skal vise år, måned og dag for alle date pickers ved å oppdatere i theme: https://mui.com/x/react-date-pickers/quickstart/#theme-augmentation
=> Ensure user must select month for date pickers

src/pages/registration/RegistrationForm.tsx
Tar bort loading for henting av channel claim da det i mange tilfeller fører til evig loop med refetching og loading state her.
Må jobbes videre med å finne en bedre løsning.
=> Remove loading state for fetching channel claim

src/pages/messages/components/TicketList.tsx, src/translations/nbTranslations.json
Link to Jira issue: https://sikt.atlassian.net/browse/NP-49038
GI bruker snarvei til å se leste/alle dialoger når man søker etter uleste meldinger men ikke får noen treff
=> NP-49038 Add button to show read messages when no unread

src/pages/editor/AddChannelClaimDialog.tsx
Unngå at exception kastes i browser når man får 4xx fra API ved lagring. Dette gir igjen problemer i e2e-testene
=> Swallow exception from API when saving claim

.github/dependabot.yml
Sørg for at `@typescript-eslint`-pakker kommer i samme dependabot-PR som andre eslint-pakker
=> Add @typescript-eslint packages to eslint dependabot group

src/translations/nbTranslations.json
Link to Jira issue: https://sikt.atlassian.net/browse/NP-49267
Erstatt "Du kan" etc med "Brukeren kan".
Nye tekster:
=> NP-49267 Update wording of license texts

src/matomo/matomo.ts
https://matomo.org/faq/how-to/how-do-i-enable-basic-javascript-error-tracking-and-reporting-in-matomo-browser-console-error-messages/
Test ut løsning som logger errors i konsollen til Matomo.
Merk at disse ikke vil inkludere noe stacktrace, så vil ikke nødvendigvis gjøre det enkelt å vite hvordan errors kan løses, men kan i hvert fall gi oss en indikasjon på hvor brukere opplever feil.
=> Add Matomo error tracking

src/pages/public_registration/ActionPanel.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-49285
Tillat alltid å flytte ticket om APIet sier det er lov i allowedoperations på ticket
=> NP-49285 Always allow ticket transfer from allowedOperations

src/components/institution/SelectInstitutionForm.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-49288
Unngå at institutsjonsfelt er i loading state som default
Før:
Etter:
=> NP-49288 Avoid showing loading state before user has searched

amplify.yml
Sett node-versjon til 22 for bygget i amplify, da v18 som brukes i dag ikke virker for vite v7.
Trodde vi allerede brukte siste versjon av node i bygget her også, men tydeligvis ikke.
Har verifisert at det virker å sette dette direkte i amplify, men foretrekker å ha det som IaC her i stedet.
=> Set node version in amplify.yml

amplify.yml
Følger opp https://github.com/BIBSYSDEV/NVA-Frontend/pull/7533 da dette ikke virker.
Fiksen er i stedet å sette enten node:22 som image, eller å bruke Amazon Linux 2023, og sette node-versjon til 22 under "Live package updates". Har nå gått for førstnevnte.
=> Set node version in amplify

.github/dependabot.yml, eslint.config.js, package-lock.json, package.json, src/utils/tests/nviHelpers.test.ts
Forenkler og forbedrer eslint config nå som alt har støtte for flat config.
Har erstattet `@typescript-eslint/eslint-plugin` og `@typescript-eslint/parser` med `typescript-eslint`, og tatt i bruk `eslint-plugin-prettier` som tilsynelatende har vært i package.json uten å ha vært konfigurert opp tidligere 😬
=> Update eslint config

src/components/BetaFunctionality.tsx, src/pages/basic_data/BasicDataPage.tsx, src/pages/basic_data/app_admin/central_import/CentralImportDuplicationCheckPage.tsx, src/utils/urlPaths.ts
Link to Jira issue: https://sikt.atlassian.net/browse/NP-49449
Endrer på at man må bruke betafunksjonalitet ved merging til at man kan velge om man vil bruke gammel eller beta-versjon. Beta-knapp er bare synlig om man har satt beta-flagg
=> NP-49449 Allow using old and new mering functionality

src/components/ServiceBanner.tsx
=> Remove redundant padding for env banner

src/pages/editor/VocabularyOverview.tsx, src/translations/nbTranslations.json
Link to Jira issue: [NP-49668](https://sikt.atlassian.net/browse/NP-49668)
Legger til en standardtekst derson institusjonen ikke har valgt vokabular.
Før:
Etter:
[NP-49668]: https://sikt.atlassian.net/browse/NP-49668?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> NP-49668 Add fallback text to vocabulary

src/components/TicketTypeFilterButton.tsx, src/pages/messages/TasksPage.tsx, src/pages/messages/components/DoiRequestMessagesColumn.tsx, src/pages/messages/components/PublishingRequestMessagesColumn.tsx, src/pages/messages/components/SupportMessagesColumn.tsx, src/pages/messages/components/TicketListItem.tsx, src/pages/my_page/MyPagePage.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-49823
Legger til ikoner for å vise hvilken type ticket det er snakk om.
Fører til et litt rart fargespill noen steder, men tenker dette egentlig er bra nok for første iterasjon, så blir det å jobbe videre med fargene
Synlig på:
- Oppgaveliste: http://localhost:3000/tasks
- Mine brukerdialoger: http://localhost:3000/my-page/messages/my-messages
=> Np 49823 show ticket type icons

src/pages/messages/components/NviStatusPage.tsx, src/pages/messages/components/NviYearSelector.tsx
Fikser responsiviteten på NVI-søk, da noen filter nå kan strekke seg ut av skjermen ved noen oppløsninger
Affected part of the application: http://localhost:3000/tasks/nvi
Før:
Etter:
=> Fix responsiveness of NVI search filters

src/pages/registration/description_tab/DatePickerField.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-49851
Unngå feil hvor et resultat har koblinger til kanaler med andre år enn året resultatet er publisert.
1. Åpne nytt resultat i wizard
2. Gå til kategori-fanen og sett en kanal (tidsskrift, utgiver, eller serie)
3. Gå til beskrivelse-fanen og sett et vilkårlig årstall som publiseringsdato
4. Lagre og sjekk oppdatert resultat i nettverksloggen
5. `entityDescription.publicationDate.year` må samsvare med siste del av kanal-ID for at NVI-rapportering skal bli riktig. 
Kanal-ID kan være `publicationContext.id` (tidsskrift), `publicationContext.publisher.id` (utgiver), eller `publicationContext.series.id` (serie) avhengig av hvilken type det er
Ensure that the changes are aligned with the expectations of PO/designer before marking the …
=> Np 49851 sync channel id with selected year

src/components/merge_results/fields/CompareFiles.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-49768
Legger til `beta`-sjekk for å flytte over fil, siden dette ikke virker i praksis uansett. Siden dette brukes for sentralimport nå kom jeg på at vi faktisk må unngå at folk mister ting her.
Affected part of the application: http://localhost:3000/basic-data/central-import?files=hasPublicFiles
1. Finn en importkandidat med fil
2. Prøv å slå sammen med eksisterende resultat
3. Se at fil-flytting ligger i beta-felt
=> NP-49768 Move file copy to beta tag

src/api/hooks/useFetchProjects.tsx, src/pages/frontpage/CategorySection.tsx, src/pages/frontpage/FrontPage.tsx, src/pages/frontpage/NvaDescriptionSection.tsx, src/pages/frontpage/SearchSection.tsx, src/pages/frontpage/TypeCard.tsx, src/pages/frontpage/styles.ts, src/pages/project/project_wizard/RelatedProjectsField.tsx
Link to Jira issue: [NP-49842](https://sikt.atlassian.net/browse/NP-49842)
Insert numbers in the main search categories on the front page:
Affected part of the application: [Front page](http://localhost:3000/new-front-page)
This PR performs one search for each of the areas projects, results and persons and displays number of hits in the respective box.
Have added skeleton for when numbers load.
Also I think I takes way too long after we click a box before the page even reacts and re-routes to the search. Don't know if this is something to fix in this PR or if it is an app-issue?
_Note: some of these criterias may not always …
=> Number of hits for each of the main search sections on front page

src/layout/header/Header.tsx
Link to Jira issue: https://sikt.atlassian.net/browse/NP-49806
La "<Siktlogo> Nasjonalt Vitenarkiv" lenke til ny forside, mens Søkeikonet lenker til nye "/filter". Om man allerede står på avansert søk lar jeg søkeikon fortsatt peke til avansert søk.
Sjekk lenker i header.
=> NP-49806 Update header links according to new front page

src/utils/validation/registration/referenceValidation.ts
Link to Jira issue: https://sikt.atlassian.net/browse/NP-49914
Unngå å gi valideringsfeil på at man har en uidentifisert serie når kategorien ikke skal ha serie. Dette kan skje om importert data har andre regler enn vi har i NVA.
Før: https://dev.nva.sikt.no/registration/0199956ab0ae-a2009854-e384-4a23-bbe4-fa7787d7d714/edit
Etter: http://localhost:3000/registration/0199956ab0ae-a2009854-e384-4a23-bbe4-fa7787d7d714/edit
Validering skal virke som før for kategorier som skal kunne ha serie
=> NP-49914 Validate series only for categories where it is relevant

src/utils/hooks/useAuthErrorListener.ts
Link to Jira issue: https://sikt.atlassian.net/browse/NP-49917
Unngå at bruker får feilmelding når om man avbryter ett innloggingsforsøk.
1. Trykk på "logg inn"
2. Trykk tilbake i nettleseren uten å gjøre noe mer
3. Se at man da får feilmelding om at "Innlogging feilet", selv om man ikke har prøvd å logge inn
=> NP-49917 Avoid error message when use cancells login

src/pages/public_registration/log/LogEntryItem.tsx, src/types/log.types.ts
Link to Jira issue: https://sikt.atlassian.net/browse/NP-49928
Tillat alle loggmeldinger å ha importkilde, og vis dem for alle. Backend vil legge til `importSource` for flere logg-typer fremover i [denne oppgaven](https://sikt.atlassian.net/browse/NP-49929).
Affected part of the application: http://localhost:3000/registration/01999d25deff-7bb3eb43-6bb8-40e3-8b42-a05da3d8beda
Siden det bare er testmiljøet som har data for dette er det litt ekstra knot å verifisere:
1. Endre `.env` til å peke mot test-miljøet
2. Siden test-miljøet ikke er satt opp til å fungere mot localhost må man ha en CORS-plugin i nettleser for at API-kall skal virke, feks [CORS Everywhere](https://addons.mozilla.org/nb-NO/firefox/addon/cors-everywhere/?utm_content=addons-manager-reviews-link&utm_medium=firefox-browser&u …
=> NP-49928 Show importSource for all log entries

src/pages/project/project_wizard/DescriptionInput.tsx, src/pages/project/project_wizard/ProjectDescriptionForm.tsx, src/pages/project/project_wizard/ProjectForm.tsx
Link to Jira issue: [NP-49960](https://sikt.atlassian.net/browse/NP-49960)
Add length validation to all summary fields, because the API does not allow summaries that are more than 4000 characters long.
Also discovered that there is a discrepancy between how we handle errors in the axios-function and in the components, so that we don't actually catch the errors returned from the API. This results in no error message shown to the user when save results in error. Fixed this in the project form, but we should look into if this happens several places in the app and consider if we want to change the axios-function or each view that posts a form.
Affected part of the application: [New project view](http://localhost:3000/projects/new)
**Before this PR:**
Start creating a new project and type a …
=> Add max length validation and character count for project summary fields
